"""
LeetCode Daily Agent — Main Entrypoint

Orchestrates the full daily workflow:
1. Validates LeetCode session credentials & logs authentication status
2. Fetches today's daily problem metadata & starter code
3. Retrieves solution (Community scraping Tier 1-3 with Gemini AI solver Tier 4 fallback)
4. Submits solution via Playwright multi-strategy engine
5. Saves the solution to the solutions/ directory
6. Sends notification via Telegram
"""
import os
import re
import sys
import json
import logging
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

from leetcode_api import check_user_session
from solver import solve_daily
from submit import submit_solution
from notifier import send_telegram_notification

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")


SOLUTIONS_DIR = "solutions"
SESSION_FILE = "leetcode_session.json"


def sanitize_filename(name):
    """Converts a problem title to a safe filename."""
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


def save_solution(date_str, title, frontend_id, code, result, language="python3"):
    """Saves the solution with rich metadata to the solutions/ directory."""
    os.makedirs(SOLUTIONS_DIR, exist_ok=True)

    ext = ".py"
    if language in ["mysql", "sql"]:
        ext = ".sql"
    elif language in ["javascript", "js"]:
        ext = ".js"
    elif language in ["typescript", "ts"]:
        ext = ".ts"

    safe_title = sanitize_filename(title)
    filename = f"{date_str}-{safe_title}{ext}"
    filepath = os.path.join(SOLUTIONS_DIR, filename)

    header = f'''# LeetCode Daily Challenge
# Date: {date_str}
# Problem: #{frontend_id} {title}
# Language: {language}
# Submission Result: {result}
# Auto-generated by LeetCode Agent

'''

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(header + code)

    logging.info(f"Solution saved to {filepath}")
    return filepath


def main():
    logging.info("=" * 60)
    logging.info("LeetCode Daily Agent Starting...")
    logging.info("=" * 60)

    # Check if session file exists
    if not os.path.exists(SESSION_FILE):
        logging.error(f"Session file '{SESSION_FILE}' not found!")
        logging.error("Run 'python login_setup.py' first to generate the session file.")
        sys.exit(1)

    try:
        with open(SESSION_FILE, "r", encoding="utf-8") as f:
            session_data = json.load(f)
    except Exception as e:
        logging.error(f"Session file '{SESSION_FILE}' is not valid JSON: {e}")
        logging.error("Please ensure your LEETCODE_SESSION_JSON secret is a valid JSON dictionary.")
        sys.exit(1)

    # Validate session status against LeetCode API
    cookies = {c["name"]: c["value"] for c in session_data.get("cookies", [])}
    auth_status = check_user_session(cookies)
    if auth_status.get("is_signed_in"):
        logging.info(f"✅ Authenticated to LeetCode as: {auth_status.get('username')}")
    else:
        logging.warning("⚠️ Session cookie is not logged in or has expired! Submissions may require session renewal.")
        logging.warning("Run 'python login_setup.py' to update LEETCODE_SESSION_JSON if submissions fail.")
        from notifier import send_session_expired_alert
        send_session_expired_alert(username=auth_status.get("username"))

    # Step 1 & 2: Fetch daily problem + get solution
    result = solve_daily()
    if not result:
        logging.error("Failed to fetch or solve the daily problem. Exiting.")
        sys.exit(1)

    logging.info(f"Problem: #{result.get('frontend_id')} {result['title']} ({result['difficulty']})")
    logging.info(f"Date: {result['date']}")
    logging.info(f"Language: {result['language']}")
    logging.info(f"Code length: {len(result['code'])} characters")

    # Step 3: Submit the solution
    logging.info("Submitting solution via Playwright engine...")
    submission_result = submit_solution(
        question_slug=result["slug"],
        code=result["code"],
        language=result["language"],
        question_id=result.get("question_id"),
        session_file=SESSION_FILE,
    )

    if submission_result:
        logging.info(f"Submission Result: {submission_result}")
    else:
        logging.warning("Could not determine submission result. Solution will still be saved.")
        submission_result = "Unknown"

    # Step 4: Save the solution
    filepath = save_solution(
        date_str=result["date"],
        title=result["title"],
        frontend_id=result.get("frontend_id", ""),
        code=result["code"],
        result=submission_result,
        language=result["language"],
    )

    # Step 5: Send Notification
    problem_url = f"https://leetcode.com/problems/{result['slug']}/"
    send_telegram_notification(result['title'], result['difficulty'], submission_result, problem_url=problem_url)


    logging.info("=" * 60)
    logging.info("Daily challenge run complete!")
    logging.info(f"  Problem:    #{result.get('frontend_id')} {result['title']}")
    logging.info(f"  Difficulty: {result['difficulty']}")
    logging.info(f"  Result:     {submission_result}")
    logging.info(f"  Saved to:   {filepath}")
    logging.info("=" * 60)


if __name__ == "__main__":
    main()

