"""
LeetCode Daily Agent — Main Entrypoint

This is the orchestration script that runs the full daily workflow:
1. Fetch today's daily problem
2. Get a community solution
3. Submit it via Playwright
4. Save the solution to the solutions/ directory
"""
import os
import re
import sys
import logging
from datetime import datetime

from solver import solve_daily
from submit import submit_solution
from notifier import send_discord_notification

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

SOLUTIONS_DIR = "solutions"
SESSION_FILE = "leetcode_session.json"


def sanitize_filename(name):
    """Converts a problem title to a safe filename."""
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


def save_solution(date_str, title, code, result, language="python3"):
    """Saves the solution to the solutions/ directory."""
    os.makedirs(SOLUTIONS_DIR, exist_ok=True)
    
    ext = ".py"
    if language == "mysql":
        ext = ".sql"
    elif language == "javascript":
        ext = ".js"
    
    safe_title = sanitize_filename(title)
    filename = f"{date_str}-{safe_title}{ext}"
    filepath = os.path.join(SOLUTIONS_DIR, filename)

    header = f'''# LeetCode Daily Challenge
# Date: {date_str}
# Problem: {title}
# Submission Result: {result}
# Auto-generated by LeetCode Agent

'''
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(header + code)

    logging.info(f"Solution saved to {filepath}")
    return filepath


def main():
    logging.info("=" * 60)
    logging.info("LeetCode Daily Agent Starting...")
    logging.info("=" * 60)

    # Check if session file exists
    if not os.path.exists(SESSION_FILE):
        logging.error(f"Session file '{SESSION_FILE}' not found!")
        logging.error("Run 'python login_setup.py' first to generate the session file.")
        sys.exit(1)

    # Step 1 & 2: Fetch daily problem + get solution
    result = solve_daily()
    if not result:
        logging.error("Failed to fetch or solve the daily problem. Exiting.")
        sys.exit(1)

    logging.info(f"Problem: {result['title']} ({result['difficulty']})")
    logging.info(f"Date: {result['date']}")
    logging.info(f"Code length: {len(result['code'])} characters")

    # Step 3: Submit the solution
    logging.info("Submitting solution via Playwright...")
    submission_result = submit_solution(
        question_slug=result["slug"],
        code=result["code"],
        language=result["language"],
        session_file=SESSION_FILE,
    )

    if submission_result:
        logging.info(f"Submission Result: {submission_result}")
    else:
        logging.warning("Could not determine submission result. Solution will still be saved.")
        submission_result = "Unknown"

    # Step 4: Save the solution
    filepath = save_solution(
        date_str=result["date"],
        title=result["title"],
        code=result["code"],
        result=submission_result,
        language=result["language"],
    )

    # Step 5: Send Notification
    send_discord_notification(result['title'], result['difficulty'], submission_result)

    logging.info("=" * 60)
    logging.info(f"Daily challenge complete!")
    logging.info(f"  Problem:    {result['title']}")
    logging.info(f"  Difficulty: {result['difficulty']}")
    logging.info(f"  Result:     {submission_result}")
    logging.info(f"  Saved to:   {filepath}")
    logging.info("=" * 60)


if __name__ == "__main__":
    main()
