# LeetCode Daily Challenge
# Date: 2026-06-27
# Problem: Find the Maximum Number of Elements in Subset
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def maximumLength(self, input_numbers: List[int]) -> int:
        chain_lengths = {}

        for current_element in sorted(input_numbers, reverse=True):
            square_of_element = current_element * current_element
            
            if current_element != 1 and square_of_element in chain_lengths:
                chain_lengths[current_element] = chain_lengths[square_of_element] + 2
            else:
                chain_lengths[current_element] = 1
        
        max_non_unity_sequence_length = max(chain_lengths.values())
        
        count_of_ones = input_numbers.count(1)
        
        adjusted_ones_sequence_length = count_of_ones - (1 if count_of_ones % 2 == 0 else 0)
        
        return max(max_non_unity_sequence_length, adjusted_ones_sequence_length)