# LeetCode Daily Challenge
# Date: 2026-09-12
# Problem: #3414 Maximum Score of Non-overlapping Intervals
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

from bisect import bisect_left
from typing import List

class Solution:
    def maximumWeight(self, intervals: List[List[int]]) -> List[int]:
        processed_intervals = [(stop, start, cost, idx) for idx, (start, stop, cost) in enumerate(intervals)]
        processed_intervals.sort(key=lambda item: item[0])

        total_intervals = len(intervals)
        memo_table = [[(0, []) for _ in range(5)] for _ in range(total_intervals + 1)]

        for curr_idx, (curr_end, curr_start, curr_weight, curr_original_index) in enumerate(processed_intervals):
            prev_valid_idx = bisect_left(processed_intervals, (curr_start,), hi=curr_idx)
            
            for count in range(1, 5):
                accumulated_weight, accumulated_indices = memo_table[prev_valid_idx][count - 1]
                
                default_state = memo_table[curr_idx][count]
                
                new_weight = accumulated_weight - curr_weight
                new_indices = sorted(accumulated_indices + [curr_original_index])
                candidate_state = (new_weight, new_indices)
                
                memo_table[curr_idx + 1][count] = min(default_state, candidate_state)

        return memo_table[-1][4][1]