# LeetCode Daily Challenge
# Date: 2026-06-05
# Problem: Total Waviness of Numbers in Range II
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def __init__(self):
        self.current_number_string = ""
        self.memoization_table = []
        self.visited_states_tracker = []

    def _calculate_waviness_recursive(self, digit_position: int, is_number_started: int, last_seen_digit: int, second_last_seen_digit: int, is_tight_bound: bool) -> tuple[int, int]:
        if digit_position == len(self.current_number_string):
            return (1, 0)

        if not is_tight_bound and self.visited_states_tracker[digit_position][is_number_started][last_seen_digit][second_last_seen_digit]:
            return self.memoization_table[digit_position][is_number_started][last_seen_digit][second_last_seen_digit]

        upper_digit_bound = int(self.current_number_string[digit_position]) if is_tight_bound else 9

        current_state_total_count = 0
        current_state_total_waviness_sum = 0

        current_digit_choice = 0
        while current_digit_choice <= upper_digit_bound:
            next_tight_bound = is_tight_bound and (current_digit_choice == upper_digit_bound)

            if not is_number_started and current_digit_choice == 0:
                next_state_count, next_state_waviness = self._calculate_waviness_recursive(digit_position + 1, 0, 10, 10, next_tight_bound)

                current_state_total_count += next_state_count
                current_state_total_waviness_sum += next_state_waviness
            else:
                waviness_point_earned = 0

                if is_number_started and second_last_seen_digit != 10:
                    if (last_seen_digit > second_last_seen_digit and last_seen_digit > current_digit_choice) or \
                       (last_seen_digit < second_last_seen_digit and last_seen_digit < current_digit_choice):
                        waviness_point_earned = 1

                new_second_last_digit = last_seen_digit if is_number_started else 10
                new_last_digit = current_digit_choice

                next_state_count, next_state_waviness = self._calculate_waviness_recursive(digit_position + 1, 1, new_last_digit, new_second_last_digit, next_tight_bound)

                current_state_total_count += next_state_count
                current_state_total_waviness_sum += next_state_waviness + waviness_point_earned * next_state_count

            current_digit_choice += 1

        if not is_tight_bound:
            self.visited_states_tracker[digit_position][is_number_started][last_seen_digit][second_last_seen_digit] = True
            self.memoization_table[digit_position][is_number_started][last_seen_digit][second_last_seen_digit] = (current_state_total_count, current_state_total_waviness_sum)

        return (current_state_total_count, current_state_total_waviness_sum)

    def _get_total_wavy_count_up_to(self, target_number: int) -> int:
        if target_number < 0:
            return 0

        self.current_number_string = str(target_number)
        
        self.memoization_table = [[[[None for _ in range(11)] for _ in range(11)] for _ in range(2)] for _ in range(20)]
        self.visited_states_tracker = [[[[False for _ in range(11)] for _ in range(11)] for _ in range(2)] for _ in range(20)]

        _, total_waviness_result = self._calculate_waviness_recursive(0, 0, 10, 10, True)
        return total_waviness_result

    def calculate_range_waviness(self, start_range_val: int, end_range_val: int) -> int:
        return self._get_total_wavy_count_up_to(end_range_val) - self._get_total_wavy_count_up_to(start_range_val - 1)