# LeetCode Daily Challenge
# Date: 2026-08-07
# Problem: Smallest Divisible Digit Product II
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def smallestNumber(self, input_string: str, target_value: int) -> str:
        string_length = len(input_string)
        temp_target_divisor = target_value
        
        prime_factors_to_check = [2, 3, 5, 7]
        prime_idx = 0
        while prime_idx < len(prime_factors_to_check):
            current_prime = prime_factors_to_check[prime_idx]
            while temp_target_divisor % current_prime == 0:
                temp_target_divisor //= current_prime
            prime_idx += 1
            
        if temp_target_divisor != 1:
            return "-1"

        prefix_gcd_tracker = [target_value] * (string_length + 1)
        
        current_index = 0
        while current_index < string_length:
            current_char_digit = int(input_string[current_index])
            if current_char_digit == 0: 
                break
            
            # Assuming gcd is an available helper function from the problem context
            prefix_gcd_tracker[current_index + 1] = prefix_gcd_tracker[current_index] // gcd(prefix_gcd_tracker[current_index], current_char_digit)
            current_index += 1
            
        if prefix_gcd_tracker[string_length] == 1:
            return input_string

        start_backward_idx = (input_string.find("0") + string_length) % string_length if "0" in input_string else string_length - 1
        
        current_position_to_change = start_backward_idx
        while current_position_to_change >= 0:
            required_gcd_val = prefix_gcd_tracker[current_position_to_change]
            remaining_digits_count = string_length - 1 - current_position_to_change
            
            candidate_digit_val = int(input_string[current_position_to_change]) + 1
            while candidate_digit_val < 10:
                # Assuming gcd is an available helper function
                remaining_target_for_suffix = required_gcd_val // gcd(required_gcd_val, candidate_digit_val)
                
                # Assuming fill is an available helper function from the problem context
                generated_suffix = fill(remaining_target_for_suffix, remaining_digits_count)
                
                if len(generated_suffix) <= remaining_digits_count:
                    return input_string[:current_position_to_change] + str(candidate_digit_val) + generated_suffix
                
                candidate_digit_val += 1
            current_position_to_change -= 1

        # Assuming fill is an available helper function
        return fill(target_value, string_length + 1)