# LeetCode Daily Challenge
# Date: 2026-07-28
# Problem: Smallest Palindromic Rearrangement I
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

import collections
import string

class Solution:
    def smallestPalindrome(self, input_string: str) -> str:
        input_length = len(input_string)
        
        # Determine character frequencies from the initial segment of the input string.
        # This segment comprises the first half of the input_string.
        char_frequencies_first_half = collections.Counter(input_string[:input_length // 2])
        
        # Construct the left portion of the resulting palindrome.
        # Characters are appended in lexicographical order (a-z) based on their counts.
        left_segment_components = []
        alphabet_index = 0
        while alphabet_index < len(string.ascii_lowercase):
            current_character_from_alphabet = string.ascii_lowercase[alphabet_index]
            # If the current character exists in our frequency map, append it
            # repeated by its count.
            if current_character_from_alphabet in char_frequencies_first_half:
                left_segment_components.append(current_character_from_alphabet * char_frequencies_first_half[current_character_from_alphabet])
            alphabet_index += 1
        generated_left_segment = "".join(left_segment_components)
        
        # Identify the central character if the palindrome's total length is odd.
        # If the input_length is odd, the middle character is taken from the input_string.
        # Otherwise, there is no central character, so an empty string is used.
        central_character_for_result = input_string[input_length // 2] if (input_length % 2 != 0) else ""
        
        # Assemble the complete palindrome: left segment + central character + reversed left segment.
        return generated_left_segment + central_character_for_result + generated_left_segment[::-1]