# LeetCode Daily Challenge
# Date: 2026-03-14
# Problem: The k-th Lexicographical String of All Happy Strings of Length n
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import collections

class Solution:
    def getHappyString(self, desired_length: int, desired_kth_string: int) -> str:
        # Map each character to its valid successor characters
        successor_chars_mapping = {
            'a': 'bc',
            'b': 'ac',
            'c': 'ab'
        }

        # Initialize a double-ended queue with the starting single-character happy strings
        candidate_strings_queue = collections.deque(['a', 'b', 'c'])

        # Continuously generate longer happy strings until they reach the desired length
        # At any point in the outer loop, all strings in the queue will have the same length
        while len(candidate_strings_queue[0]) < desired_length:
            # Retrieve the lexicographically smallest (first) string of the current length
            current_base_string = candidate_strings_queue.popleft()
            
            # Identify the last character of the current base string
            last_character_in_base = current_base_string[-1]
            
            # Get the allowed characters that can follow the last character
            available_next_characters = successor_chars_mapping[last_character_in_base]
            
            # Iterate through each possible next character to form new strings
            character_iterator_index = 0
            while character_iterator_index < len(available_next_characters):
                next_character_to_append = available_next_characters[character_iterator_index]
                # Append the newly formed longer happy string to the queue
                candidate_strings_queue.append(current_base_string + next_character_to_append)
                character_iterator_index += 1
        
        # Once the loop finishes, the queue contains all happy strings of 'desired_length'
        # Check if the 'desired_kth_string' exists within the generated strings
        if len(candidate_strings_queue) >= desired_kth_string:
            # Return the (k-1)-th string (0-indexed)
            return candidate_strings_queue[desired_kth_string - 1]
        else:
            # If fewer than k happy strings of the desired length exist, return an empty string
            return ''