# LeetCode Daily Challenge
# Date: 2026-09-09
# Problem: #3871 Count Commas in Range II
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def countCommas(self, n: int) -> int:
        thousand_threshold = 999
        million_threshold = 999999
        billion_threshold = 999999999
        trillion_threshold = 999999999999
        quadrillion_threshold = 999999999999999

        return (
            max(0, n - thousand_threshold) +
            max(0, n - million_threshold) +
            max(0, n - billion_threshold) +
            max(0, n - trillion_threshold) +
            max(0, n - quadrillion_threshold)
        )