# LeetCode Daily Challenge
# Date: 2026-05-23
# Problem: Check if Array Is Sorted and Rotated
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def check(self, input_sequence: list[int]) -> bool:
        descent_points = 0
        total_elements = len(input_sequence)
        
        if total_elements <= 1:
            return True

        current_position = 1
        while current_position < total_elements:
            if input_sequence[current_position - 1] > input_sequence[current_position]:
                descent_points += 1
            current_position += 1
        
        if descent_points > 1:
            return False
        
        # If there's exactly one descent, verify the wrap-around condition.
        # This means the last element must be less than or equal to the first element.
        # If descent_points is 0, the array is already fully sorted, and this condition
        # (input_sequence[total_elements - 1] > input_sequence[0] and descent_points != 0)
        # will correctly evaluate to false, allowing the function to return True.
        if input_sequence[total_elements - 1] > input_sequence[0] and descent_points != 0:
            return False
            
        return True