# LeetCode Daily Challenge
# Date: 2026-03-05
# Problem: Minimum Changes To Make Alternating Binary String
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def minOperations(self, s: str) -> int:
        string_length = len(s)
        
        # This counter tracks operations needed to transform 's' into '01010...' pattern
        mismatches_for_pattern_zero_start = 0
        
        # This counter tracks operations needed to transform 's' into '10101...' pattern
        mismatches_for_pattern_one_start = 0
        
        current_index = 0
        while current_index < string_length:
            # Determine the character expected at this position for a string starting with '0'
            # e.g., index 0 -> '0', index 1 -> '1', index 2 -> '0', etc.
            expected_char_if_zero_starts = str(current_index & 1) 
            
            # If the character at the current_index in the input string 's'
            # does not match what's expected for the '01010...' pattern,
            # increment the counter for operations towards that pattern.
            mismatches_for_pattern_zero_start += (s[current_index] != expected_char_if_zero_starts)
            
            # If the character at the current_index in the input string 's'
            # matches what's expected for the '01010...' pattern,
            # then it *does not* match what's expected for the '10101...' pattern (which is the opposite).
            # So, increment the counter for operations towards the '10101...' pattern.
            mismatches_for_pattern_one_start += (s[current_index] == expected_char_if_zero_starts)
            
            current_index += 1
            
        # The minimum operations required is the lesser of the two possibilities
        return min(mismatches_for_pattern_zero_start, mismatches_for_pattern_one_start)