# LeetCode Daily Challenge
# Date: 2026-05-28
# Problem: Longest Common Suffix Queries
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class TrieNode:
    def __init__(self):
        self.best_word_idx = float('inf')
        self.next_nodes = [None] * 26

class SuffixTrie:
    def __init__(self, word_list_container):
        self.trie_base_node = TrieNode()
        self.stored_words_list = word_list_container
        
        total_words_to_process = len(self.stored_words_list)
        current_word_position = 0
        while current_word_position < total_words_to_process:
            self.add_suffix_to_trie(self.stored_words_list[current_word_position], current_word_position)
            current_word_position += 1
    
    def check_and_update_index(self, existing_index, potential_index):
        total_words_in_container = len(self.stored_words_list)
        
        if not (0 <= potential_index < total_words_in_container):
            return False
        
        if not (0 <= existing_index < total_words_in_container):
            return True
        
        length_potential = len(self.stored_words_list[potential_index])
        length_existing = len(self.stored_words_list[existing_index])
        
        return length_potential < length_existing
    
    def add_suffix_to_trie(self, input_string_val, current_word_index):
        current_trie_node = self.trie_base_node
        
        str_len = len(input_string_val)
        char_position = str_len - 1
        
        while char_position >= 0:
            current_char_val = input_string_val[char_position]
            char_node_idx = ord(current_char_val) - ord('a')
            
            if current_trie_node.next_nodes[char_node_idx] is None:
                current_trie_node.next_nodes[char_node_idx] = TrieNode()
            
            if self.check_and_update_index(current_trie_node.best_word_idx, current_word_index):
                current_trie_node.best_word_idx = current_word_index
            
            current_trie_node = current_trie_node.next_nodes[char_node_idx]
            char_position -= 1
        
        if self.check_and_update_index(current_trie_node.best_word_idx, current_word_index):
            current_trie_node.best_word_idx = current_word_index
    
    def find_longest_common_suffix_index(self, query_string_val):
        current_node_in_trie = self.trie_base_node
        
        query_len = len(query_string_val)
        reverse_char_pos = query_len - 1
        
        while reverse_char_pos >= 0:
            character_to_match = query_string_val[reverse_char_pos]
            char_map_index = ord(character_to_match) - ord('a')
            
            if current_node_in_trie.next_nodes[char_map_index] is None:
                break
            
            current_node_in_trie = current_node_in_trie.next_nodes[char_map_index]
            reverse_char_pos -= 1
            
        return current_node_in_trie.best_word_idx

class Solution:
    def stringIndices(self, source_word_list, search_queries):
        suffix_trie_instance = SuffixTrie(source_word_list)
        
        result_indices_list = []
        query_iterator = 0
        total_queries = len(search_queries)
        
        while query_iterator < total_queries:
            current_query_string = search_queries[query_iterator]
            found_index = suffix_trie_instance.find_longest_common_suffix_index(current_query_string)
            result_indices_list.append(found_index)
            query_iterator += 1
            
        return result_indices_list