# LeetCode Daily Challenge
# Date: 2026-03-27
# Problem: Matrix Similarity After Cyclic Shifts
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def areSimilar(self, input_matrix: List[List[int]], shift_val: int) -> bool:
        row_index = 0
        total_rows = len(input_matrix)

        while row_index < total_rows:
            current_row_elements = input_matrix[row_index]
            row_length = len(current_row_elements)
            
            element_index = 0
            while element_index < row_length:
                if current_row_elements[element_index] != current_row_elements[(element_index + shift_val) % row_length]:
                    return False
                element_index += 1
            row_index += 1
            
        return True