# LeetCode Daily Challenge
# Date: 2026-03-11
# Problem: Complement of Base 10 Integer
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def bitwiseComplement(self, input_number: int) -> int:
        # Convert the given integer to its binary string representation,
        # removing the initial '0b' prefix.
        binary_representation_str = bin(input_number)[2:]

        # Initialize a new string to build the complement.
        complemented_binary_string = ""

        # Iterate through each character (bit) in the binary string using a while loop.
        current_char_index = 0
        while current_char_index < len(binary_representation_str):
            # Get the current bit character.
            current_bit_char = binary_representation_str[current_char_index]

            # Append the inverted bit to the result string.
            if current_bit_char == '0':
                complemented_binary_string += '1'
            else: # current_bit_char must be '1'
                complemented_binary_string += '0'

            # Move to the next character.
            current_char_index += 1

        # Convert the resulting complemented binary string back to an integer
        # (base 2) and return it.
        return int(complemented_binary_string, 2)