# LeetCode Daily Challenge
# Date: 2026-08-13
# Problem: Longest Substring of One Repeating Character
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import collections
import bisect

class TextSegmentProcessor:
    def __init__(self):
        # A list of tuples (start_index, end_index, character_value)
        # This list is maintained in sorted order based on the start_index of each segment.
        self.interval_segments = []

        # A dictionary (Counter) to track the frequencies of different segment lengths.
        # Keys are segment lengths, values are their counts.
        self.length_frequencies = collections.Counter()

    def _adjust_length_count(self, length_delta: int):
        # This helper function updates the frequency count for a given segment length.
        # If length_delta is positive, it increments the count for abs(length_delta).
        # If length_delta is negative, it decrements the count for abs(length_delta).
        
        count_multiplier = -1 if length_delta < 0 else 1
        actual_length = abs(length_delta)
        
        self.length_frequencies[actual_length] += count_multiplier
        # Remove a length from the dictionary if its count drops to zero or below.
        if self.length_frequencies[actual_length] <= 0:
            del self.length_frequencies[actual_length]

    def _add_segment_to_structure(self, segment_data: tuple):
        # Inserts a new segment into the sorted list of segments and updates length frequencies.
        bisect.insort_left(self.interval_segments, segment_data)
        segment_span = segment_data[1] - segment_data[0] + 1
        self._adjust_length_count(segment_span)

    def _remove_segment_from_structure(self, segment_data: tuple):
        # Removes an existing segment from the sorted list and updates length frequencies.
        # It finds the segment's position using binary search and then removes it.
        segment_position_idx = bisect.bisect_left(self.interval_segments, segment_data)
        
        # Verify the segment at the found index is indeed the one we want to remove.
        # This check is crucial because bisect_left returns an insertion point,
        # which might not exactly match the element if duplicates or non-exact matches exist.
        # In this problem, segment_data tuples are unique.
        if segment_position_idx < len(self.interval_segments) and self.interval_segments[segment_position_idx] == segment_data:
            self.interval_segments.pop(segment_position_idx)
        
        segment_span = segment_data[1] - segment_data[0] + 1
        self._adjust_length_count(-segment_span)

    def _split_segment_at_point(self, split_index: int, segment_to_divide: tuple, new_char_value: str) -> int:
        # This function splits an existing segment into up to three new segments:
        # a left part, a single-character middle part, and a right part.
        # It returns the index of the newly inserted single-character segment.

        self._remove_segment_from_structure(segment_to_divide)
        
        start_boundary, end_boundary, original_char_value = segment_to_divide
        
        # Add the left part if it exists
        if start_boundary < split_index:
            self._add_segment_to_structure((start_boundary, split_index - 1, original_char_value))
        # Add the right part if it exists
        if end_boundary > split_index:
            self._add_segment_to_structure((split_index + 1, end_boundary, original_char_value))
        
        # Add the new single-character segment at the split_index.
        # Its length count is automatically handled by _add_segment_to_structure.
        new_single_char_segment = (split_index, split_index, new_char_value)
        self._add_segment_to_structure(new_single_char_segment)

        # Return the index of the newly inserted segment.
        return bisect.bisect_left(self.interval_segments, new_single_char_segment)

    def _merge_contiguous_segments(self, segment_list_index: int):
        # Merges a segment with its adjacent neighbors if they share the same character.
        # This function carefully handles index shifts due to removals.

        segment_under_consideration = self.interval_segments[segment_list_index]
        
        # Retrieve neighbors before any removals to ensure correct references.
        left_adjacent_segment = self.interval_segments[segment_list_index - 1]
        right_adjacent_segment = self.interval_segments[segment_list_index + 1]
        
        segments_to_be_removed = [segment_under_consideration]
        
        final_start_position = segment_under_consideration[0]
        final_end_position = segment_under_consideration[1]
        segment_character = segment_under_consideration[2]
        
        # Check and prepare to merge with the left neighbor
        if left_adjacent_segment[2] == segment_character:
            segments_to_be_removed.append(left_adjacent_segment)
            final_start_position = left_adjacent_segment[0]
            
        # Check and prepare to merge with the right neighbor
        if right_adjacent_segment[2] == segment_character:
            segments_to_be_removed.append(right_adjacent_segment)
            final_end_position = right_adjacent_segment[1]
            
        # Remove all identified segments from the structure.
        # Iterating through a copy of the list of segments to remove is safer.
        for segment_to_erase in segments_to_be_removed:
            self._remove_segment_from_structure(segment_to_erase)
            
        # Add the newly merged segment.
        self._add_segment_to_structure((final_start_position, final_end_position, segment_character))

    def process_update_query(self, query_target_position: int, new_char_for_position: str):
        # Handles a single update query: changing a character at a specific position.

        # Find the segment that contains the query_target_position.
        # A dummy tuple is used with bisect_left to find the first segment that starts at or after query_target_position.
        dummy_for_search = (query_target_position, -1, '') 
        found_segment_index = bisect.bisect_left(self.interval_segments, dummy_for_search)
        
        current_containing_segment = self.interval_segments[found_segment_index]
        # If the found segment starts after the target position, the actual containing segment is the one before it.
        if current_containing_segment[0] > query_target_position:
            current_containing_segment = self.interval_segments[found_segment_index - 1]
        
        # If the character is already the same as the new character, no operation is needed.
        if new_char_for_position == current_containing_segment[2]:
            return
        
        # Split the current segment at the query_target_position and get the index of the new middle segment.
        newly_created_segment_idx = self._split_segment_at_point(query_target_position, current_containing_segment, new_char_for_position)
        
        # Merge the newly created segment with its neighbors if characters match.
        self._merge_contiguous_segments(newly_created_segment_idx)

    def get_longest_repeating_substrings(self, initial_string_content: str, query_characters: str, query_indices_list: list) -> list:
        string_total_length = len(initial_string_content)
        total_queries = len(query_characters)
        
        # Prepend and append dummy characters to simplify boundary conditions for segment processing.
        # This makes internal indexing 1-based relative to the original string.
        adjusted_string_with_dummies = '?' + initial_string_content + '?'
        
        # Add dummy segments at the very beginning and end to handle edge cases for merging.
        # Using '\0' as a character unlikely to appear in actual input.
        self._add_segment_to_structure((0, 0, '\0'))
        self._add_segment_to_structure((string_total_length + 1, string_total_length + 1, '\0'))
        
        current_segment_start_position = 1
        previous_character_in_scan = adjusted_string_with_dummies[1]
        
        # Initialize the segments based on the initial string content.
        scan_index = 2
        while scan_index <= string_total_length + 1:
            if adjusted_string_with_dummies[scan_index] == previous_character_in_scan:
                # If character is the same, continue extending the current segment.
                pass 
            else:
                # Character changed, finalize the previous segment and start a new one.
                self._add_segment_to_structure((current_segment_start_position, scan_index - 1, previous_character_in_scan))
                previous_character_in_scan = adjusted_string_with_dummies[scan_index]
                current_segment_start_position = scan_index
            scan_index += 1
        
        list_of_results = []
        query_iteration_counter = 0
        while query_iteration_counter < total_queries:
            # Adjust query index to be 1-based, matching internal string representation.
            self.process_update_query(query_indices_list[query_iteration_counter] + 1, query_characters[query_iteration_counter])
            
            # After each update, find the maximum segment length currently present.
            # `max(dict.keys())` finds the largest key (length) in the frequency map.
            if self.length_frequencies:
                list_of_results.append(max(self.length_frequencies.keys()))
            else:
                # Should not be reached if dummy segments always exist and have length 1.
                list_of_results.append(0) 
            
            query_iteration_counter += 1
            
        return list_of_results