# LeetCode Daily Challenge
# Date: 2026-03-06
# Problem: Check if Binary String Has at Most One Segment of Ones
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def checkOnesSegment(self, binary_sequence: str) -> bool:
        sequence_length = len(binary_sequence)
        
        if sequence_length < 2:
            return True
        
        current_index = 0
        while current_index < sequence_length - 1:
            if binary_sequence[current_index] == '0' and binary_sequence[current_index + 1] == '1':
                return False
            current_index += 1
            
        return True

class Solution:
    def checkOnesSegment(self, input_string_val: str) -> bool:
        processed_string_data = input_string_val.strip("0")
        first_zero_position = processed_string_data.find('0')
        return first_zero_position == -1