# LeetCode Daily Challenge
# Date: 2026-03-10
# Problem: Find All Possible Stable Binary Arrays II
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def numberOfStableArrays(self, zero: int, one: int, limit: int) -> int:
        divisor_val = 10**9 + 7

        count_zeros_req = zero
        count_ones_req = one
        max_consecutive_len = limit

        memo_table = [[[0, 0] for _zeros_idx in range(count_zeros_req + 1)] for _ones_idx in range(count_ones_req + 1)]

        current_zero_count = 0
        while current_zero_count <= min(count_zeros_req, max_consecutive_len):
            memo_table[0][current_zero_count][0] = 1
            current_zero_count += 1

        current_one_count = 0
        while current_one_count <= min(count_ones_req, max_consecutive_len):
            memo_table[current_one_count][0][1] = 1
            current_one_count += 1

        memo_table[0][0] = [0, 0]

        current_row_ones = 1
        while current_row_ones <= count_ones_req:
            current_col_zeros = 1
            while current_col_zeros <= count_zeros_req:
                
                sum_ending_zero = memo_table[current_row_ones][current_col_zeros - 1][1] + memo_table[current_row_ones][current_col_zeros - 1][0]
                if current_col_zeros >= max_consecutive_len + 1:
                    sum_ending_zero -= memo_table[current_row_ones][current_col_zeros - max_consecutive_len - 1][1]
                memo_table[current_row_ones][current_col_zeros][0] = sum_ending_zero % divisor_val

                sum_ending_one = memo_table[current_row_ones - 1][current_col_zeros][0] + memo_table[current_row_ones - 1][current_col_zeros][1]
                if current_row_ones >= max_consecutive_len + 1:
                    sum_ending_one -= memo_table[current_row_ones - max_consecutive_len - 1][current_col_zeros][0]
                memo_table[current_row_ones][current_col_zeros][1] = sum_ending_one % divisor_val

                current_col_zeros += 1
            current_row_ones += 1

        total_stable_arrays = sum(memo_table[count_ones_req][count_zeros_req]) % divisor_val
        return total_stable_arrays