# LeetCode Daily Challenge
# Date: 2026-08-10
# Problem: Stone Game IV
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import math
import functools

class Solution:
    def winnerSquareGame(self, total_piles):

        @functools.lru_cache(None)
        def determine_winner(current_pile_size):
            if current_pile_size == 0:
                return False

            limit_val = int(math.sqrt(current_pile_size))
            for iter_val in range(1, limit_val + 1):
                square_removed = iter_val * iter_val
                if not determine_winner(current_pile_size - square_removed):
                    return True

            return False

        return determine_winner(total_piles)