# LeetCode Daily Challenge
# Date: 2026-04-06
# Problem: Walking Robot Simulation
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def robotSim(self, command_sequence, terrain_obstacles):
        robot_x_coord = 0
        robot_y_coord = 0
        current_orientation_index = 0  # 0: North (+Y), 1: East (+X), 2: South (-Y), 3: West (-X)

        orientation_vectors = [(0, 1), (1, 0), (0, -1), (-1, 0)]

        max_squared_distance_achieved = 0

        blocked_grid_cells = set(map(tuple, terrain_obstacles))

        command_pointer = 0
        total_commands_in_sequence = len(command_sequence)

        while command_pointer < total_commands_in_sequence:
            current_instruction = command_sequence[command_pointer]

            if current_instruction == -1:  # Turn right (clockwise)
                current_orientation_index = (current_orientation_index + 1) % 4
            elif current_instruction == -2:  # Turn left (counter-clockwise)
                current_orientation_index = (current_orientation_index - 1) % 4 
            else:  # Move forward 'current_instruction' steps
                steps_to_attempt = current_instruction
                step_counter = 0

                while step_counter < steps_to_attempt:
                    delta_x, delta_y = orientation_vectors[current_orientation_index]
                    potential_next_x = robot_x_coord + delta_x
                    potential_next_y = robot_y_coord + delta_y

                    if (potential_next_x, potential_next_y) in blocked_grid_cells:
                        break  # Stop movement if an obstacle is encountered

                    robot_x_coord = potential_next_x
                    robot_y_coord = potential_next_y

                    current_squared_distance = robot_x_coord * robot_x_coord + robot_y_coord * robot_y_coord
                    max_squared_distance_achieved = max(max_squared_distance_achieved, current_squared_distance)

                    step_counter += 1

            command_pointer += 1

        return max_squared_distance_achieved