# LeetCode Daily Challenge
# Date: 2026-08-20
# Problem: Distribute Elements Into Two Arrays I
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

from typing import List

class Solution:
    def resultArray(self, source_elements: List[int]) -> List[int]:
        total_elements_count = len(source_elements)
        
        # Initialize the two dynamic arrays with the first two elements
        # (Assuming the input 'source_elements' will always contain at least two items)
        first_dynamic_array = [source_elements[0]]
        second_dynamic_array = [source_elements[1]]
        
        current_processing_index = 2
        while current_processing_index < total_elements_count:
            # Compare the last added elements of the two dynamic arrays
            if first_dynamic_array[-1] > second_dynamic_array[-1]:
                first_dynamic_array.append(source_elements[current_processing_index])
            else:
                second_dynamic_array.append(source_elements[current_processing_index])
            current_processing_index += 1
        
        # Concatenate the two dynamic arrays into a single final result array
        final_result_array = []
        for item_from_first in first_dynamic_array:
            final_result_array.append(item_from_first)
        
        for item_from_second in second_dynamic_array:
            final_result_array.append(item_from_second)
            
        return final_result_array