# LeetCode Daily Challenge
# Date: 2026-05-03
# Problem: Rotate String
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def rotateString(self, base_text: str, desired_text: str) -> bool:
        initial_length = len(base_text)
        extended_text = base_text + base_text
        return initial_length == len(desired_text) and desired_text in extended_text