# LeetCode Daily Challenge
# Date: 2026-08-24
# Problem: Stone Game VIII
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from typing import List

class Solution:
    def stoneGameVIII(self, initial_stone_weights: List[int]) -> int:
        num_stones = len(initial_stone_weights)

        # Handle the edge case where there are no stones.
        # Problem constraints typically guarantee at least one stone,
        # but a robust solution should consider this.
        if num_stones == 0:
            return 0

        # Phase 1: Transform the input array into an array of prefix sums (cumulative sums).
        # After this loop, `initial_stone_weights[k]` will contain the sum of all stones
        # from the beginning of the list up to index `k`.
        current_position = 1
        while current_position < num_stones:
            initial_stone_weights[current_position] += initial_stone_weights[current_position - 1]
            current_position += 1

        # Phase 2: Initialize the dynamic programming state.
        # The base case for the DP calculation corresponds to `dp[N-2] = prefix[N-1]`.
        # In our modified array, `prefix[N-1]` is simply the last element.
        # If `num_stones` is 1, `num_stones - 1` is 0, correctly pointing to the single stone's value.
        calculated_optimal_score = initial_stone_weights[num_stones - 1]

        # Phase 3: Iterate backwards to compute the optimal score using the DP recurrence relation.
        # The loop effectively runs for `i` from `N-2` down to `1`.
        # The recurrence is `dp[i-1] = max(dp[i], prefix[i] - dp[i])`.
        # `calculated_optimal_score` holds the `dp[i]` value from the previous step.
        # `initial_stone_weights[processing_index]` holds `prefix[i]`.
        # The loop condition `processing_index > 0` ensures we process prefix sums down to `prefix[1]`.
        # For `num_stones = 1`, `num_stones - 2` is -1, so the loop `while -1 > 0` does not execute, which is correct.
        # For `num_stones = 2`, `num_stones - 2` is 0, so the loop `while 0 > 0` does not execute.
        # In this case, `calculated_optimal_score` remains `prefix[1]`, which is the correct result for N=2.
        processing_index = num_stones - 2
        while processing_index > 0:
            calculated_optimal_score = max(calculated_optimal_score, initial_stone_weights[processing_index] - calculated_optimal_score)
            processing_index -= 1

        return calculated_optimal_score