# LeetCode Daily Challenge
# Date: 2026-10-02
# Problem: #22 Generate Parentheses
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def generateParenthesis(self, n: int) -> list[str]:
        if not n:
            return []
        
        combinations = []
        self._backtrack(n, n, combinations, "")
        return combinations

    def _backtrack(self, open_count: int, close_count: int, result: list[str], current_string: str) -> None:
        if close_count < open_count:
            return
        if not open_count and not close_count:
            result.append(current_string)
            return
        
        if open_count:
            self._backtrack(open_count - 1, close_count, result, current_string + "(")
        if close_count:
            self._backtrack(open_count, close_count - 1, result, current_string + ")")