# LeetCode Daily Challenge
# Date: 2026-10-05
# Problem: #856 Score of Parentheses
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def scoreOfParentheses(self, S: str) -> int:
        return self.helper(S, 0, len(S) - 1)

    def helper(self, sequence: str, left_index: int, right_index: int) -> int:
        if right_index - left_index == 1:
            return 1
        
        balance_count = 0
        for current_index in range(left_index, right_index):
            if sequence[current_index] == '(':
                balance_count += 1
            elif sequence[current_index] == ')':
                balance_count -= 1
                
            if balance_count == 0:
                return self.helper(sequence, left_index, current_index) + self.helper(sequence, current_index + 1, right_index)
                
        return 2 * self.helper(sequence, left_index + 1, right_index - 1)