# LeetCode Daily Challenge
# Date: 2026-04-26
# Problem: Detect Cycles in 2D Grid
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def containsCycle(self, grid: List[List[str]]) -> bool:
        def check_for_path_cycle(current_coords, parent_coords):
            # If the current coordinate is already in our globally visited set,
            # it means we've encountered a cycle, because the parent is explicitly
            # excluded from neighbor consideration.
            if current_coords in visited_cells_global:
                return True

            visited_cells_global.add(current_coords)
            curr_r, curr_c = current_coords

            # Define movement vectors for adjacent cells (right, left, down, up)
            direction_vectors = [(0, 1), (0, -1), (1, 0), (-1, 0)]

            eligible_neighbors = []
            for dr, dc in direction_vectors:
                next_r, next_c = curr_r + dr, curr_c + dc
                neighbor_position = (next_r, next_c)

                # Check if the neighbor is within grid boundaries
                is_row_valid = 0 <= next_r < num_rows
                is_col_valid = 0 <= next_c < num_cols

                if is_row_valid and is_col_valid:
                    # Check if the neighbor has the same character as the current cell
                    character_matches = grid[next_r][next_c] == grid[curr_r][curr_c]
                    # Ensure the neighbor is not the immediate parent cell
                    not_the_parent = neighbor_position != parent_coords

                    if character_matches and not_the_parent:
                        eligible_neighbors.append(neighbor_position)

            neighbor_index = 0
            while neighbor_index < len(eligible_neighbors):
                neighbor_cell = eligible_neighbors[neighbor_index]
                if check_for_path_cycle(neighbor_cell, current_coords):
                    return True
                neighbor_index += 1

            return False

        num_rows, num_cols = len(grid), len(grid[0])
        visited_cells_global = set()

        row_idx = 0
        while row_idx < num_rows:
            col_idx = 0
            while col_idx < num_cols:
                current_start_position = (row_idx, col_idx)
                # Only start a new DFS if the cell hasn't been visited yet
                if current_start_position not in visited_cells_global:
                    # For the initial call, there is no parent, so we pass None
                    if check_for_path_cycle(current_start_position, None):
                        return True
                col_idx += 1
            row_idx += 1

        # If no cycle was found after checking all components
        return False