# LeetCode Daily Challenge
# Date: 2026-05-29
# Problem: Minimum Element After Replacement With Digit Sum
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from typing import List

class Solution:
    def findMinSumOfDigits(self, input_numbers: List[int]) -> int:

        def calculate_number_digit_sum(current_number_value: int) -> int:
            resultant_sum = 0
            processing_number = current_number_value

            if processing_number == 0:
                return 0

            # The original code's lambda `sum(int(x) for x in str(num))` would
            # raise a ValueError for negative numbers (e.g., `str(-12)` produces `'-12'`,
            # and `int('-')` is invalid).
            # Thus, we assume positive integers or that the problem context
            # implies we should handle the absolute value for digit summing.
            # For strict equivalence, we'll maintain behavior for positive inputs.
            # If negative inputs were expected to be handled (e.g., sum of digits of abs value),
            # `processing_number = abs(processing_number)` would be added here.

            while processing_number > 0:
                digit_extracted = processing_number % 10
                resultant_sum += digit_extracted
                processing_number //= 10
            
            return resultant_sum

        # Use a generator expression to apply the digit sum calculation
        # to each element and then find the minimum.
        # This approach is equivalent to `min(map(calculate_number_digit_sum, input_numbers))`
        # in terms of functionality and complexity.
        return min(calculate_number_digit_sum(val) for val in input_numbers)