# LeetCode Daily Challenge
# Date: 2026-05-20
# Problem: Find the Prefix Common Array of Two Arrays
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def findThePrefixCommonArray(self, arr_a: List[int], arr_b: List[int]) -> List[int]:
        array_length = len(arr_a)

        # Store the first occurrence index for each value in arr_a
        val_to_first_idx_a = dict()
        # Store the first occurrence index for each value in arr_b
        val_to_first_idx_b = dict()

        # Populate the index maps
        idx_populate = 0
        while idx_populate < array_length:
            val_to_first_idx_a[arr_a[idx_populate]] = idx_populate
            val_to_first_idx_b[arr_b[idx_populate]] = idx_populate
            idx_populate = idx_populate + 1

        # Initialize the result array with zeros
        result_common_counts = [0 for _ in range(array_length)]

        # Iterate through each prefix length
        current_prefix_end = 0
        while current_prefix_end < array_length:
            # Count elements common to both prefixes up to current_prefix_end
            current_prefix_match_count = 0

            # Iterate through elements within the current prefix
            element_in_prefix_idx = 0
            while element_in_prefix_idx <= current_prefix_end:
                # Get the value of the current element in arr_a
                current_value = arr_a[element_in_prefix_idx]

                # Check if this value appeared in arr_a's prefix and arr_b's prefix
                if val_to_first_idx_a[current_value] <= current_prefix_end and \
                   val_to_first_idx_b[current_value] <= current_prefix_end:
                    current_prefix_match_count = current_prefix_match_count + 1

                element_in_prefix_idx += 1

            # Store the count for the current prefix length
            result_common_counts[current_prefix_end] = current_prefix_match_count
            current_prefix_end += 1

        return result_common_counts