# LeetCode Daily Challenge
# Date: 2026-06-21
# Problem: Maximum Ice Cream Bars
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from typing import List
from itertools import accumulate
from bisect import bisect_right

class Solution:
    def maxIceCream(self, item_prices: List[int], available_funds: int) -> int:
        # Sort the prices of ice cream items in ascending order.
        # This greedy strategy ensures we maximize the number of items by buying the cheapest first.
        ordered_item_prices = sorted(item_prices)

        # Calculate the running sum of the sorted prices.
        # Each element in this sequence represents the total cost to buy 1, 2, 3, ...
        # (up to the current index) of the cheapest ice creams.
        cumulative_cost_generator = accumulate(ordered_item_prices)
        
        # Convert the generator to a list to allow for efficient binary search.
        total_expenditure_sequence = list(cumulative_cost_generator)

        # Use bisect_right to find the insertion point for 'available_funds'
        # in the 'total_expenditure_sequence'.
        # This function returns an index 'k' such that all elements total_expenditure_sequence[0...k-1]
        # are less than or equal to 'available_funds'.
        # This index 'k' directly corresponds to the maximum number of ice creams
        # that can be purchased without exceeding the budget.
        maximum_purchasable_items = bisect_right(total_expenditure_sequence, available_funds)
        
        return maximum_purchasable_items