# LeetCode Daily Challenge
# Date: 2026-08-11
# Problem: Smallest Missing Integer Greater Than Sequential Prefix Sum
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def missingInteger(self, nums: List[int]) -> int:
        
        number_list = nums
        
        # Initialize the sum of the sequential prefix
        sequential_prefix_sum = number_list[0]

        # Iterate through the array to find the sequential prefix sum
        current_index = 0
        while current_index < len(number_list) - 1:
            previous_element = number_list[current_index]
            current_element = number_list[current_index + 1]

            # Check if the current element continues the sequential series
            if current_element - previous_element == 1:
                sequential_prefix_sum = sequential_prefix_sum + current_element
                current_index = current_index + 1
            else:
                # Break the loop if the sequence is not consecutive
                break
        
        # Find the smallest integer greater than sequential_prefix_sum
        # that is not present in the input array.
        # The 'in' operator for a list has O(N) average time complexity.
        while sequential_prefix_sum in number_list:
            sequential_prefix_sum = sequential_prefix_sum + 1

        return sequential_prefix_sum