# LeetCode Daily Challenge
# Date: 2026-04-14
# Problem: Minimum Total Distance Traveled
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

from collections import deque

class Solution:
    def minimumTotalDistance(self, robot_positions: List[int], factory_data_list: List[List[int]]) -> int:
        robot_positions.sort()
        factory_data_list.sort()

        num_robots, num_factories = len(robot_positions), len(factory_data_list)
        
        # Initialize DP table: min_dist_matrix[r_idx][f_idx] is min cost for robots[r_idx:] with factories[f_idx:]
        min_dist_matrix = [[0] * (num_factories + 1) for _ in range(num_robots + 1)]

        # Base case: If no factories are available (last column), distance is infinite for any remaining robots
        # The last row (min_dist_matrix[num_robots][:]) is already 0, meaning 0 cost for 0 robots.
        robot_idx_for_base = 0
        while robot_idx_for_base < num_robots:
            min_dist_matrix[robot_idx_for_base][num_factories] = float('inf')
            robot_idx_for_base += 1
        
        # Iterate through factories from right to left
        current_factory_idx = num_factories - 1
        while current_factory_idx >= 0:
            current_cumulative_cost = 0
            
            # Monotonic queue to optimize transitions for this factory
            # Stores (robot_index, dp_value_minus_prefix_cost)
            optimal_queue = deque([(num_robots, 0)]) # Initial state: no robots left, cost 0
            
            # Iterate through robots from right to left
            current_robot_idx = num_robots - 1
            while current_robot_idx >= 0:
                # Add cost for the current robot to be serviced by the current factory
                current_cumulative_cost += abs(robot_positions[current_robot_idx] - factory_data_list[current_factory_idx][0])
                
                # Remove elements from the front of the queue that are out of capacity range
                # A factory at current_factory_idx can service robots from `current_robot_idx` up to 
                # `current_robot_idx + factory_data_list[current_factory_idx][1] - 1`.
                # If the robot index stored in the queue's front is beyond this limit, it's invalid.
                while optimal_queue and optimal_queue[0][0] > current_robot_idx + factory_data_list[current_factory_idx][1]:
                    optimal_queue.popleft()
                
                # Maintain monotonic property: remove larger or equal values from the back
                # We are looking for min(dp[i][j+1] - current_cumulative_cost)
                while optimal_queue and optimal_queue[-1][1] >= min_dist_matrix[current_robot_idx][current_factory_idx + 1] - current_cumulative_cost:
                    optimal_queue.pop()
                    
                # Add current state to the queue
                optimal_queue.append((current_robot_idx, min_dist_matrix[current_robot_idx][current_factory_idx + 1] - current_cumulative_cost))
                
                # The minimum distance for min_dist_matrix[current_robot_idx][current_factory_idx]
                # is the best value from the queue's front + the current cumulative cost
                min_dist_matrix[current_robot_idx][current_factory_idx] = optimal_queue[0][1] + current_cumulative_cost
                
                current_robot_idx -= 1
            current_factory_idx -= 1
            
        # The result is the minimum total distance for all robots starting from the first factory
        return min_dist_matrix[0][0]