# LeetCode Daily Challenge
# Date: 2026-04-19
# Problem: Maximum Distance Between a Pair of Values
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def maxDistance(self, array_a_vals: List[int], array_b_vals: List[int]) -> int:
        pointer_alpha = 0
        pointer_beta = 0
        greatest_separation = 0

        length_alpha = len(array_a_vals)
        length_beta = len(array_b_vals)

        while pointer_alpha < length_alpha and pointer_beta < length_beta:
            if array_a_vals[pointer_alpha] > array_b_vals[pointer_beta]:
                pointer_alpha = pointer_alpha + 1
            else:
                greatest_separation = max(greatest_separation, pointer_beta - pointer_alpha)
                pointer_beta = pointer_beta + 1
        return greatest_separation