# LeetCode Daily Challenge
# Date: 2026-04-15
# Problem: Shortest Distance to Target String in a Circular Array
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def closetTarget(self, word_list: list[str], search_item: str, start_position: int) -> int:
        total_words = len(word_list)
        minimum_distance_found = float('inf')

        current_idx = 0
        while current_idx < total_words:
            if word_list[current_idx] == search_item:
                # Calculate the direct distance (e.g., clockwise)
                direct_path_length = abs(start_position - current_idx)
                
                # Calculate the distance in the opposite direction (e.g., counter-clockwise)
                # For a circular array, if direct_path_length is the distance in one direction,
                # then total_words - direct_path_length is the distance in the other direction.
                reverse_path_length = total_words - direct_path_length
                
                # The actual shortest path to this specific target occurrence is the minimum of these two
                shortest_path_to_current_target = min(direct_path_length, reverse_path_length)
                
                # Update the overall minimum distance found across all target occurrences
                minimum_distance_found = min(minimum_distance_found, shortest_path_to_current_target)
            
            current_idx += 1 # Advance to the next word in the list

        # If the target was never found, minimum_distance_found will still be infinity.
        # In that case, return -1 as per problem specification.
        if minimum_distance_found == float('inf'):
            return -1
        else:
            # Otherwise, return the smallest distance found.
            return int(minimum_distance_found)