# LeetCode Daily Challenge
# Date: 2026-06-01
# Problem: Minimum Cost of Buying Candies With Discount
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:\n    def minimumCost(self, cost: List[int]) -> int:\n        cost.sort(reverse=True)\n        res, i, N = 0, 0, len(cost)\n        while i < N:\n            res += sum(cost[i : i + 2])\n            i += 3\n        return res\n```