# LeetCode Daily Challenge
# Date: 2026-06-28
# Problem: Maximum Element After Decreasing and Rearranging
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def maximumElementAfterDecrementingAndRearranging(self, data_sequence):
        data_sequence.sort()

        data_sequence[0] = 1

        sequence_length = len(data_sequence)
        current_position = 1

        while current_position < sequence_length:
            if data_sequence[current_position] > data_sequence[current_position - 1] + 1:
                data_sequence[current_position] = data_sequence[current_position - 1] + 1
            
            current_position += 1

        return data_sequence[-1]