# LeetCode Daily Challenge
# Date: 2026-06-22
# Problem: Maximum Number of Balloons
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def maxNumberOfBalloons(self, text: str) -> int:
        # Initialize a dictionary to store the frequency of each required letter
        # The letters are 'b', 'a', 'l', 'o', 'n' from the word "balloon"
        letter_frequencies = {"b": 0, "a": 0, "l": 0, "o": 0, "n": 0}
        
        # Use an index and a while loop to iterate through the input string
        current_position = 0
        while current_position < len(text):
            character_at_pos = text[current_position]
            # If the current character is one of the letters needed for "balloon", increment its count
            if character_at_pos in letter_frequencies:
                letter_frequencies[character_at_pos] += 1
            current_position += 1
            
        # The word "balloon" requires two 'l's and two 'o's.
        # Therefore, we divide the counts of 'l' and 'o' by two to reflect how many full "balloon" words can be made.
        letter_frequencies["l"] = letter_frequencies["l"] // 2
        letter_frequencies["o"] = letter_frequencies["o"] // 2
        
        # To find the maximum number of "balloon" words, we need to find the minimum count
        # among all the required letter frequencies. This is because the word count is
        # limited by the letter that is least available.
        minimum_balloons_possible = float('inf') # Start with a very large number
        for count_val in letter_frequencies.values():
            if count_val < minimum_balloons_possible:
                minimum_balloons_possible = count_val
        
        return int(minimum_balloons_possible)