# LeetCode Daily Challenge
# Date: 2026-09-24
# Problem: #3550 Smallest Index With Digit Sum Equal to Index
# Language: python
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def smallestIndex(self, nums: List[int]) -> int:
        for idx, val in enumerate(nums):
            digit_sum = 0
            current_val = val
            while current_val and digit_sum <= idx:
                digit_sum += current_val % 10
                current_val //= 10
            if digit_sum == idx:
                return idx
        return -1