# LeetCode Daily Challenge
# Date: 2026-05-18
# Problem: Jump Game IV
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from collections import deque

class Solution:
    def minJumps(self, input_array: list[int]) -> int:
        array_size = len(input_array)
        
        if array_size == 1:
            return 0
        
        value_to_indices_map = {}
        
        # Populate the map: stores value -> list of all indices where that value appears
        current_index_fill = 0
        while current_index_fill < array_size:
            current_value_at_index = input_array[current_index_fill]
            if current_value_at_index not in value_to_indices_map:
                value_to_indices_map[current_value_at_index] = []
            value_to_indices_map[current_value_at_index].append(current_index_fill)
            current_index_fill += 1
            
        bfs_exploration_queue = deque()
        bfs_exploration_queue.append(0)  # Begin BFS from the starting position (index 0)
        
        total_jumps_taken = 0
        
        while bfs_exploration_queue:
            total_jumps_taken += 1
            nodes_to_process_in_this_level = len(bfs_exploration_queue)
            
            level_node_counter = 0
            while level_node_counter < nodes_to_process_in_this_level:
                current_node_position = bfs_exploration_queue.popleft()
                
                # Possible move 1: Jump to the immediate left neighbor
                leftward_position = current_node_position - 1
                if leftward_position >= 0 and input_array[leftward_position] in value_to_indices_map:
                    bfs_exploration_queue.append(leftward_position)

                # Possible move 2: Jump to the immediate right neighbor
                rightward_position = current_node_position + 1
                if rightward_position < array_size:
                    if rightward_position == array_size - 1:
                        return total_jumps_taken  # Target reached (last index)
                    # Only add if the value is not yet processed (still exists in map)
                    if input_array[rightward_position] in value_to_indices_map:
                        bfs_exploration_queue.append(rightward_position)

                # Possible move 3: Jump to any other index that holds the same value
                value_at_current_node = input_array[current_node_position]
                if value_at_current_node in value_to_indices_map:
                    # Iterate over a copy of the list, as the dictionary might be modified
                    for target_index_from_value_match in list(value_to_indices_map[value_at_current_node]):
                        if target_index_from_value_match != current_node_position: # Avoid jumping to oneself
                            if target_index_from_value_match == array_size - 1:
                                return total_jumps_taken # Target reached
                            bfs_exploration_queue.append(target_index_from_value_match)
                    
                    # Mark this value as completely processed to prevent revisiting
                    # This is critical for maintaining O(N) time complexity
                    del value_to_indices_map[value_at_current_node]
                
                level_node_counter += 1
        
        return total_jumps_taken # This line should theoretically not be reached for valid inputs where a path always exists