# LeetCode Daily Challenge
# Date: 2026-06-20
# Problem: Maximum Building Height
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def maxBuilding(self, total_cities: int, building_rules: List[List[int]]) -> int:
        # Incorporate virtual building constraints for the leftmost and rightmost positions.
        # A building at city 1 cannot exceed height 0.
        # A building at city 'total_cities' cannot exceed height 'total_cities - 1'.
        building_rules.append([1, 0])
        building_rules.append([total_cities, total_cities - 1])

        # Sort all building constraints based on their city position.
        building_rules.sort()

        # Determine the total count of constraints after adding the virtual ones.
        num_constraints = len(building_rules)

        # First pass: Iterate from left to right to enforce height limits.
        # A building's height is constrained by its own rule and the previous building's height plus the distance.
        current_rule_idx = 1
        while current_rule_idx < num_constraints:
            current_building_data = building_rules[current_rule_idx]
            previous_building_data = building_rules[current_rule_idx - 1]

            # Calculate the maximum permissible height at the current position
            # based on the previous building's height and the distance.
            max_height_from_left = previous_building_data[1] + (current_building_data[0] - previous_building_data[0])
            
            # Update the current building's height limit to be the minimum of its original limit
            # and the limit imposed by the previous building.
            building_rules[current_rule_idx][1] = min(current_building_data[1], max_height_from_left)
            current_rule_idx += 1

        # Second pass: Iterate from right to left to further refine height limits.
        # A building's height is also constrained by its own rule and the next building's height plus the distance.
        current_rule_idx = num_constraints - 2
        while current_rule_idx >= 0:
            current_building_data = building_rules[current_rule_idx]
            next_building_data = building_rules[current_rule_idx + 1]

            # Calculate the maximum permissible height at the current position
            # based on the next building's height and the distance.
            max_height_from_right = next_building_data[1] + (next_building_data[0] - current_building_data[0])
            
            # Update the current building's height limit to be the minimum of its current refined limit
            # and the limit imposed by the next building.
            building_rules[current_rule_idx][1] = min(current_building_data[1], max_height_from_right)
            current_rule_idx -= 1

        # Calculate the overall maximum possible building height that can be constructed.
        # This involves finding the peak height in each segment between two adjacent constrained buildings.
        overall_peak_height = 0
        current_rule_idx = 1
        while current_rule_idx < num_constraints:
            left_segment_data = building_rules[current_rule_idx - 1]
            right_segment_data = building_rules[current_rule_idx]

            left_city_position = left_segment_data[0]
            left_max_height = left_segment_data[1]

            right_city_position = right_segment_data[0]
            right_max_height = right_segment_data[1]

            # Horizontal distance between the two cities.
            distance_between_cities = right_city_position - left_city_position
            # Absolute difference in their maximum allowed heights.
            height_difference_abs = abs(left_max_height - right_max_height)

            # The maximum height in the segment is found by taking the taller of the two building limits
            # and adding the additional height that can be built in the triangular space between them.
            # This additional height is (distance - absolute_height_difference) // 2.
            segment_highest_point = max(left_max_height, right_max_height) + (distance_between_cities - height_difference_abs) // 2
            
            # Update the overall maximum peak height found so far.
            overall_peak_height = max(overall_peak_height, segment_highest_point)
            current_rule_idx += 1

        return overall_peak_height