# LeetCode Daily Challenge
# Date: 2026-09-01
# Problem: #3568 Minimum Moves to Clean the Classroom
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

from typing import List
from collections import deque

class Solution:
    def minMoves(self, classroom: List[str], energy: int) -> int:
        m = len(classroom)
        n = len(classroom[0])
        
        # Find 'S' and all 'L's
        start = None
        litters = []
        for r in range(m):
            for c in range(n):
                if classroom[r][c] == 'S':
                    start = (r, c)
                elif classroom[r][c] == 'L':
                    litters.append((r, c))
                    
        k = len(litters)
        if k == 0:
            return 0
            
        # We need to find shortest paths between:
        # - start and each litter
        # - each reset area ('R' and 'S') and each litter
        # - start and each reset area
        # - each litter and each other litter
        # Wait, actually, any cell (start, R, or L) can be a source.
        # Let's identify all important nodes:
        # Node 0: 'S' (start)
        # Nodes 1 to k: the k 'L's
        # Other nodes: 'R' cells.
        
        # Let's collect all 'R' cells.
        resets = []
        for r in range(m):
            for c in range(n):
                if classroom[r][c] == 'R':
                    resets.append((r, c))
                    
        # To compute shortest paths efficiently, we can run BFS from each 'R', 'S', and 'L'.
        # However, since $m, n \le 20$, $m \times n \le 400$.
        # The number of litter items is at most 10.
        # So important locations are:
        # S: 1
        # L: up to 10
        # R: up to 400 (though many might be unreachable or redundant, but standard BFS from each 'R', 'S', and 'L' is at most $1 + 10 + 400$ BFSs, which is too many if $|R|$ is large).
        # Wait, do we need BFS from EVERY 'R'?
        # Actually, when energy runs out, we MUST be at an 'R' (or 'S' if 'S' acts as reset? Wait, problem says: "'R' : Reset area that restores the student's energy to full capacity...". Does 'S' act as a reset? Problem doesn't explicitly say 'S' is a reset, but usually 'S' doesn't necessarily reset unless it's also 'R'. Wait, if we start at 'S' with full energy, we can come back to 'S', but does it reset? "R : Reset area that restores...". Let's assume only 'R' resets energy, unless 'S' is marked 'R'. Wait, what if energy is large enough? If energy >= 50, maybe we don't even need R. But to be safe, any 'R' can reset. Can 'S' reset? The problem description says "'R' : Reset area...". It does not mention 'S' as reset. So only 'R' resets.)
        
        # Can we use Dijkstra or BFS to find shortest paths between important points?
        # Actually, standard TSP with state (current_pos, mask_of_litters, current_energy)?
        # But energy <= 50, grid is 20x20. State space for standard BFS/Dijkstra:
        # (r, c, mask, e) -> 400 * 1024 * 51 = ~2 * 10^7 states, which is totally feasible with 0-1 BFS or Dijkstra!
        # Wait, each move costs 1 energy. This is an unweighted shortest path graph!
        # State: (r, c, mask, e) where:
        # - (r, c) is the current position (400)
        # - mask is the bitmask of collected litters (up to 2^10 = 1024)
        # - e is the current energy (0 to energy, so 51 values)
        # Total states = 400 * 1024 * 51 = 20,951,040. This might be a bit tight for Python in time limits, but with BFS queue, many states are unreachable.
        # Let's optimize: Can we precompute distances or use a reduced graph?
        
        # Let's check if we can use a graph of (litter/start/resets).
        # Actually, since $k \le 10$, state space of TSP with dynamic energy is often solved by:
        # Instead of full grid BFS, we can find shortest paths between all pairs of (S, L_i, R_j).
        # But there can be many R's. Do we need all R's?
        # An R is useful if it lies on a path between two L's (or S and L) where energy would otherwise deplete.
        # Alternatively, since energy <= 50, maybe we can just do BFS on `(r, c, mask)` where we track `max_energy_left`? No, energy is consumed.
        
        # Let's re-evaluate the full state BFS: `(r, c, mask, e)`
        # Queue stores `(r, c, mask, e)`.
        # To avoid redundant states, `visited[r][c][mask][e]` can store the minimum moves. But since edge weights are all 1, the first time we reach a state in BFS, it's optimal!
        # Wait, is it? Yes, unweighted BFS finds the shortest path.
        # But wait! If we reach `(r, c, mask)` with energy `e1`, and later with energy `e2` where `e2 > e1`, the second one is strictly better (or equal). If `e2 <= e1`, the first one is better.
        # So `visited[r][c][mask]` can store the maximum energy we've ever had when reaching `(r, c)` with `mask`.
        # If we reach `(r, c, mask)` with energy `e`, and `e <= stored_energy[r][c][mask]`, we can prune!
        # This drastically reduces the state space because for a given cell and mask, we only care about the max energy we arrived with.
        
        dist = {} # (r, c, mask) -> max_energy
        queue = deque()
        
        start_mask = 0
        # Check if start is a litter
        for i, (lr, lc) in enumerate(litters):
            if start == (lr, lc):
                start_mask |= (1 << i)
                
        # queue stores (r, c, mask, e)
        queue.append((start[0], start[1], start_mask, energy))
        dist[(start[0], start[1], start_mask)] = energy
        
        moves = 0
        target_mask = (1 << k) - 1
        
        if start_mask == target_mask:
            return 0
            
        # Directions
        dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        
        while queue:
            # To count moves properly, we can either store `steps` in queue or do level-order BFS.
            # Since all edge weights are 1, level-order BFS guarantees shortest path in terms of moves.
            level_size = len(queue)
            for _ in range(level_size):
                r, c, mask, e = queue.popleft()
                
                if mask == target_mask:
                    return moves
                    
                if dist[(r, c, mask)] > e:
                    continue
                    
                for dr, dc in dirs:
                    nr, nc = r + dr, c + dc
                    if 0 <= nr < m and 0 <= nc < n and classroom[nr][nc] != 'X':
                        cell_type = classroom[nr][nc]
                        
                        # Determine new energy
                        if cell_type == 'R':
                            ne = energy
                        else:
                            ne = e - 1
                            
                        if ne < 0:
                            continue
                            
                        nmask = mask
                        if cell_type == 'L':
                            for i, (lr, lc) in enumerate(litters):
                                if lr == nr and lc == nc:
                                    nmask |= (1 << i)
                                    break
                                    
                        state_key = (nr, nc, nmask)
                        if ne > dist.get(state_key, -1):
                            dist[state_key] = ne
                            queue.append((nr, nc, nmask, ne))
                            
            moves += 1
            
        return -1