# LeetCode Daily Challenge
# Date: 2026-05-25
# Problem: Jump Game VII
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

import collections

class Solution:
    def canReach(self, binary_string: str, minimum_jump_distance: int, maximum_jump_distance: int) -> bool:
        
        exploration_queue = collections.deque([0])
        
        farthest_index_covered = 0 
        
        total_length = len(binary_string)
        destination_index = total_length - 1

        while exploration_queue:
            
            current_idx = exploration_queue.popleft()
            
            # Determine the start of the next possible jump range.
            # It must be at least 'current_idx + minimum_jump_distance'
            # and also greater than 'farthest_index_covered' to avoid re-evaluating indices.
            next_jump_start_point = max(current_idx + minimum_jump_distance, farthest_index_covered + 1)
            
            # Determine the end of the next possible jump range (exclusive).
            # It cannot exceed 'current_idx + maximum_jump_distance'
            # and must be within the bounds of the 'binary_string'.
            next_jump_end_point = min(current_idx + maximum_jump_distance + 1, total_length)
            
            potential_next_position = next_jump_start_point
            while potential_next_position < next_jump_end_point:
                
                # A jump is valid only if the target cell is '0'
                if binary_string[potential_next_position] == '0':
                    # If the destination is reached, return True
                    if potential_next_position == destination_index:
                        return True
                    
                    # Otherwise, add this new reachable position to the queue
                    exploration_queue.append(potential_next_position)
                
                potential_next_position += 1
            
            # Update 'farthest_index_covered'. Since we are processing in BFS order,
            # 'current_idx' is monotonically increasing, so 'current_idx + maximum_jump_distance'
            # will always represent the maximum index reachable from any previously processed node.
            farthest_index_covered = current_idx + maximum_jump_distance
            
        return False