# LeetCode Daily Challenge
# Date: 2026-08-26
# Problem: Shortest and Lexicographically Smallest Beautiful String
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def shortestBeautifulSubstring(self, input_string_data, target_one_count):
        string_length = len(input_string_data)
        shortest_lex_beautiful = ""
        left_boundary = 0
        right_boundary = 0
        active_one_count = 0

        while (right_boundary < string_length):
            if (input_string_data[right_boundary] == '1'):
                active_one_count += 1
            
            if (active_one_count == target_one_count):
                while (left_boundary < string_length) and (active_one_count == target_one_count):
                    current_window_str = input_string_data[left_boundary : right_boundary + 1]
                    
                    if (len(shortest_lex_beautiful) == 0) or (len(current_window_str) < len(shortest_lex_beautiful)):
                        shortest_lex_beautiful = current_window_str
                    elif (len(current_window_str) == len(shortest_lex_beautiful)):
                        shortest_lex_beautiful = min(shortest_lex_beautiful, current_window_str)
                    
                    if (input_string_data[left_boundary] == '1'):
                        active_one_count -= 1
                    left_boundary += 1
            
            right_boundary += 1
        
        return shortest_lex_beautiful