# LeetCode Daily Challenge
# Date: 2026-03-29
# Problem: Check if Strings Can be Made Equal With Operations I
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def canBeEqual(self, string_one_input: str, string_two_input: str) -> bool:

        # Extract characters from the first string at even indices
        first_str_char_at_zero = string_one_input[0]
        first_str_char_at_two = string_one_input[2]
        even_chars_from_first = {first_str_char_at_zero, first_str_char_at_two}

        # Extract characters from the second string at even indices
        second_str_char_at_zero = string_two_input[0]
        second_str_char_at_two = string_two_input[2]
        even_chars_from_second = {second_str_char_at_zero, second_str_char_at_two}

        # Extract characters from the first string at odd indices
        first_str_char_at_one = string_one_input[1]
        first_str_char_at_three = string_one_input[3]
        odd_chars_from_first = {first_str_char_at_one, first_str_char_at_three}

        # Extract characters from the second string at odd indices
        second_str_char_at_one = string_two_input[1]
        second_str_char_at_three = string_two_input[3]
        odd_chars_from_second = {second_str_char_at_one, second_str_char_at_three}

        # Check if the sets of even-indexed characters are identical
        even_index_sets_are_equal = (even_chars_from_first == even_chars_from_second)

        # Check if the sets of odd-indexed characters are identical
        odd_index_sets_are_equal = (odd_chars_from_first == odd_chars_from_second)

        # The strings can be made equal if both conditions are true
        return even_index_sets_are_are_equal and odd_index_sets_are_equal