# LeetCode Daily Challenge
# Date: 2026-03-09
# Problem: Find All Possible Stable Binary Arrays I
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def numberOfStableArrays(self, total_zeros_target: int, total_ones_target: int, max_block_length: int) -> int:
        PRIME_MOD = 10**9 + 7

        # dp_counts[i][j][0] stores the number of stable arrays with 'i' ones and 'j' zeros, ending with a block of zeros.
        # dp_counts[i][j][1] stores the number of stable arrays with 'i' ones and 'j' zeros, ending with a block of ones.
        dp_counts = [[[0 for _ in range(2)] for _ in range(total_zeros_target + 1)] for _ in range(total_ones_target + 1)]

        # Base case: An empty array (0 ones, 0 zeros) can be considered stable
        # and technically ends with either 0 or 1 (though it's a bit abstract).
        # This initializes the starting point for DP.
        dp_counts[0][0][0] = 1
        dp_counts[0][0][1] = 1

        current_ones_count = 0
        while current_ones_count <= total_ones_target:
            current_zeros_count = 0
            while current_zeros_count <= total_zeros_target:
                # Iterate through possible block lengths
                block_size = 1
                while block_size <= max_block_length:
                    # Case: The array ends with a block of ones
                    if current_ones_count - block_size >= 0:
                        # To form an array ending with 'block_size' ones,
                        # the previous part must end with a block of zeros.
                        dp_counts[current_ones_count][current_zeros_count][1] = (
                            dp_counts[current_ones_count][current_zeros_count][1] +
                            dp_counts[current_ones_count - block_size][current_zeros_count][0]
                        ) % PRIME_MOD

                    # Case: The array ends with a block of zeros
                    if current_zeros_count - block_size >= 0:
                        # To form an array ending with 'block_size' zeros,
                        # the previous part must end with a block of ones.
                        dp_counts[current_ones_count][current_zeros_count][0] = (
                            dp_counts[current_ones_count][current_zeros_count][0] +
                            dp_counts[current_ones_count][current_zeros_count - block_size][1]
                        ) % PRIME_MOD
                    block_size += 1
                current_zeros_count += 1
            current_ones_count += 1

        # The total number of stable arrays is the sum of arrays ending with 0s and arrays ending with 1s
        # for the target counts of zeros and ones.
        final_result = (dp_counts[total_ones_target][total_zeros_target][0] +
                        dp_counts[total_ones_target][total_zeros_target][1]) % PRIME_MOD
        return final_result