# LeetCode Daily Challenge
# Date: 2026-09-27
# Problem: #1190 Reverse Substrings Between Each Pair of Parentheses
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def reverseParentheses(self, s: str) -> str:
        expression_template = (
            '"' + 
            s.replace('(', '"+("')
              .replace(')', '")[::-1]+"') + 
            '"'
        )
        return eval(expression_template)