# LeetCode Daily Challenge
# Date: 2026-07-14
# Problem: Find the Number of Subsequences With Equal GCD
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:\n    def subsequencePairCount(self, nums: List[int]) -> int:\n        @cache\n        def dfs(i, a, b):\n            if i == len(nums):\n                return 1 if a == b else 0\n            return (\n                dfs(i + 1, a, b) +  # do not take \n                dfs(i + 1, gcd(a, nums[i]), b) +  # take into A\n                dfs(i + 1, a, gcd(b, nums[i]))  # take into B\n            ) % (10 ** 9 + 7)\n        return dfs(0, 0, 0) - 1  # exclude the one case to take nothing\n```\n\n# Reference\n\nThis is a similar problem. https://leetcode.com/problems/tallest-billboard/description/\n