# LeetCode Daily Challenge
# Date: 2026-07-06
# Problem: Remove Covered Intervals
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution(object):
    def removeCoveredIntervals(self, segment_collection):
        # Sort the intervals: primary key is start point (ascending), secondary key is end point (descending)
        segment_collection.sort(key=lambda current_item: (current_item[0], -current_item[1]))

        current_max_endpoint = -1  # Tracks the maximum end point among non-covered intervals encountered so far
        number_of_covered_segments = 0 # Counter for intervals that are found to be covered

        segment_pointer = 0
        total_number_of_segments = len(segment_collection)

        while segment_pointer < total_number_of_segments:
            present_segment = segment_collection[segment_pointer]
            
            # Extract start and end for clarity, although not strictly necessary for the logic
            segment_start_value = present_segment[0]
            segment_end_value = present_segment[1]

            # If the current segment's end point is less than or equal to the maximum end point seen,
            # it means this segment is covered by a previous, non-covered segment.
            if segment_end_value <= current_max_endpoint:
                number_of_covered_segments = number_of_covered_segments + 1
            else:
                # If it's not covered, then this segment potentially extends our maximum reach.
                # Update the maximum end point.
                current_max_endpoint = segment_end_value
            
            segment_pointer = segment_pointer + 1
            
        # The result is the total number of segments minus those identified as covered.
        return total_number_of_segments - number_of_covered_segments