# LeetCode Daily Challenge
# Date: 2026-04-07
# Problem: Walking Robot Simulation II
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class RobotGridTraversal:

    def __init__(self, grid_width_val, grid_height_val):
        self.current_path_index = 0
        
        perimeter_points = []

        # Initial point as per path definition (0, 0, 'South')
        perimeter_points.append([0, 0, 'South'])

        # Segment 1: Bottom edge, moving East (x from 1 to grid_width_val-1, y=0)
        x_position = 1
        while x_position < grid_width_val:
            perimeter_points.append([x_position, 0, 'East'])
            x_position += 1

        # Segment 2: Right edge, moving North (x=grid_width_val-1, y from 1 to grid_height_val-1)
        y_position = 1
        while y_position < grid_height_val:
            perimeter_points.append([grid_width_val - 1, y_position, 'North'])
            y_position += 1

        # Segment 3: Top edge, moving West (x from grid_width_val-2 down to 0, y=grid_height_val-1)
        x_position = grid_width_val - 2
        while x_position >= 0:
            perimeter_points.append([x_position, grid_height_val - 1, 'West'])
            x_position -= 1

        # Segment 4: Left edge, moving South (x=0, y from grid_height_val-2 down to 1)
        y_position = grid_height_val - 2
        while y_position > 0:
            perimeter_points.append([0, y_position, 'South'])
            y_position -= 1
        
        self.robot_path_data = perimeter_points

    def move(self, steps_to_advance):
        self.current_path_index += steps_to_advance

    def getPos(self):
        path_total_length = len(self.robot_path_data)
        effective_idx = self.current_path_index % path_total_length
        return self.robot_path_data[effective_idx][:2]

    def getDir(self):
        path_total_length = len(self.robot_path_data)
        effective_idx = self.current_path_index % path_total_length
        
        # Special condition for the initial state (index 0) as per problem spec
        if self.current_path_index == 0:
            return 'East'
        else:
            return self.robot_path_data[effective_idx][2]