# LeetCode Daily Challenge
# Date: 2026-09-29
# Problem: #2267  Check if There Is a Valid Parentheses String Path
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def hasValidPath(self, grid: List[List[str]]) -> bool:  
        rows_count = len(grid)
        cols_count = len(grid[0])
        
        @lru_cache(maxsize=None)
        def _explore_path(row_idx, col_idx, balance_count):
            if row_idx == rows_count or col_idx == cols_count or balance_count < 0:
                return False
            
            balance_count += 1 if grid[row_idx][col_idx] == '(' else -1
            
            if row_idx == rows_count - 1 and col_idx == cols_count - 1 and balance_count == 0:
                return True
            
            return _explore_path(row_idx + 1, col_idx, balance_count) or _explore_path(row_idx, col_idx + 1, balance_count)

        return _explore_path(0, 0, 0)