# LeetCode Daily Challenge
# Date: 2026-09-08
# Problem: #3870 Count Commas in Range
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def countCommas(self, n: int) -> int:
        total_commas = 0
        if n >= 1000:
            total_commas += (n - 1000 + 1)
        if n >= 100000:
            total_commas += (n - 100000 + 1)
        return total_commas