# LeetCode Daily Challenge
# Date: 2026-09-21
# Problem: #3524 Find X Value of Array I
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

from typing import List

class Solution:
    def resultArray(self, nums: List[int], k: int) -> List[int]:
        n = len(nums)
        # Since $k \le 5$, we can maintain the counts of each remainder modulo $k$
        # for all possible non-empty subarrays using dynamic programming / hashing.
        
        # A non-overlapping prefix and suffix removal means we are choosing a non-empty subarray.
        # Wait, the problem says "remove any non-overlapping prefix and suffix".
        # This is equivalent to choosing any non-empty contiguous subarray!
        # Let's double check:
        # Array: [p1 ... p_end] [chosen subarray] [s_start ... s_end]
        # We remove a prefix (which can be empty) and a suffix (which can be empty) such that they are non-overlapping.
        # This means the remaining part is a contiguous subarray of nums!
        # And the prefix and suffix are disjoint (or can touch? "non-overlapping prefix and suffix".
        # A prefix of an array starts from the beginning. A suffix starts anywhere and extends to the end.
        # Removing a prefix of length L and a suffix of length R such that they are non-overlapping
        # means L + R <= n, and the remaining part is nums[L : n - R].
        # Since L >= 0 and R >= 0, and they don't overlap, the remaining elements form a non-empty contiguous subarray.
        # Specifically, any non-empty contiguous subarray nums[i : j+1] (0 <= i <= j < n)
        # corresponds to removing prefix of length i and suffix of length n - 1 - j.
        # Since i <= j, i + (n - 1 - j) <= n - 1 < n, so the prefix and suffix do not overlap.
        # Thus, the problem is simply to count the product modulo k for ALL non-empty contiguous subarrays!
        
        # Since k <= 5, we can use the fact that the number of unique values in running products
        # modulo k is at most k (in fact, since k is small, we can just maintain counts of remainders).
        # Actually, as we iterate through the right endpoint j, the set of possible products of subarrays ending at j
        # has size at most k. We can maintain a dictionary or array of size k for the current ending point.
        
        ans = [0] * k
        
        # dp[r] will store the number of subarrays ending at the current position with product % k == r
        current_counts = [0] * k
        
        for num in nums:
            val = num % k
            next_counts = [0] * k
            # Single element subarray [num]
            next_counts[val] += 1
            
            # Extend previous subarrays ending at j-1
            for r in range(k):
                if current_counts[r] > 0:
                    new_r = (r * val) % k
                    next_counts[new_r] += current_counts[r]
            
            current_counts = next_counts
            for r in range(k):
                ans[r] += current_counts[r]
                
        return ans