# LeetCode Daily Challenge
# Date: 2026-09-16
# Problem: #1621 Number of Sets of K Non-Overlapping Line Segments
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

from functools import lru_cache

class Solution:
    def numberOfSets(self, n: int, k: int) -> int:
        MODULO = 10**9 + 7
        
        @lru_cache(None)
        def compute_sets(index: int, remaining_segments: int, is_active: bool) -> int:
            if index == n - 1:
                return 0 if remaining_segments else 1
            
            total_ways = 0
            if is_active:
                total_ways += compute_sets(index + 1, remaining_segments, is_active)
                total_ways %= MODULO
                total_ways += compute_sets(index + 1, remaining_segments, not is_active)
                total_ways %= MODULO
                if remaining_segments > 0:
                    total_ways += compute_sets(index + 1, remaining_segments - 1, is_active)
                    total_ways %= MODULO
            else:
                total_ways += compute_sets(index + 1, remaining_segments, is_active)
                total_ways %= MODULO
                if remaining_segments > 0:
                    total_ways += compute_sets(index + 1, remaining_segments - 1, not is_active)
                    total_ways %= MODULO
                    
            return total_ways
            
        return compute_sets(0, k, False)