# LeetCode Daily Challenge
# Date: 2026-10-04
# Problem: #678 Valid Parenthesis String
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def checkValidString(self, s: str) -> bool:
        paren_stack = []
        star_stack = []
        
        for curr_index, curr_char in enumerate(s):
            if curr_char == '(':
                paren_stack.append(curr_index)
            elif curr_char == ')':
                if paren_stack:
                    paren_stack.pop()
                elif star_stack:
                    star_stack.pop()
                else:
                    return False
            else:
                star_stack.append(curr_index)
        
        while paren_stack and star_stack:
            if paren_stack[-1] > star_stack[-1]:
                return False
            paren_stack.pop()
            star_stack.pop()
        
        return not paren_stack