# LeetCode Daily Challenge
# Date: 2026-05-24
# Problem: Jump Game V
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def maxJumps(self, arr_values, max_dist):
        array_length = len(arr_values)
        adjacency_list = collections.defaultdict(list)
        
        def build_connections(index_sequence):
            monotonic_stack = []
            for current_idx in index_sequence:
                while monotonic_stack and arr_values[monotonic_stack[-1]] < arr_values[current_idx]:
                    popped_idx = monotonic_stack.pop()
                    if abs(current_idx - popped_idx) <= max_dist: adjacency_list[popped_idx].append(current_idx)
                monotonic_stack.append(current_idx)
        
        build_connections(range(array_length))
        build_connections(reversed(range(array_length)))
        
        @functools.lru_cache(maxsize=None)
        def calculate_max_jumps_from_index(start_index):
            return 1 + max(map(calculate_max_jumps_from_index, adjacency_list[start_index]), default=0)
        
        return max(map(calculate_max_jumps_from_index, range(array_length)))