# LeetCode Daily Challenge
# Date: 2026-05-01
# Problem: Rotate Function
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution(object):
    def maxRotateFunction(self, numbers_list):
        current_cumulative_sum = sum(index * element for index, element in enumerate(numbers_list))
        maximum_achieved_value = current_cumulative_sum
        total_elements_sum = sum(numbers_list)
        initial_list_size = len(numbers_list)
        while numbers_list:
            removed_element = numbers_list.pop()
            current_cumulative_sum += total_elements_sum - removed_element * initial_list_size
            maximum_achieved_value = max(current_cumulative_sum, maximum_achieved_value)
        return maximum_achieved_value