# LeetCode Daily Challenge
# Date: 2026-03-19
# Problem: Count Submatrices With Equal Frequency of X and Y
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def numberOfSubmatrices(self, grid: List[List[str]]) -> int:

        # Determine the number of columns in the grid.
        column_dimension = len(grid[0])

        # Initialize arrays to store the running counts of 'X' and 'Y'
        # for submatrices ending at the current row, across all columns.
        # 'matrix_x_counts[k]' will hold the total 'X's in the submatrix
        # defined by rows 0 to current_row_idx and columns 0 to k.
        matrix_x_counts = [0] * column_dimension
        matrix_y_counts = [0] * column_dimension

        # This variable will accumulate the count of submatrices
        # that satisfy the given conditions.
        submatrix_satisfaction_count = 0

        current_row_idx = 0
        total_rows_in_grid = len(grid)

        # Iterate through each row of the input grid using a while loop.
        while current_row_idx < total_rows_in_grid:
            present_row_data = grid[current_row_idx]

            # These variables track the 'X' and 'Y' counts within the
            # current row as we scan from the leftmost column to the right.
            x_count_within_row_prefix = 0
            y_count_within_row_prefix = 0

            col_traversal_idx = 0
            # Iterate through each column in the present row using a while loop.
            while col_traversal_idx < column_dimension:

                # Update the counts for 'X' and 'Y' based on the current cell's content.
                if present_row_data[col_traversal_idx] == 'X':
                    x_count_within_row_prefix += 1
                elif present_row_data[col_traversal_idx] == 'Y':
                    y_count_within_row_prefix += 1

                # Add the current row's prefix counts to the overall
                # cumulative counts for the submatrix ending at
                # (current_row_idx, col_traversal_idx).
                matrix_x_counts[col_traversal_idx] += x_count_within_row_prefix
                matrix_y_counts[col_traversal_idx] += y_count_within_row_prefix

                # Check if the submatrix ending at the current cell
                # meets the criteria: at least one 'X' and an equal
                # number of 'X's and 'Y's.
                if matrix_x_counts[col_traversal_idx] > 0 and \
                   matrix_x_counts[col_traversal_idx] == matrix_y_counts[col_traversal_idx]:
                    submatrix_satisfaction_count += 1

                col_traversal_idx += 1
            current_row_idx += 1

        return submatrix_satisfaction_count