# LeetCode Daily Challenge
# Date: 2026-09-20
# Problem: #3498 Reverse Degree of a String
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution(object):
    def reverseDegree(self, s):
        total_sum = 0
        for index, character in enumerate(s):
            weight = 123 - ord(character)
            product = weight * (index + 1)
            total_sum += product
        return total_sum