# LeetCode Daily Challenge
# Date: 2026-06-29
# Problem: Number of Strings That Appear as Substrings in Word
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def numOfStrings(self, search_patterns: List[str], target_string: str) -> int:
        total_matches = sum(1 for current_pattern in search_patterns if current_pattern in target_string)
        return total_matches