# LeetCode Daily Challenge
# Date: 2026-10-01
# Problem: #20 Valid Parentheses
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution(object):
    def isValid(self, s):
        """
        :type s: str
        :rtype: bool
        """
        bracket_mapping = {'(': ')', '{': '}', '[': ']'}
        char_stack = []
        
        for current_char in s:
            if current_char in bracket_mapping:
                char_stack.append(current_char)
            elif not char_stack or bracket_mapping[char_stack.pop()] != current_char:
                return False
                
        return not char_stack