# LeetCode Daily Challenge
# Date: 2026-08-09
# Problem: Stone Game II
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def solve_game(self, stone_amounts_list, memoization_table, total_suffix_sums, current_pile_index, current_max_take):
        total_piles_count = len(stone_amounts_list)
        
        # Base case 1: No piles left to consider
        if current_pile_index == total_piles_count:
            return 0
        
        # Base case 2: Current player can take all remaining piles
        # This occurs if the number of remaining piles is less than or equal to 2 * current_max_take
        if current_pile_index + (2 * current_max_take) >= total_piles_count:
            return total_suffix_sums[current_pile_index]
        
        # Check if this state has already been computed
        if memoization_table[current_pile_index][current_max_take] != 0:
            return memoization_table[current_pile_index][current_max_take]
        
        # Initialize the maximum score for the current player for this state
        player_max_gain = 0
        
        # Iterate through possible number of stones to take (from 1 up to 2 * current_max_take)
        stones_to_grab = 1
        max_possible_grab = 2 * current_max_take
        
        while stones_to_grab <= max_possible_grab:
            # Calculate the score if the current player takes 'stones_to_grab'
            # This is the total sum of remaining stones minus what the opponent gets
            score_if_taken = total_suffix_sums[current_pile_index] - self.solve_game(
                stone_amounts_list,
                memoization_table,
                total_suffix_sums,
                current_pile_index + stones_to_grab,
                max(current_max_take, stones_to_grab) # Update M for the next player
            )
            
            # Update the maximum score for the current player
            player_max_gain = max(player_max_gain, score_if_taken)
            stones_to_grab += 1
            
        # Store the computed result in the memoization table
        memoization_table[current_pile_index][current_max_take] = player_max_gain
        return player_max_gain

    def stoneGameII(self, pile_values):
        if not pile_values:
            return 0
        
        number_of_piles = len(pile_values)
        
        # Initialize DP table (memoization_table) with zeros
        # Dimensions: [number_of_piles][number_of_piles]
        memoization_table = [[0] * number_of_piles for _ in range(number_of_piles)]
        
        # Calculate suffix sums
        # total_suffix_sums[i] stores the sum of stones from index i to the end
        total_suffix_sums = [0] * number_of_piles
        
        # The last element's suffix sum is just itself
        total_suffix_sums[number_of_piles - 1] = pile_values[number_of_piles - 1]
        
        # Compute suffix sums from right to left
        current_index_for_sum = number_of_piles - 2
        while current_index_for_sum >= 0:
            total_suffix_sums[current_index_for_sum] = pile_values[current_index_for_sum] + total_suffix_sums[current_index_for_sum + 1]
            current_index_for_sum -= 1
            
        # Start the game from the first pile (index 0) with initial M=1
        return self.solve_game(pile_values, memoization_table, total_suffix_sums, 0, 1)