# LeetCode Daily Challenge
# Date: 2026-04-24
# Problem: Furthest Point From Origin
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def furthestDistanceFromOrigin(self, movement_sequence: str) -> int:

        left_move_count = 0
        right_move_count = 0
        wildcard_move_count = 0

        current_position = 0
        sequence_length = len(movement_sequence)

        while current_position < sequence_length:
            character_at_pos = movement_sequence[current_position]
            if character_at_pos == 'L':
                left_move_count += 1
            elif character_at_pos == 'R':
                right_move_count += 1
            else: # character_at_pos == '_'
                wildcard_move_count += 1
            current_position += 1

        directional_imbalance = abs(left_move_count - right_move_count)
        maximum_possible_displacement = directional_imbalance + wildcard_move_count

        return maximum_possible_displacement