# LeetCode Daily Challenge
# Date: 2026-04-21
# Problem: Minimize Hamming Distance After Swap Operations
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import collections
from typing import List

class Solution:
    def minimumHammingDistance(self, initial_values: List[int], final_values: List[int], swap_pairs_list: List[List[int]]) -> int:
        
        num_elements = len(initial_values)
        node_parents = list(range(num_elements))
        tree_heights = [0] * num_elements

        def get_root(element_index: int) -> int:
            if node_parents[element_index] != element_index:
                node_parents[element_index] = get_root(node_parents[element_index])
            return node_parents[element_index]

        def unite_components(idx_a: int, idx_b: int):
            root_a = get_root(idx_a)
            root_b = get_root(idx_b)

            if root_a != root_b:
                if tree_heights[root_a] > tree_heights[root_b]:
                    root_a, root_b = root_b, root_a
                
                node_parents[root_a] = root_b
                
                if tree_heights[root_a] == tree_heights[root_b]:
                    tree_heights[root_b] += 1

        pair_iterator = 0
        while pair_iterator < len(swap_pairs_list):
            current_pair = swap_pairs_list[pair_iterator]
            unite_components(current_pair[0], current_pair[1])
            pair_iterator += 1

        component_value_balances = collections.defaultdict(collections.Counter)

        item_index = 0
        while item_index < num_elements:
            current_source_val = initial_values[item_index]
            current_target_val = final_values[item_index]
            
            component_representative = get_root(item_index)
            
            component_value_balances[component_representative][current_source_val] += 1
            component_value_balances[component_representative][current_target_val] -= 1
            
            item_index += 1

        return sum(val_excess for component_map in component_value_balances.values() for val_excess in component_map.values() if val_excess > 0)