# LeetCode Daily Challenge
# Date: 2026-09-07
# Problem: #940 Distinct Subsequences II
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def distinctSubseqII(self, s: str) -> int:
        total_subsequences = 1
        last_seen_count = {}
        
        for char in s:
            increment = total_subsequences - last_seen_count.get(char, 0)
            last_seen_count[char] = last_seen_count.get(char, 0) + increment
            total_subsequences += increment
            
        return (total_subsequences - 1) % (10**9 + 7)