# LeetCode Daily Challenge
# Date: 2026-08-21
# Problem: Kth Smallest Amount With Single Denomination Combination
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from typing import List
from collections import defaultdict
import itertools
import math

class Solution:
    def findKthSmallest(self, coins: List[int], k: int) -> int:
        num_coin_types = len(coins)
        lcm_groups_by_size = defaultdict(list)
        
        subset_size_counter = 1
        while subset_size_counter <= num_coin_types:
            for current_combination in itertools.combinations(coins, subset_size_counter):
                lcm_groups_by_size[len(current_combination)].append(math.lcm(*current_combination))
            subset_size_counter += 1
        
        def calculate_elements_up_to(lcm_data_map, upper_bound_val):
            total_counted_elements = 0
            current_subset_size = 1
            while current_subset_size <= num_coin_types:
                for calculated_lcm_val in lcm_data_map[current_subset_size]:
                    total_counted_elements += upper_bound_val // calculated_lcm_val * ((-1)**(current_subset_size + 1))
                current_subset_size += 1
            return total_counted_elements
        
        search_low_bound, search_high_bound = min(coins), min(coins) * k
        
        while search_low_bound < search_high_bound - 1:
            current_guess_val = (search_low_bound + search_high_bound) // 2
            if calculate_elements_up_to(lcm_groups_by_size, current_guess_val) >= k:
                search_high_bound = current_guess_val
            else:
                search_low_bound = current_guess_val
        
        if calculate_elements_up_to(lcm_groups_by_size, search_low_bound) >= k:
            return search_low_bound
        else:
            return search_high_bound