# LeetCode Daily Challenge
# Date: 2026-09-11
# Problem: #3483 Unique 3-Digit Even Numbers
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def totalNumbers(self, digits: List[int]) -> int:
        valid_numbers = set()
        digit_counts = [0] * 10
        
        for d in digits:
            digit_counts[d] += 1

        for first in range(1, 10):
            if digit_counts[first] == 0:
                continue
            digit_counts[first] -= 1
            
            for second in range(0, 10):
                if digit_counts[second] == 0:
                    continue
                digit_counts[second] -= 1
                
                for third in range(0, 10, 2):
                    if digit_counts[third] > 0:
                        valid_numbers.add(first * 100 + second * 10 + third)
                        
                digit_counts[second] += 1
            digit_counts[first] += 1

        return len(valid_numbers)