# LeetCode Daily Challenge
# Date: 2026-05-31
# Problem: Destroying Asteroids
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def asteroidsDestroyed(self, initial_power: int, celestial_bodies: List[int]) -> bool:
        
        celestial_bodies.sort()
        
        current_power = initial_power
        
        body_index = 0
        number_of_bodies = len(celestial_bodies)
        
        while body_index < number_of_bodies:
            body_mass = celestial_bodies[body_index]
            
            if body_mass <= current_power:
                current_power += body_mass
            else:
                return False
            
            body_index += 1
            
        return True