# LeetCode Daily Challenge
# Date: 2026-07-13
# Problem: Sequential Digits
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def sequentialDigits(self, lower_limit: int, upper_limit: int) -> List[int]:
        source_digits_string = "123456789"
        result_collection = []

        length_min = len(str(lower_limit))
        length_max = len(str(upper_limit))

        current_length_val = length_min
        while current_length_val <= length_max:
            start_idx_val = 0
            # The maximum starting position for a substring of 'current_length_val'
            # is such that the substring ends at or before the end of 'source_digits_string'.
            # len(source_digits_string) is 9.
            # So, start_idx_val + current_length_val <= 9.
            # This implies start_idx_val <= 9 - current_length_val.
            # The original loop range was `range(0, 10 - i)`, meaning 'j' went up to `9 - i`.
            # Thus, `start_idx_val < (10 - current_length_val)` is the correct condition.
            max_start_position = len(source_digits_string) - current_length_val + 1

            while start_idx_val < max_start_position:
                end_idx_val = start_idx_val + current_length_val
                substring_representation = source_digits_string[start_idx_val: end_idx_val]
                candidate_number_val = int(substring_representation)

                if lower_limit <= candidate_number_val <= upper_limit:
                    result_collection.append(candidate_number_val)

                start_idx_val += 1
            current_length_val += 1

        return result_collection