# LeetCode Daily Challenge
# Date: 2026-03-31
# Problem: Lexicographically Smallest Generated String
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def generate_reconstructed_string(self, source_instructions: str, target_pattern: str) -> str:
        source_char_list = list(source_instructions)
        source_length = len(source_char_list)
        pattern_length = len(target_pattern)
        reconstructed_output = ['?'] * (source_length + pattern_length - 1)

        # Process 'T' instructions
        z_function_for_pattern = self._compute_z_array(target_pattern)
        
        previous_t_occurrence_index = -pattern_length
        current_source_instruction_index = 0
        while current_source_instruction_index < source_length:
            if source_char_list[current_source_instruction_index] != 'T':
                current_source_instruction_index += 1
                continue

            current_overlap_length = max(previous_t_occurrence_index + pattern_length - current_source_instruction_index, 0)
            
            # Check prefix/suffix equality for 'T'
            if current_overlap_length > 0 and z_function_for_pattern[pattern_length - current_overlap_length] < current_overlap_length:
                return ""
            
            # Fill in the target pattern
            char_fill_position = current_overlap_length
            while char_fill_position < pattern_length:
                reconstructed_output[current_source_instruction_index + char_fill_position] = target_pattern[char_fill_position]
                char_fill_position += 1
            
            previous_t_occurrence_index = current_source_instruction_index
            current_source_instruction_index += 1

        # Determine the nearest preceding undecided position for each index
        last_question_mark_indices = [0] * len(reconstructed_output)
        most_recent_q_mark_position = -1
        output_array_iterator = 0
        while output_array_iterator < len(reconstructed_output):
            if reconstructed_output[output_array_iterator] == '?':
                reconstructed_output[output_array_iterator] = 'a' # Default value for undecided
                most_recent_q_mark_position = output_array_iterator
            last_question_mark_indices[output_array_iterator] = most_recent_q_mark_position
            output_array_iterator += 1

        # Compute Z-function for the combined string (pattern + reconstructed_output)
        combined_string_for_z_calculation = target_pattern + "".join(reconstructed_output)
        z_function_combined_results = self._compute_z_array(combined_string_for_z_calculation)

        # Process 'F' instructions
        current_instruction_position = 0
        while current_instruction_position < source_length:
            if source_char_list[current_instruction_position] != 'F':
                current_instruction_position += 1
                continue
            
            # Check if the substring at current_instruction_position equals the target_pattern
            if z_function_combined_results[pattern_length + current_instruction_position] < pattern_length:
                current_instruction_position += 1
                continue
            
            # Find the last undecided position within the current pattern match
            target_undecided_position = last_question_mark_indices[current_instruction_position + pattern_length - 1]
            if target_undecided_position < current_instruction_position: # No undecided position exists within bounds
                return ""
            
            reconstructed_output[target_undecided_position] = 'b' # Mark as 'b' to make it different from 'a'
            current_instruction_position = target_undecided_position + 1 # Jump to avoid reprocessing this segment

        return "".join(reconstructed_output)

    def _compute_z_array(self, input_text: str) -> list[int]:
        text_characters = list(input_text)
        text_length = len(text_characters)
        z_result_array = [0] * text_length
        
        z_box_left_boundary = 0
        z_box_right_boundary = 0
        
        current_comparison_index = 1
        while current_comparison_index < text_length:
            if current_comparison_index <= z_box_right_boundary:
                z_result_array[current_comparison_index] = min(z_result_array[current_comparison_index - z_box_left_boundary], z_box_right_boundary - current_comparison_index + 1)
            
            while current_comparison_index + z_result_array[current_comparison_index] < text_length and \
                  text_characters[z_result_array[current_comparison_index]] == text_characters[current_comparison_index + z_result_array[current_comparison_index]]:
                z_box_left_boundary = current_comparison_index
                z_box_right_boundary = current_comparison_index + z_result_array[current_comparison_index]
                z_result_array[current_comparison_index] += 1
            current_comparison_index += 1
        
        if text_length > 0:
            z_result_array[0] = text_length
        return z_result_array