# LeetCode Daily Challenge
# Date: 2026-04-01
# Problem: Robot Collisions
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def survivedRobotsHealths(self, robot_positions: List[int], robot_healths: List[int], robot_directions_str: str) -> List[int]:
        num_entities = len(robot_positions)
        all_robot_units = [] # Format: [position, health, direction, original_index]

        # Populate initial robot data using a while loop
        current_index = 0
        while current_index < num_entities:
            all_robot_units.append([
                robot_positions[current_index],
                robot_healths[current_index],
                robot_directions_str[current_index],
                current_index
            ])
            current_index += 1

        # Sort all robot units based on their position (first element)
        all_robot_units.sort()

        collision_handling_stack = []

        # Iterate through sorted robot units to simulate collisions using a while loop
        processing_iterator = 0
        while processing_iterator < num_entities:
            current_robot_being_processed = all_robot_units[processing_iterator]
            current_robot_direction = current_robot_being_processed[2] # Index 2 holds direction

            # Case 1: Robot moves 'R', or stack is empty, or stack top moves 'L'.
            # No immediate collision with stack top, so just add to stack.
            if current_robot_direction == 'R' or not collision_handling_stack or collision_handling_stack[-1][2] == 'L':
                collision_handling_stack.append(current_robot_being_processed)
            else: # Case 2: Current robot moves 'L' and stack top moves 'R'. Collision!
                should_add_this_robot = True # Flag to track if the current robot survives to be added to stack
                
                # Resolve collisions with robots on the stack moving 'R'
                while collision_handling_stack and collision_handling_stack[-1][2] == 'R' and should_add_this_robot:
                    top_stack_robot = collision_handling_stack[-1]
                    top_stack_robot_health = top_stack_robot[1] # Index 1 holds health

                    if current_robot_being_processed[1] > top_stack_robot_health:
                        # Current robot wins, top robot is destroyed, current robot's health decreases
                        collision_handling_stack.pop()
                        current_robot_being_processed[1] -= 1
                    elif current_robot_being_processed[1] < top_stack_robot_health:
                        # Top robot wins, current robot is destroyed, top robot's health decreases
                        top_stack_robot[1] -= 1
                        should_add_this_robot = False # Current robot is destroyed, won't be added
                    else:
                        # Both robots have equal health and destroy each other
                        collision_handling_stack.pop()
                        should_add_this_robot = False # Current robot is destroyed, won't be added
                
                # If the current robot survived all confrontations, add it to the stack
                if should_add_this_robot:
                    collision_handling_stack.append(current_robot_being_processed)
            
            processing_iterator += 1

        # Sort the remaining robots by their original index to get the final order
        remaining_robots_in_original_order = sorted(collision_handling_stack, key=lambda unit_info: unit_info[3])

        # Extract the healths of the surviving robots using a while loop
        final_health_results = []
        result_iterator = 0
        while result_iterator < len(remaining_robots_in_original_order):
            final_health_results.append(remaining_robots_in_original_order[result_iterator][1]) # Index 1 is health
            result_iterator += 1

        return final_health_results