# LeetCode Daily Challenge
# Date: 2026-07-05
# Problem: Number of Paths with Max Score
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def pathsWithMaxScore(self, board: List[str]) -> List[int]:
        num_rows = len(board)
        num_cols = len(board[0])

        from functools import lru_cache

        @lru_cache(maxsize=None)
        def calculate_max_score_and_paths(current_row, current_col, dummy_path_param):
            if current_row == 0 and current_col == 0:
                return 0, 1
            if current_row < 0 or current_col < 0 or board[current_row][current_col] == "X":
                return -float("inf"), -float("inf")

            # This parameter is not used internally, but passed to recursive calls.
            # The actual path count is calculated below.
            current_paths_accumulator = 0

            cell_char = board[current_row][current_col]
            current_cell_value = 0
            if cell_char != "S":
                current_cell_value = int(cell_char)

            # Explore paths from three possible directions: up, left, and diagonal-up-left
            score_from_up, paths_from_up = calculate_max_score_and_paths(current_row - 1, current_col, dummy_path_param + 1)
            score_from_left, paths_from_left = calculate_max_score_and_paths(current_row, current_col - 1, dummy_path_param + 1)
            score_from_diagonal, paths_from_diagonal = calculate_max_score_and_paths(current_row - 1, current_col - 1, dummy_path_param + 1)

            # Determine the maximum score achievable from any of the neighbor cells
            optimal_prev_score = max(score_from_up, score_from_left, score_from_diagonal)

            # Sum the number of paths that achieve this optimal previous score
            if optimal_prev_score == score_from_up:
                current_paths_accumulator += paths_from_up
            if optimal_prev_score == score_from_left:
                current_paths_accumulator += paths_from_left
            if optimal_prev_score == score_from_diagonal:
                current_paths_accumulator += paths_from_diagonal
            
            # Return the total score for the current cell and the accumulated path count
            return current_cell_value + optimal_prev_score, current_paths_accumulator

        MODULO_CONSTANT = 10**9 + 7
        
        # Start the DFS from the bottom-right corner (end point 'S')
        final_max_score, total_max_paths = calculate_max_score_and_paths(num_rows - 1, num_cols - 1, 0)

        # Handle cases where no valid path exists (score remains -infinity)
        if final_max_score == -float("inf") and total_max_paths == -float("inf"):
            return [0, 0]
        else:
            # Apply modulo to the results
            return [final_max_score % MODULO_CONSTANT, total_max_paths % MODULO_CONSTANT]