# LeetCode Daily Challenge
# Date: 2026-03-07
# Problem: Minimum Number of Flips to Make the Binary String Alternating
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

import math

class Solution:
    def minFlips(self, binary_string: str) -> int:
        string_length = len(binary_string)
        
        current_flips_for_pattern_A = 0
        current_flips_for_pattern_B = 0
        
        minimum_total_flips_result = math.inf
        
        iteration_index = 0
        loop_upper_bound = 2 * string_length
        
        while iteration_index < loop_upper_bound:
            current_character_value = int(binary_string[iteration_index % string_length])
            
            if current_character_value != (iteration_index % 2):
                current_flips_for_pattern_A += 1
            
            if current_character_value != ((iteration_index + 1) % 2):
                current_flips_for_pattern_B += 1
            
            if iteration_index >= string_length:
                leaving_char_original_index = iteration_index - string_length
                leaving_character_value = int(binary_string[leaving_char_original_index])
                
                if leaving_character_value != (leaving_char_original_index % 2):
                    current_flips_for_pattern_A -= 1
                
                if leaving_character_value != ((leaving_char_original_index + 1) % 2):
                    current_flips_for_pattern_B -= 1
            
            if iteration_index >= string_length - 1:
                minimum_total_flips_result = min(
                    minimum_total_flips_result,
                    current_flips_for_pattern_A,
                    current_flips_for_pattern_B
                )
            
            iteration_index += 1
            
        return minimum_total_flips_result