# LeetCode Daily Challenge
# Date: 2026-09-25
# Problem: #1096 Brace Expansion II
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

import itertools
from typing import List


class Solution:

    def braceExpansionII(self, expression: str) -> List[str]:
        sub_groups = [[]]
        nesting_depth = 0
        sub_start_idx = 0

        for char_idx, char in enumerate(expression):
            if char == "{":
                if nesting_depth == 0:
                    sub_start_idx = char_idx + 1
                nesting_depth += 1
            elif char == "}":
                nesting_depth -= 1
                if nesting_depth == 0:
                    sub_groups[-1].append(
                        self.braceExpansionII(
                            expression[sub_start_idx:char_idx]
                        )
                    )
            elif char == "," and nesting_depth == 0:
                sub_groups.append([])
            elif nesting_depth == 0:
                sub_groups[-1].append([char])

        unique_words = set()
        for group in sub_groups:
            unique_words |= set(map("".join, itertools.product(*group)))

        return sorted(unique_words)