# LeetCode Daily Challenge
# Date: 2026-06-07
# Problem: Create Binary Tree From Descriptions
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def createBinaryTree(self, descriptions: List[List[int]]) -> Optional[TreeNode]:
        # A collection to store the integer values of all nodes that are children in any description.
        # This set helps in identifying the eventual root node, which will not be present here.
        all_child_values = set()

        # A dictionary to map node integer values to their corresponding TreeNode objects.
        # This allows for efficient lookup and creation of nodes.
        node_value_to_object = {}

        # First iteration: Process each description to build the tree structure and identify all children.
        for description_tuple in descriptions:
            # Unpack the current description into its components: parent value, child value, and left/right indicator.
            parent_value, child_value, is_left_child_indicator = description_tuple

            # Ensure the parent node exists in our map. If not, create a new TreeNode for it.
            if parent_value not in node_value_to_object:
                node_value_to_object[parent_value] = TreeNode(parent_value)
            
            # Ensure the child node exists in our map. If not, create a new TreeNode for it.
            if child_value not in node_value_to_object:
                node_value_to_object[child_value] = TreeNode(child_value)

            # Retrieve the actual TreeNode objects for the current parent and child.
            current_parent_node_ref = node_value_to_object[parent_value]
            current_child_node_ref = node_value_to_object[child_value]

            # Link the child node to the parent's left or right pointer based on the indicator.
            if is_left_child_indicator == 1: # Assuming 1 means left child
                current_parent_node_ref.left = current_child_node_ref
            else: # 0 means right child
                current_parent_node_ref.right = current_child_node_ref
            
            # Add the child's value to our set of all child values.
            all_child_values.add(child_value)
        
        # Second iteration: Find the root of the entire binary tree.
        # The root is the unique node that is never specified as a child in any description.
        for entry_tuple in descriptions:
            # The first element of any description tuple is a parent's value.
            # This parent could potentially be the overall root of the tree.
            potential_root_identification = entry_tuple[0]

            # If this value is not present in our set of all_child_values, it must be the root.
            if potential_root_identification not in all_child_values:
                # Return the TreeNode object corresponding to this identified root value.
                return node_value_to_object[potential_root_identification]
        
        # This return statement should ideally not be reached if the input guarantees a valid tree with a single root.
        return None