# LeetCode Daily Challenge
# Date: 2026-05-10
# Problem: Maximum Number of Jumps to Reach the Last Index
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def maximumJumps(self, num_list: List[int], jump_range: int) -> int:
        num_elements = len(num_list)
        max_reach_at_index = [-1] * num_elements
        max_reach_at_index[0] = 0

        destination_index = 1
        while destination_index < num_elements:
            source_index = destination_index - 1
            while source_index >= 0:
                current_val = num_list[destination_index]
                previous_val = num_list[source_index]

                if abs(current_val - previous_val) <= jump_range:
                    if max_reach_at_index[source_index] != -1:
                        max_reach_at_index[destination_index] = max(max_reach_at_index[destination_index], max_reach_at_index[source_index] + 1)
                source_index -= 1
            destination_index += 1
        
        return max_reach_at_index[num_elements - 1]