# LeetCode Daily Challenge
# Date: 2026-07-18
# Problem: Find Greatest Common Divisor of Array
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def findGCD(self, number_collection: List[int]) -> int:
        
        def compute_gcd_recursive(operand_a: int, operand_b: int) -> int:
            # Base case for the Euclidean algorithm
            if operand_b == 0:
                return operand_a
            # Recursive step
            return compute_gcd_recursive(operand_b, operand_a % operand_b)

        # Determine the highest and lowest values from the input list
        maximum_element = max(number_collection)
        minimum_element = min(number_collection)
        
        # Calculate and return the GCD of the extreme values
        return compute_gcd_recursive(maximum_element, minimum_element)