# LeetCode Daily Challenge
# Date: 2026-09-15
# Problem: #2472 Maximum Number of Non-overlapping Palindrome Substrings
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def maxPalindromes(self, s: str, k: int) -> int:
        string_length = len(s)
        max_palindromes_dp = [0] * (string_length + 1)
        
        for current_idx in range(k, string_length + 1):
            max_palindromes_dp[current_idx] = max_palindromes_dp[current_idx - 1]
            for length_offset in range(k, k + 2):
                start_idx = current_idx - length_offset
                if start_idx < 0:
                    break
                if self.isPalindrome(s, start_idx, current_idx):
                    max_palindromes_dp[current_idx] = max(
                        max_palindromes_dp[current_idx], 
                        1 + max_palindromes_dp[start_idx]
                    )
                    
        return max_palindromes_dp[-1]
    
    def isPalindrome(self, s: str, start_idx: int, end_idx: int) -> bool:
        left_ptr, right_ptr = start_idx, end_idx - 1
        while left_ptr < right_ptr:
            if s[left_ptr] != s[right_ptr]:
                return False
            left_ptr += 1
            right_ptr -= 1
        return True