# LeetCode Daily Challenge
# Date: 2026-06-30
# Problem: Number of Substrings Containing All Three Characters
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def numberOfSubstrings(self, input_sequence: str) -> int:
        total_length = len(input_sequence)
        substring_counter = 0

        # Track the last seen index for each character 'a', 'b', 'c'
        last_a_occurrence = -1
        last_b_occurrence = -1
        last_c_occurrence = -1

        current_position = 0
        while current_position < total_length:
            character_at_current_position = input_sequence[current_position]

            if character_at_current_position == 'a':
                last_a_occurrence = current_position
            elif character_at_current_position == 'b':
                last_b_occurrence = current_position
            else:  # The character must be 'c'
                last_c_occurrence = current_position

            # Only if all three characters ('a', 'b', 'c') have been encountered at least once
            if last_a_occurrence != -1 and last_b_occurrence != -1 and last_c_occurrence != -1:
                # Find the earliest position among the last occurrences of 'a', 'b', and 'c'
                earliest_of_last_seen = min(last_a_occurrence, last_b_occurrence, last_c_occurrence)

                # The number of valid starting positions for substrings ending at current_position
                # is (earliest_of_last_seen + 1).
                # These are substrings starting from index 0 up to earliest_of_last_seen.
                substring_counter += earliest_of_last_seen + 1
            
            current_position += 1

        return substring_counter