# LeetCode Daily Challenge
# Date: 2026-08-23
# Problem: Sum Game
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def sumGame(self, num_string: str) -> bool:
        string_length = len(num_string)
        
        first_half_question_marks = 0
        first_half_digit_sum = 0
        
        current_idx_one = 0
        division_point = string_length // 2
        
        while current_idx_one < division_point:
            character_val = num_string[current_idx_one]
            if character_val == '?':
                first_half_question_marks += 1
            else:    
                first_half_digit_sum += int(character_val)
            current_idx_one += 1
            
        second_half_question_marks = 0
        second_half_digit_sum = 0
        
        current_idx_two = division_point
        while current_idx_two < string_length:
            character_val = num_string[current_idx_two]
            if character_val == '?':
                second_half_question_marks += 1
            else:    
                second_half_digit_sum += int(character_val)
            current_idx_two += 1
            
        total_sum_difference = first_half_digit_sum - second_half_digit_sum
        total_q_mark_difference = second_half_question_marks - first_half_question_marks
        
        bob_can_win_condition = (total_q_mark_difference % 2 == 0) and \
                                (total_q_mark_difference // 2 * 9 == total_sum_difference)
        
        return not bob_can_win_condition