# LeetCode Daily Challenge
# Date: 2026-03-16
# Problem: Get Biggest Three Rhombus Sums in a Grid
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import heapq
import itertools
from functools import lru_cache

class Solution:
    def getBiggestThree(self, input_grid):
        num_rows, num_cols = len(input_grid), len(input_grid[0])
        candidate_sums = [] # This will function as a min-heap to keep track of the top 3 distinct sums

        def maintain_top_three_distinct(current_heap, new_value):
            # Only add if the value is not already present
            if new_value not in current_heap:
                heapq.heappush(current_heap, new_value)
                # If more than 3 elements, remove the smallest one
                if len(current_heap) > 3:
                    heapq.heappop(current_heap)

        # First, consider all individual cell values as potential rhombus sums (for radius 0)
        for cell_value in itertools.chain(*input_grid):
            maintain_top_three_distinct(candidate_sums, cell_value)
        
        # Memoized recursive function to calculate diagonal prefix sums
        # col_coord refers to column index (i in original)
        # row_coord refers to row index (j in original)
        # direction_factor refers to dr (1 or -1)
        # dp(col, row, -1) sums values along (col,row), (col-1,row-1), (col-2,row-2)...
        # dp(col, row, 1) sums values along (col,row), (col-1,row+1), (col-2,row+2)...
        @lru_cache(None)
        def compute_diagonal_sum(col_coord, row_coord, direction_factor):
            # Base case: if coordinates are out of grid bounds, return 0
            if not (0 <= col_coord < num_cols and 0 <= row_coord < num_rows):
                return 0
            # Recursive step: sum current cell value with the diagonal sum of the previous cell
            return compute_diagonal_sum(col_coord - 1, row_coord + direction_factor, direction_factor) + input_grid[row_coord][col_coord]

        # Iterate through possible rhombus sizes (represented by 'extent')
        # extent is the "radius" from the center to a corner
        max_possible_extent = (1 + min(num_rows, num_cols)) // 2 
        
        current_extent = 1
        while current_extent < max_possible_extent:
            # Iterate through all possible center points (center_col, center_row) for the current extent
            center_col = current_extent
            while center_col < num_cols - current_extent:
                center_row = current_extent
                while center_row < num_rows - current_extent:
                    # Calculate sums of the four segments forming the rhombus perimeter
                    # The original solution's prefix sum logic: S(end_point) - S(point_before_start_of_segment)
                    # This ensures each cell on the perimeter is counted exactly once.

                    # Segment 1: Top-point to Right-point (diagonal with col increasing, row increasing)
                    # Uses compute_diagonal_sum with direction_factor = -1
                    segment_a_sum = compute_diagonal_sum(center_col + current_extent, center_row, -1) - \
                                    compute_diagonal_sum(center_col, center_row - current_extent, -1)
                    
                    # Segment 2: Right-point to Bottom-point (diagonal with col increasing, row increasing)
                    # Uses compute_diagonal_sum with direction_factor = -1
                    segment_b_sum = compute_diagonal_sum(center_col - 1, center_row + current_extent - 1, -1) - \
                                    compute_diagonal_sum(center_col - current_extent - 1, center_row - 1, -1)

                    # Segment 3: Bottom-point to Left-point (diagonal with col decreasing, row increasing)
                    # Uses compute_diagonal_sum with direction_factor = 1
                    segment_c_sum = compute_diagonal_sum(center_col, center_row - current_extent, 1) - \
                                    compute_diagonal_sum(center_col - current_extent, center_row, 1)

                    # Segment 4: Left-point to Top-point (diagonal with col decreasing, row increasing)
                    # Uses compute_diagonal_sum with direction_factor = 1
                    segment_d_sum = compute_diagonal_sum(center_col + current_extent - 1, center_row + 1, 1) - \
                                    compute_diagonal_sum(center_col - 1, center_row + current_extent + 1, 1)

                    # The total sum for the current rhombus perimeter
                    total_rhombus_perimeter_sum = segment_a_sum + segment_b_sum + segment_c_sum + segment_d_sum
                    
                    # Add this sum to our candidates
                    maintain_top_three_distinct(candidate_sums, total_rhombus_perimeter_sum)

                    center_row += 1
                center_col += 1
            current_extent += 1

        # The heap stores the 3 largest distinct sums. Sort in descending order for the final result.
        return sorted(candidate_sums, reverse=True)