# LeetCode Daily Challenge
# Date: 2026-05-05
# Problem: Rotate List
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def rotateRight(self, initial_head, rotation_amount):
        """
        :type head: ListNode
        :type k: int
        :rtype: ListNode
        """
        
        # Handle cases for an empty list
        if initial_head is None:
            return None
        
        # Handle cases for a list with a single node
        if initial_head.next is None:
            return initial_head
            
        # First phase: Traverse the list to determine its total number of nodes
        # and identify the current tail node.
        current_node_for_length = initial_head
        total_nodes = 1
        
        while current_node_for_length.next is not None:
            current_node_for_length = current_node_for_length.next
            total_nodes += 1
        
        # Calculate the actual number of rotations needed,
        # considering that k might be larger than the list length.
        actual_rotations_needed = rotation_amount % total_nodes
        
        # If no rotation is effectively required, return the original head.
        if rotation_amount == 0 or actual_rotations_needed == 0:
            return initial_head
        
        # Second phase: Use two pointers to find the new tail and new head.
        # The 'forward_mover' will lead by 'actual_rotations_needed' steps.
        forward_mover = initial_head
        backward_mover = initial_head
        
        # Advance 'forward_mover' by the calculated number of steps.
        step_counter = 0
        while step_counter < actual_rotations_needed:
            forward_mover = forward_mover.next
            step_counter += 1
        
        # Now, move both pointers simultaneously until 'forward_mover' reaches the last node.
        # At this point, 'backward_mover' will be positioned just before the new head.
        while forward_mover.next is not None:
            backward_mover = backward_mover.next
            forward_mover = forward_mover.next
        
        # Third phase: Perform the actual re-linking to rotate the list.
        # 1. The node immediately after 'backward_mover' becomes the start of the new list.
        new_list_start = backward_mover.next
        
        # 2. Break the link from 'backward_mover', making it the new tail of the list.
        backward_mover.next = None
        
        # 3. Connect the original tail (which 'forward_mover' points to) to the original head.
        forward_mover.next = initial_head
        
        # Return the new head of the rotated list.
        return new_list_start