# LeetCode Daily Challenge
# Date: 2026-05-17
# Problem: Jump Game III
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def canReach(self, number_array, current_index):
        array_size = len(number_array)

        # Check for invalid index (out of bounds) or if this position has already been visited
        if current_index < 0 or current_index >= array_size or number_array[current_index] < 0:
            return False

        # Mark the current position as visited by negating its value.
        # If the original value was 0, it remains 0.
        number_array[current_index] = -number_array[current_index]

        # If the value at this position is 0 (meaning it was originally 0), we've found a target.
        # Otherwise, recursively explore both possible jump directions using the now-negated value.
        # (current_index + negative_value) effectively means (current_index - original_absolute_value)
        # (current_index - negative_value) effectively means (current_index + original_absolute_value)
        return number_array[current_index] == 0 or \
               self.canReach(number_array, current_index + number_array[current_index]) or \
               self.canReach(number_array, current_index - number_array[current_index])