# LeetCode Daily Challenge
# Date: 2026-05-14
# Problem: Check if Array is Good
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from typing import List

class Solution:
    def isGood(self, input_numbers: List[int]) -> bool:
        
        current_length = len(input_numbers)

        # A "good" array of length k should be [1, 2, ..., k-1, k-1]
        # So, for an input of 'current_length', the target is [1, 2, ..., current_length-1, current_length-1]
        
        # Generate the ascending sequence from 1 up to current_length-1
        expected_initial_segment = [num_val for num_val in range(1, current_length)]
        
        # The last element is a duplicate of current_length-1
        last_repeated_element = [current_length - 1]
        
        # Combine to form the complete expected good array
        target_good_sequence = expected_initial_segment + last_repeated_element
        
        # Sort the input array and compare with the target good sequence
        return sorted(input_numbers) == target_good_sequence