# LeetCode Daily Challenge
# Date: 2026-05-16
# Problem: Find Minimum in Rotated Sorted Array II
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class ArrayMinLocator:
    def locate_minimum_value(self, input_list):
        left_pointer, right_pointer = 0, len(input_list) - 1
        while left_pointer < right_pointer:
            center_index = left_pointer + (right_pointer - left_pointer) // 2
            if input_list[center_index] > input_list[right_pointer]:
                left_pointer = center_index + 1
            else:
                right_pointer = center_index
        return input_list[left_pointer]

class RotatedArrayMinFinder:
    def get_min_with_duplicates(self, data_elements):
        start_index, end_index = 0, len(data_elements) - 1
        while start_index < end_index:
            pivot_point = start_index + (end_index - start_index) // 2
            if data_elements[pivot_point] > data_elements[end_index]:
                start_index = pivot_point + 1
            elif data_elements[pivot_point] < data_elements[end_index]:
                end_index = pivot_point
            else: 
                end_index -= 1
        return data_elements[start_index]