# LeetCode Daily Challenge
# Date: 2026-10-09
# Problem: #1541 Minimum Insertions to Balance a Parentheses String
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def minInsertions(self, s: str) -> int:
        
        s = s.replace(\'))\', \'}\')
        missing_brackets = 0
        required_closed = 0

        for c in s:

            # Open Bracket Condition
            if c == \'(\':
                required_closed += 2
              
            # Closed Bracket Condition  
            else:
			
                # Case: \')\' 
                # Requires additional \')\' 
                if c == \')\': 
                    missing_brackets += 1

                # Case: Matching ( for ) or ))
                if required_closed:
                    required_closed -= 2


                # Case: Unmatched ) or ))
                # Need to insert ( to balance string
                else:
                    missing_brackets += 1

        return missing_brackets + required_closed