# LeetCode Daily Challenge
# Date: 2026-08-28
# Problem: Lexicographically Smallest Palindromic Permutation Greater Than Target
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class PalindromeGenerator:
    def findLexicographicalPalindrome(self, input_string: str, target_string: str) -> str:
        alphabet_size = 26
        ascii_a_code = ord('a')
        
        # 1. Count character frequencies in the input string
        char_frequencies = [0] * alphabet_size
        for current_input_char in input_string:
            char_frequencies[ord(current_input_char) - ascii_a_code] += 1

        # 2. Identify characters with odd frequencies
        indices_with_odd_counts = []
        for char_index_val, frequency_val in enumerate(char_frequencies):
            if (frequency_val % 2) != 0:
                indices_with_odd_counts.append(char_index_val)
        
        # If more than one character has an odd frequency, a palindrome cannot be formed
        if len(indices_with_odd_counts) > 1:
            return ""

        # 3. Determine the middle character of the palindrome (if any)
        middle_character_component = ""
        if indices_with_odd_counts:
            middle_character_component = chr(indices_with_odd_counts[0] + ascii_a_code)
        
        # Halve the frequencies for constructing the left half of the palindrome
        half_char_frequencies = [freq_val // 2 for freq_val in char_frequencies]

        # 4. Determine the target's left half segment
        input_string_half_length = len(input_string) // 2
        target_prefix_segment = target_string[:input_string_half_length]

        # 5. Nested helper function to construct the full palindrome from its left half
        def assemble_full_palindrome(left_half_string_segment: str) -> str:
            return left_half_string_segment + middle_character_component + left_half_string_segment[::-1]

        # 6. Greedily match the target's left half as much as possible
        current_left_prefix_chars = []
        remaining_available_char_counts = list(half_char_frequencies) # Create a mutable copy
        
        current_prefix_pos = 0
        while current_prefix_pos < len(target_prefix_segment):
            target_char_code = ord(target_prefix_segment[current_prefix_pos]) - ascii_a_code
            
            if remaining_available_char_counts[target_char_code] == 0:
                break # Cannot match this character, stop matching prefix
            
            current_left_prefix_chars.append(target_prefix_segment[current_prefix_pos])
            remaining_available_char_counts[target_char_code] -= 1
            current_prefix_pos += 1
        
        # If the prefix matching loop completed entirely (no break), check the candidate
        if current_prefix_pos == len(target_prefix_segment):
            potential_palindrome_candidate = assemble_full_palindrome("".join(current_left_prefix_chars))
            if potential_palindrome_candidate > target_string:
                return potential_palindrome_candidate

        # 7. Backtrack and find the next lexicographically larger palindrome
        # This loop continues until a valid palindrome is found or no more options exist
        while True:
            current_prefix_length = len(current_left_prefix_chars)

            # Try to extend the current prefix by finding a character larger than target_prefix_segment[current_prefix_length]
            if current_prefix_length < len(target_prefix_segment):
                char_code_at_target_position = ord(target_prefix_segment[current_prefix_length]) - ascii_a_code
                
                next_possible_char_code = char_code_at_target_position + 1
                while next_possible_char_code < alphabet_size:
                    if remaining_available_char_counts[next_possible_char_code] > 0:
                        remaining_available_char_counts[next_possible_char_code] -= 1
                        current_left_prefix_chars.append(chr(next_possible_char_code + ascii_a_code))
                        
                        # Fill the rest of the left half with the smallest available characters
                        for fill_code in range(alphabet_size):
                            for _ in range(remaining_available_char_counts[fill_code]):
                                current_left_prefix_chars.append(chr(fill_code + ascii_a_code))
                        
                        return assemble_full_palindrome("".join(current_left_prefix_chars))
                    
                    next_possible_char_code += 1

            # If no suitable character was found to extend the prefix, or if we are beyond target prefix length
            # Backtrack by removing the last character from the prefix
            if not current_left_prefix_chars: # If the prefix is empty, no solution can be formed
                return ""

            removed_char_code_from_prefix = ord(current_left_prefix_chars.pop()) - ascii_a_code
            remaining_available_char_counts[removed_char_code_from_prefix] += 1 # Restore its count for future use