# LeetCode Daily Challenge
# Date: 2026-09-17
# Problem: #1477 Find Two Non-overlapping Sub-arrays Each With Target Sum
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

import itertools
import math
from typing import List

class Solution:
    def minSumOfLengths(self, arr: List[int], target: int) -> int:
        prefix_sum_indices = {0: -1}
        min_len_ending_at_or_before = [math.inf] * len(arr)
        min_total_sum_len = math.inf
        current_min_len = math.inf
        
        for current_idx, running_sum in enumerate(itertools.accumulate(arr)):
            target_sum = running_sum - target
            if target_sum in prefix_sum_indices:
                prev_idx = prefix_sum_indices[target_sum]
                if prev_idx > -1:
                    min_total_sum_len = min(
                        min_total_sum_len, 
                        current_idx - prev_idx + min_len_ending_at_or_before[prev_idx]
                    )
                current_min_len = min(current_min_len, current_idx - prev_idx)
                
            min_len_ending_at_or_before[current_idx] = current_min_len
            prefix_sum_indices[running_sum] = current_idx
            
        return -1 if min_total_sum_len == math.inf else min_total_sum_len