# LeetCode Daily Challenge
# Date: 2026-10-10
# Problem: #2333 Minimum Sum of Squared Difference
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

from heapq import heapify, heappop, heappush
from typing import List

class Solution:
    def minSumSquareDiff(self, nums1: List[int], nums2: List[int], k1: int, k2: int) -> int:
        diff_max_heap = [-abs(num_a - num_b) for num_a, num_b in zip(nums1, nums2)]
        total_diff_sum = -sum(diff_max_heap)
        
        if k1 + k2 >= total_diff_sum:
            return 0
            
        remaining_operations = k1 + k2
        heapify(diff_max_heap)
        element_count = len(nums1)
        
        while remaining_operations > 0:
            current_diff = -heappop(diff_max_heap)
            reduction_step = max(remaining_operations // element_count, 1) if diff_max_heap else remaining_operations
            current_diff -= reduction_step
            heappush(diff_max_heap, -current_diff)
            remaining_operations -= reduction_step
            
        return sum(pow(diff_val, 2) for diff_val in diff_max_heap)