# LeetCode Daily Challenge
# Date: 2026-08-16
# Problem: Stone Game IX
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def stoneGameIX(self, stones: List[int]) -> bool:
        from collections import Counter

        # Generate a list of remainders when each stone's value is divided by 3
        remainder_list = [val % 3 for val in stones]
        
        # Count occurrences of each remainder (0, 1, 2)
        remainder_frequency = Counter(remainder_list)

        # Extract counts for easier access and slightly different variable names
        freq_zero = remainder_frequency[0]
        freq_one = remainder_frequency[1]
        freq_two = remainder_frequency[2]

        # Scenario 1: Even count of stones with remainder 0
        if not (freq_zero % 2): # Using 'not (x % 2)' for even check
            # Alice wins if and only if there are both remainder 1 and remainder 2 stones available
            return freq_one > 0 and freq_two > 0
        # Scenario 2: Odd count of stones with remainder 0
        else:
            # Alice wins if and only if the absolute difference between counts of remainder 1 and 2 is greater than 2
            return abs(freq_one - freq_two) > 2