# LeetCode Daily Challenge
# Date: 2026-07-20
# Problem: Shift 2D Grid
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def shiftGrid(self, input_matrix: List[List[int]], steps: int) -> List[List[int]]:
        num_rows = len(input_matrix)
        num_columns = len(input_matrix[0])

        resultant_matrix = [ [0] * num_columns for _init_row in range(num_rows) ]

        current_column_index = 0
        while current_column_index < num_columns:
            
            target_column_index = (current_column_index + steps) % num_columns
            
            current_row_index = 0
            while current_row_index < num_rows:
                
                target_row_index = (current_row_index + (current_column_index + steps) // num_columns) % num_rows
                
                resultant_matrix[target_row_index][target_column_index] = input_matrix[current_row_index][current_column_index]
                
                current_row_index += 1
            current_column_index += 1
            
        return resultant_matrix