# LeetCode Daily Challenge
# Date: 2026-09-18
# Problem: #1520 Maximum Number of Non-Overlapping Substrings
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

from bisect import bisect_left
from typing import List

class Solution:
    def maxNumOfSubstrings(self, s: str) -> List[str]:
        char_indices = {}
        for idx, char in enumerate(s): 
            char_indices.setdefault(char, []).append(idx)
        
        def expand_range(left_bound, right_bound): 
            for char, indices in char_indices.items(): 
                idx_left = bisect_left(indices, left_bound)
                idx_right = bisect_left(indices, right_bound)
                if idx_left < idx_right and (indices[0] < left_bound or right_bound < indices[-1]): 
                    left_bound = min(left_bound, indices[0])
                    right_bound = max(right_bound, indices[-1])
                    left_bound, right_bound = expand_range(left_bound, right_bound)
            return left_bound, right_bound
        
        interval_set = set()
        for char, indices in char_indices.items(): 
            interval_set.add(expand_range(indices[0], indices[-1]))
        
        result = [] 
        last_end = -1 
        for left_bound, right_bound in sorted(interval_set, key=lambda interval: interval[1]): 
            if last_end < left_bound: 
                result.append(s[left_bound:right_bound+1])
                last_end = right_bound 
        return result