# LeetCode Daily Challenge
# Date: 2026-09-28
# Problem: #1614 Maximum Nesting Depth of the Parentheses
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def maxDepth(self, s: str) -> int:
        max_nesting_depth = 0
        current_nesting_depth = 0
        
        for character in s:
            if character == '(':
                current_nesting_depth += 1
                max_nesting_depth = max(max_nesting_depth, current_nesting_depth)
            elif character == ')':
                current_nesting_depth -= 1
                
        return max_nesting_depth