# LeetCode Daily Challenge
# Date: 2026-08-29
# Problem: Make Lexicographically Smallest Array by Swapping Elements
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from typing import List

class Solution:
    def lexicographicallySmallestArray(self, input_array: List[int], max_diff_allowed: int) -> List[int]:
        array_length = len(input_array)
        val_idx_pairs = []

        # Populate list with (value, original_index) tuples
        current_idx = 0
        while current_idx < array_length:
            val_idx_pairs.append((input_array[current_idx], current_idx))
            current_idx += 1

        # Sort the pairs based on their values
        val_idx_pairs.sort(key=lambda pair_item: pair_item[0])

        # Group elements that can be swapped (difference <= max_diff_allowed)
        group_containers = [[val_idx_pairs[0]]]
        current_idx = 1
        while current_idx < array_length:
            current_val, _ = val_idx_pairs[current_idx]
            previous_val, _ = val_idx_pairs[current_idx - 1]
            if current_val - previous_val <= max_diff_allowed:
                group_containers[-1].append(val_idx_pairs[current_idx])
            else:
                group_containers.append([val_idx_pairs[current_idx]])
            current_idx += 1

        # For each group, sort the original indices and place the values
        # from the sorted group into those sorted original indices.
        group_iterator_idx = 0
        while group_iterator_idx < len(group_containers):
            current_component = group_containers[group_iterator_idx]
            original_indices_of_component = []
            
            # Extract original indices
            sub_idx = 0
            while sub_idx < len(current_component):
                _, original_position = current_component[sub_idx]
                original_indices_of_component.append(original_position)
                sub_idx += 1
            
            # Sort the original indices to get their target positions
            original_indices_of_component.sort()

            # Place the values from the sorted group into the sorted original positions
            placement_idx = 0
            while placement_idx < len(original_indices_of_component):
                target_original_index = original_indices_of_component[placement_idx]
                value_to_place = current_component[placement_idx][0]
                input_array[target_original_index] = value_to_place
                placement_idx += 1
            
            group_iterator_idx += 1

        return input_array