# LeetCode Daily Challenge
# Date: 2026-05-12
# Problem: Minimum Initial Energy to Finish Tasks
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def minimumEffort(self, job_items: List[List[int]]) -> int:
        job_items.sort(key=lambda item_data: item_data[0] - item_data[1])
        total_energy_expended = 0
        current_energy_level = 0
        
        for actual_consumption, minimum_start_level in job_items:
            if minimum_start_level > current_energy_level:
                total_energy_expended += (minimum_start_level - current_energy_level)
                current_energy_level = minimum_start_level
            current_energy_level -= actual_consumption
            
        return total_energy_expended