# LeetCode Daily Challenge
# Date: 2026-07-26
# Problem: Maximum Product of Three Numbers
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def maximumProduct(self, input_numbers: List[int]) -> int:
        current_two_minima = [float('inf'), float('inf')]
        current_three_maxima = [float('-inf'), float('-inf'), float('-inf')]

        for element_value in input_numbers:
            if element_value <= current_two_minima[0]:
                current_two_minima[0] = element_value
                current_two_minima.sort(reverse=True)
            
            if element_value >= current_three_maxima[0]:
                current_three_maxima[0] = element_value
                current_three_maxima.sort()
        
        return max(current_two_minima[0] * current_two_minima[1] * current_three_maxima[2],
                   current_three_maxima[0] * current_three_maxima[1] * current_three_maxima[2])