# LeetCode Daily Challenge
# Date: 2026-04-04
# Problem: Decode the Slanted Ciphertext
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def decodeCiphertext(self, cipher_input: str, num_matrix_rows: int) -> str:
        total_input_length = len(cipher_input)
        num_grid_columns = total_input_length // num_matrix_rows
        result_message = ""

        current_column_start = 0
        while current_column_start < num_grid_columns:
            diagonal_position = current_column_start
            while diagonal_position < total_input_length:
                result_message += cipher_input[diagonal_position]
                diagonal_position += num_grid_columns + 1
            current_column_start += 1
        
        return result_message.rstrip()