# LeetCode Daily Challenge
# Date: 2026-08-08
# Problem: Find the Lexicographically Smallest Valid Sequence
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def __init__(self):
        self.visited_states = set() # Stores (source_index, pattern_index, single_char_skip_token) for states that did not lead to a full match

    def match_words_recursively(self, source_index, pattern_index, single_char_skip_token, source_text, target_pattern, matched_segment_indices):
        # Termination condition: If the entire target_pattern has been successfully matched
        if pattern_index >= len(target_pattern):
            return True
        # Termination condition: If the source_text is exhausted before the target_pattern
        if source_index >= len(source_text):
            return False

        # Memoization check: If this specific state has been evaluated before and found to be a dead end
        state_identifier = (source_index, pattern_index, single_char_skip_token)
        if state_identifier in self.visited_states:
            return False

        # Variable to track if any path from this state leads to a successful overall match
        found_valid_path = False

        # Scenario 1: Direct character match between current characters of source_text and target_pattern
        if source_text[source_index] == target_pattern[pattern_index]:
            found_valid_path = self.match_words_recursively(
                source_index + 1, pattern_index + 1, single_char_skip_token,
                source_text, target_pattern, matched_segment_indices
            )
            if found_valid_path:
                matched_segment_indices.append(source_index) # Record the index from source_text
            return found_valid_path
        else:
            # Scenario 2: Current characters do not match
            # Option A: Attempt to use the special single character skip token if available
            if single_char_skip_token > 0: # A value of 1 means the token is available, 0 means it has been used
                found_valid_path = self.match_words_recursively(
                    source_index + 1, pattern_index + 1, 0, # Consume the skip token by setting its status to 0
                    source_text, target_pattern, matched_segment_indices
                )
                if found_valid_path:
                    matched_segment_indices.append(source_index) # This index is considered 'matched' by the skip token
                    return True # Successfully found a path using the skip token

            # Option B: Search for the next occurrence of target_pattern[pattern_index] within source_text
            # This 'current_source_seeker' variable is used to scan ahead in source_text
            current_source_seeker = source_index
            while current_source_seeker < len(source_text) and source_text[current_source_seeker] != target_pattern[pattern_index]:
                current_source_seeker += 1

            # If a matching character was found in source_text
            if current_source_seeker < len(source_text):
                # Recursively try to match the rest of the pattern from this new position
                found_valid_path = self.match_words_recursively(
                    current_source_seeker + 1, pattern_index + 1, single_char_skip_token,
                    source_text, target_pattern, matched_segment_indices
                )
                if found_valid_path:
                    matched_segment_indices.append(current_source_seeker) # Record the index where the match occurred
                    return True # Successfully found a path by skipping characters

        # If after exploring all possibilities from this state, no valid path was found, memoize it as a failure
        self.visited_states.add(state_identifier)
        return found_valid_path

    def find_sequence_matches(self, primary_word_str, secondary_word_str):
        self.visited_states = set() # Ensure memoization cache is clean for each new test case
        final_match_locations = []

        # Initiate the recursive matching process from the beginning of both strings,
        # with the single character skip token initially available (value 1)
        if self.match_words_recursively(0, 0, 1, primary_word_str, secondary_word_str, final_match_locations):
            final_match_locations.reverse() # The indices were collected in reverse order during recursion
            # Final verification: The number of collected indices must exactly match the length of the target pattern
            if len(final_match_locations) == len(secondary_word_str):
                return final_match_locations
        
        # If no valid sequence could be constructed or the final conditions were not met, return an empty list
        return []