# LeetCode Daily Challenge
# Date: 2026-04-23
# Problem: Sum of Distances
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def get_index_distances(self, input_numbers: list[int]) -> list[int]:
        data_length = len(input_numbers)
        result_distances = [0] * data_length
        index_mapping = {}

        idx_counter = 0
        while idx_counter < data_length:
            current_value = input_numbers[idx_counter]
            if current_value not in index_mapping:
                index_mapping[current_value] = []
            index_mapping[current_value].append(idx_counter)
            idx_counter += 1

        for number_key, indices_occurrence_list in index_mapping.items():
            total_sum_of_all_indices = sum(indices_occurrence_list)
            
            prefix_sum_tracker = 0
            list_position = 0
            count_of_indices_for_key = len(indices_occurrence_list)

            while list_position < count_of_indices_for_key:
                current_position_index = indices_occurrence_list[list_position]
                
                # Calculate sum of indices appearing AFTER the current one
                # This is equivalent to total_sum - prefix_sum - current_position_index
                remaining_sum_of_indices = total_sum_of_all_indices - prefix_sum_tracker - current_position_index
                
                # Contribution from elements to the left (smaller indices in the list)
                # (current_position_index - idx_j) for j < list_position
                # Sum = list_position * current_position_index - sum(idx_j for j < list_position)
                result_distances[current_position_index] += current_position_index * list_position
                result_distances[current_position_index] -= prefix_sum_tracker
                
                # Contribution from elements to the right (larger indices in the list)
                # (idx_j - current_position_index) for j > list_position
                # Sum = sum(idx_j for j > list_position) - (count_after) * current_position_index
                elements_after_current = count_of_indices_for_key - list_position - 1
                result_distances[current_position_index] += remaining_sum_of_indices
                result_distances[current_position_index] -= current_position_index * elements_after_current
                
                prefix_sum_tracker += current_position_index
                list_position += 1
                
        return result_distances