# LeetCode Daily Challenge
# Date: 2026-09-02
# Problem: #3875 Construct Uniform Parity Array I
# Language: python
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def checkUniformParity(self, nums1: List[int]) -> bool:
        total_elements = len(nums1)
        even_count = 0
        odd_count = 0
        initial_odd_index = -1

        for idx in range(total_elements):
            if nums1[idx] % 2 == 0:
                even_count += 1
            else:
                odd_count += 1
                if initial_odd_index == -1:
                    initial_odd_index = idx

        if even_count == 0 or odd_count == 0:
            return True

        pivot_value = nums1[initial_odd_index]
        transformed_nums = [0] * total_elements

        for idx in range(total_elements):
            if nums1[idx] % 2 == 1:
                transformed_nums[idx] = nums1[idx]
            else:
                transformed_nums[idx] = nums1[idx] - pivot_value

        return True