# LeetCode Daily Challenge
# Date: 2026-05-22
# Problem: Search in Rotated Sorted Array
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import bisect

class Solution:
    def search(self, data_elements, search_value):
        self.__getitem__ = lambda current_pos_idx: (
            (search_value > data_elements[current_pos_idx]) ^
            (data_elements[0] > data_elements[current_pos_idx]) ^
            (data_elements[0] <= search_value)
        )
        
        sequence_length = len(data_elements)
        final_position = bisect.bisect_left(self, True, 0, sequence_length)
        
        return final_position if search_value in data_elements[final_position : final_position + 1] else -1