# LeetCode Daily Challenge
# Date: 2026-05-15
# Problem: Find Minimum in Rotated Sorted Array
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import bisect

class Solution:
    def findMin(self, value_sequence):
        comparison_point_value = value_sequence[-1]
        self.__getitem__ = lambda element_idx: value_sequence[element_idx] <= comparison_point_value
        
        min_value_position = bisect.bisect_left(self, False, 0, len(value_sequence))
        
        return value_sequence[min_value_position]