# LeetCode Daily Challenge
# Date: 2026-09-19
# Problem: #1401 Circle and Rectangle Overlapping
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def checkOverlap(self, radius: int, xCenter: int, yCenter: int, x1: int, y1: int, x2: int, y2: int) -> bool:
        clamped_x = max(x1, min(x2, xCenter))
        clamped_y = max(y1, min(y2, yCenter))
        
        diff_x = clamped_x - xCenter
        diff_y = clamped_y - yCenter
        
        return diff_x ** 2 + diff_y ** 2 <= radius ** 2