# LeetCode Daily Challenge
# Date: 2026-05-04
# Problem: Rotate Image
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution(object):
    def rotate(self, matrix):
        """
        :type matrix: List[List[int]]
        :rtype: None Do not return anything, modify matrix in-place instead.
        """
        side_length = len(matrix)

        # Step 1: Transpose the matrix (swap elements across the main diagonal)
        row_counter = 0
        while row_counter < side_length:
            column_counter = 0
            while column_counter < side_length:
                if row_counter < column_counter:
                    # Perform the swap for elements where row index is less than column index
                    matrix[row_counter][column_counter], matrix[column_counter][row_counter] = \
                        matrix[column_counter][row_counter], matrix[row_counter][column_counter]
                column_counter += 1
            row_counter += 1

        # Step 2: Reverse each row of the transposed matrix
        row_index_to_reverse = 0
        while row_index_to_reverse < side_length:
            matrix[row_index_to_reverse].reverse()
            row_index_to_reverse += 1