# LeetCode Daily Challenge
# Date: 2026-09-10
# Problem: #2265 Count Nodes Equal to Average of Subtree
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def averageOfSubtree(self, root: Optional[TreeNode]) -> int:
        matched_count = 0
        
        def calculate_subtree_metrics(current_node):
            nonlocal matched_count
            
            if not current_node:
                return 0, 0
            
            left_total_sum, left_node_count = calculate_subtree_metrics(current_node.left)
            right_total_sum, right_node_count = calculate_subtree_metrics(current_node.right)
            
            accumulated_sum = current_node.val + left_total_sum + right_total_sum
            accumulated_count = 1 + left_node_count + right_node_count
            
            if accumulated_sum // accumulated_count == current_node.val:
                matched_count += 1
            
            return accumulated_sum, accumulated_count
        
        calculate_subtree_metrics(root)
        
        return matched_count