# LeetCode Daily Challenge
# Date: 2026-08-06
# Problem: Smallest Divisible Digit Product I
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def _calculate_product_of_digits(self, input_number: int) -> int:
        product_result = 1
        temp_number = input_number
        while temp_number > 0:
            last_digit = temp_number % 10
            product_result *= last_digit
            temp_number //= 10
        return product_result

    def smallestNumber(self, start_value: int, target_mod: int) -> int:
        current_iter_val = start_value
        upper_bound = start_value + 10

        while current_iter_val < upper_bound:
            if self._calculate_product_of_digits(current_iter_val) % target_mod == 0:
                return current_iter_val
            current_iter_val += 1