# LeetCode Daily Challenge
# Date: 2026-05-27
# Problem: Count the Number of Special Characters II
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:\n    def numberOfSpecialChars(self, word: str, ans = 0) -> int:\n        \n        for ch, CH in zip(ascii_lowercase, ascii_uppercase):\n\n            if ch not in word or CH not in word: continue\n  \n            ans+= word.rfind(ch) < word.find(CH)\n\n        return ans\n```\n[https://leetcode.com/problems/count-the-number-of-special-characters-ii/submissions/1238386975/](https://leetcode.com/problems/count-the-number-of-special-characters-ii/submissions/1238386975/)\n\nI could be wrong, but I think that time complexity is *O*(*N*) and space complexity is *O*(1), in which *N* ~ `len(word)`.