# LeetCode Daily Challenge
# Date: 2026-08-01
# Problem: Predict the Winner
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def PredictTheWinner(self, score_sequence):
        """
        Determines if the first player can win the game.
        :type score_sequence: List[int]
        :rtype: bool
        """
        memoization_cache = {}

        def calculate_max_score_difference(left_bound, right_bound):
            position_key = (left_bound, right_bound)

            if position_key not in memoization_cache:
                if left_bound == right_bound:
                    return score_sequence[left_bound]
                
                # Player 1 chooses score_sequence[left_bound] or score_sequence[right_bound]
                # The opponent then tries to maximize their score, which for Player 1 means minimizing the opponent's score,
                # effectively subtracting the opponent's optimal play from Player 1's choice.
                pick_left_value = score_sequence[left_bound] - calculate_max_score_difference(left_bound + 1, right_bound)
                pick_right_value = score_sequence[right_bound] - calculate_max_score_difference(left_bound, right_bound - 1)
                
                memoization_cache[position_key] = max(pick_left_value, pick_right_value)
            
            return memoization_cache[position_key]

        # The first player wins if their score difference (Player1_Score - Player2_Score) is non-negative
        initial_left_index = 0
        initial_right_index = len(score_sequence) - 1
        
        return calculate_max_score_difference(initial_left_index, initial_right_index) >= 0