# LeetCode Daily Challenge
# Date: 2026-09-26
# Problem: #1807 Evaluate the Bracket Pairs of a String
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def evaluate(self, s: str, knowledge: List[List[str]]) -> str:
        lookup_map = {pair[0]: pair[1] for pair in knowledge}
        char_stack = []
        
        for current_char in s:
            if current_char != ')':
                char_stack.append(current_char)
            else:
                key_chars = []
                while char_stack[-1] != '(':
                    key_chars.append(char_stack.pop())
                char_stack.pop()
                
                lookup_key = ''.join(key_chars[::-1])
                char_stack.append(lookup_map.get(lookup_key, '?'))
                
        return ''.join(char_stack)