# LeetCode Daily Challenge
# Date: 2026-03-21
# Problem: Flip Square Submatrix Vertically
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def reverseSubmatrix(self, matrix_data: List[List[int]], start_row_idx: int, start_col_idx: int, submatrix_dim: int) -> List[List[int]]:
        grid_column_count = len(matrix_data[0])

        # Condition 1: Submatrix column dimension is less than or equal to half of the total grid width
        if submatrix_dim <= (grid_column_count + 1) // 2:
            row_pair_iterator = 0
            half_sub_dim_rows = submatrix_dim // 2 
            
            while row_pair_iterator < half_sub_dim_rows:
                # Calculate absolute row indices for the current pair
                current_upper_row_index = start_row_idx + row_pair_iterator
                current_lower_row_index = start_row_idx + submatrix_dim - 1 - row_pair_iterator
                
                # Get references to the actual row lists
                upper_row_elements = matrix_data[current_upper_row_index]
                lower_row_elements = matrix_data[current_lower_row_index]
                
                # Iterate through columns ONLY within the submatrix's column range
                column_iterator_inner = start_col_idx
                end_column_for_swap = start_col_idx + submatrix_dim
                while column_iterator_inner < end_column_for_swap:
                    # Swap individual elements
                    upper_row_elements[column_iterator_inner], lower_row_elements[column_iterator_inner] = \
                        lower_row_elements[column_iterator_inner], upper_row_elements[column_iterator_inner]
                    column_iterator_inner += 1
                
                row_pair_iterator += 1 
        
        # Condition 2: Submatrix column dimension is greater than half of the total grid width
        else:
            row_pair_iterator_else_branch = 0
            half_sub_dim_rows_else_branch = submatrix_dim // 2 
            
            while row_pair_iterator_else_branch < half_sub_dim_rows_else_branch:
                # Calculate absolute row indices for the current pair
                upper_absolute_row_index = start_row_idx + row_pair_iterator_else_branch
                lower_absolute_row_index = start_row_idx + submatrix_dim - 1 - row_pair_iterator_else_branch
                
                # Get references to the actual row lists
                current_upper_row_ref = matrix_data[upper_absolute_row_index]
                current_lower_row_ref = matrix_data[lower_absolute_row_index]
                
                # First column-wise swap loop: for columns BEFORE the submatrix region
                col_idx_before_submatrix = 0
                while col_idx_before_submatrix < start_col_idx:
                    current_upper_row_ref[col_idx_before_submatrix], current_lower_row_ref[col_idx_before_submatrix] = \
                        current_lower_row_ref[col_idx_before_submatrix], current_upper_row_ref[col_idx_before_submatrix]
                    col_idx_before_submatrix += 1
                
                # Second column-wise swap loop: for columns AFTER the submatrix region
                col_idx_after_submatrix = start_col_idx + submatrix_dim
                while col_idx_after_submatrix < grid_column_count:
                    current_upper_row_ref[col_idx_after_submatrix], current_lower_row_ref[col_idx_after_submatrix] = \
                        current_lower_row_ref[col_idx_after_submatrix], current_upper_row_ref[col_idx_after_submatrix]
                    col_idx_after_submatrix += 1
                
                # Crucially, swap the entire row references in the main matrix_data
                # This effectively swaps the *middle* part of the rows implicitly
                matrix_data[upper_absolute_row_index], matrix_data[lower_absolute_row_index] = \
                    matrix_data[lower_absolute_row_index], matrix_data[upper_absolute_row_index]
                
                row_pair_iterator_else_branch += 1 
                
        return matrix_data