# LeetCode Daily Challenge
# Date: 2026-08-31
# Problem: #2058 Find the Minimum and Maximum Number of Nodes Between Critical Points
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

from typing import List

# Assuming ListNode definition is available or implicitly handled by LeetCode environment.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next

class Solution:
    def nodesBetweenCriticalPoints(self, head: ListNode) -> List[int]:
        current_node_index = 0
        critical_point_indices = []
        previous_node_value = head.val

        while head.next:
            current_node_value = head.val
            next_node_value = head.next.val

            if (previous_node_value - current_node_value) * (current_node_value - next_node_value) < 0:
                critical_point_indices.append(current_node_index)

            previous_node_value = current_node_value
            head = head.next
            current_node_index += 1

        num_critical_points_found = len(critical_point_indices)

        if num_critical_points_found < 2:
            return [-1, -1]

        min_distance_between_critical_points = min(
            (critical_point_indices[i] - critical_point_indices[i-1]
             for i in range(1, num_critical_points_found))
        )

        max_distance_between_critical_points = critical_point_indices[-1] - critical_point_indices[0]

        return [min_distance_between_critical_points, max_distance_between_critical_points]