# LeetCode Daily Challenge
# Date: 2026-05-02
# Problem: Rotated Digits
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def count_good_numbers(self, upper_limit: int) -> int:
        total_valid_rotations = 0
        current_number_to_check = 1
        while current_number_to_check <= upper_limit:
            if self._verify_rotational_integrity(current_number_to_check):
                total_valid_rotations += 1
            current_number_to_check += 1
        return total_valid_rotations

    def _verify_rotational_integrity(self, candidate_number: int) -> bool:
        rotatable_and_changing_digits = {2, 5, 6, 9}
        disallowed_digits = {3, 4, 7}

        contains_a_changing_digit = False
        processing_number = candidate_number

        while processing_number > 0:
            current_digit_value = processing_number % 10
            if current_digit_value in disallowed_digits:
                return False
            if current_digit_value in rotatable_and_changing_digits:
                contains_a_changing_digit = True
            processing_number //= 10

        return contains_a_changing_digit