# LeetCode Daily Challenge
# Date: 2026-09-13
# Problem: #835 Image Overlap
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def largestOverlap(self, A: List[List[int]], B: List[List[int]]) -> int:
        coords_a = []
        coords_b = []
        offset_counts = collections.defaultdict(int)

        grid_rows = len(A)
        grid_cols = len(A[0])

        for row_idx in range(grid_rows):
            for col_idx in range(grid_cols):
                if A[row_idx][col_idx]:
                    coords_a.append((row_idx, col_idx))
                if B[row_idx][col_idx]:
                    coords_b.append((row_idx, col_idx))

        for point_a_row, point_a_col in coords_a:
            for point_b_row, point_b_col in coords_b:
                diff_vector = (point_b_row - point_a_row, point_b_col - point_a_col)
                offset_counts[diff_vector] += 1

        return max(offset_counts.values() or [0])