# LeetCode Daily Challenge
# Date: 2026-07-17
# Problem: Sorted GCD Pair Queries
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import collections
import bisect
from typing import List

class Solution:
    def gcdValues(self, nums: List[int], queries: List[int]) -> List[int]:
        
        highest_val = max(nums)
        
        value_counts = collections.defaultdict(int)
        idx_n = 0
        num_elements = len(nums)
        while idx_n < num_elements:
            value_counts[nums[idx_n]] += 1
            idx_n += 1

        total_pairs_for_divisor = [0] * (highest_val + 1)

        current_divisor = highest_val
        while current_divisor > 0:
            multiples_count = 0
            
            multiple_val = current_divisor
            while multiple_val <= highest_val:
                multiples_count += value_counts[multiple_val]
                multiple_val += current_divisor

            total_pairs_for_divisor[current_divisor] = multiples_count * (multiples_count - 1) // 2

            multiple_val = 2 * current_divisor
            while multiple_val <= highest_val:
                total_pairs_for_divisor[current_divisor] -= total_pairs_for_divisor[multiple_val]
                multiple_val += current_divisor
            
            current_divisor -= 1

        cumulative_pair_sums = [0] * (highest_val + 1)
        current_total = 0
        
        current_idx = 1
        while current_idx <= highest_val:
            current_total += total_pairs_for_divisor[current_idx]
            cumulative_pair_sums[current_idx] = current_total
            current_idx += 1

        output_list = []
        idx_q = 0
        num_queries = len(queries)
        while idx_q < num_queries:
            query_val = queries[idx_q]
            output_list.append(bisect.bisect_right(cumulative_pair_sums, query_val))
            idx_q += 1

        return output_list