# LeetCode Daily Challenge
# Date: 2026-04-12
# Problem: Minimum Distance to Type a Word Using Two Fingers
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    _KEYBOARD_COLUMNS = 6
    _UNPLACED_FINGER_INDEX = 26

    def _determine_key_travel_cost(self, starting_key: int, ending_key: int) -> int:
        if starting_key == self._UNPLACED_FINGER_INDEX:
            return 0

        start_row_coord = starting_key // self._KEYBOARD_COLUMNS
        start_col_coord = starting_key % self._KEYBOARD_COLUMNS
        end_row_coord = ending_key // self._KEYBOARD_COLUMNS
        end_col_coord = ending_key % self._KEYBOARD_COLUMNS

        return abs(end_row_coord - start_row_coord) + abs(end_col_coord - start_col_coord)

    def minimumDistance(self, input_string: str) -> int:
        sequence_length = len(input_string)
        total_key_positions = self._UNPLACED_FINGER_INDEX + 1

        # dynamic_programming_cache[char_position][finger1_at][finger2_at]
        # stores the minimal distance to type characters from 'char_position' onwards
        dynamic_programming_cache = [[[0] * total_key_positions
                                      for _ in range(total_key_positions)]
                                     for _ in range(sequence_length + 1)]

        current_char_in_sequence = sequence_length - 1
        while current_char_in_sequence >= 0:
            target_char_key_index = ord(input_string[current_char_in_sequence]) - ord('A')

            finger_one_position = 0
            while finger_one_position < total_key_positions:

                finger_two_position = 0
                while finger_two_position < total_key_positions:

                    # Scenario 1: First finger moves to type the current character
                    movement_cost_f1 = self._determine_key_travel_cost(finger_one_position, target_char_key_index)
                    total_effort_option1 = dynamic_programming_cache[current_char_in_sequence + 1][target_char_key_index][finger_two_position] + movement_cost_f1

                    # Scenario 2: Second finger moves to type the current character
                    movement_cost_f2 = self._determine_key_travel_cost(finger_two_position, target_char_key_index)
                    total_effort_option2 = dynamic_programming_cache[current_char_in_sequence + 1][finger_one_position][target_char_key_index] + movement_cost_f2

                    # Store the minimum of the two scenarios
                    dynamic_programming_cache[current_char_in_sequence][finger_one_position][finger_two_position] = min(total_effort_option1, total_effort_option2)

                    finger_two_position += 1
                finger_one_position += 1
            current_char_in_sequence -= 1

        # The final result is the minimum distance to type the entire string,
        # starting with both fingers in the unplaced state.
        return dynamic_programming_cache[0][self._UNPLACED_FINGER_INDEX][self._UNPLACED_FINGER_INDEX]