# LeetCode Daily Challenge
# Date: 2026-07-30
# Problem: Minimum Number of Pushes to Type Word I
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def minimumPushes(self, word_string: str) -> int:
        total_characters = len(word_string)
        
        # Determine the number of complete sets of 8 characters
        # Each set of 8 characters will occupy 8 distinct 'slots' on the virtual keypad
        num_full_eights = total_characters // 8
        
        # Determine the number of characters remaining after forming complete sets
        chars_remainder = total_characters % 8
        
        # Calculate the cumulative pushes for the full sets of 8 characters.
        # The first 8 characters are pushed 1 time each, next 8 are pushed 2 times each, etc.
        # This sum is 8 * (1 + 2 + ... + num_full_eights)
        # Which simplifies to 8 * (num_full_eights * (num_full_eights + 1) / 2)
        # Or 4 * num_full_eights * (num_full_eights + 1)
        pushes_from_full_groups = 4 * num_full_eights * (num_full_eights + 1)
        
        # Calculate the pushes for the remaining characters.
        # These characters will be pushed (num_full_eights + 1) times each.
        pushes_from_remainder = chars_remainder * (num_full_eights + 1)
        
        # The total minimum pushes is the sum of pushes from full groups and remaining characters
        return pushes_from_full_groups + pushes_from_remainder