# LeetCode Daily Challenge
# Date: 2026-08-31
# Problem: #2058 Find the Minimum and Maximum Number of Nodes Between Critical Points
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def nodesBetweenCriticalPoints(self, head: ListNode) -> List[int]:
        current_index = 0
        critical_point_indices = []
        previous_value = head.val

        while head.next:
            current_value = head.val
            next_value = head.next.val

            if (previous_value - current_value) * (current_value - next_value) < 0:
                critical_point_indices.append(current_index)

            previous_value = current_value
            head = head.next
            current_index += 1

        count_critical_points = len(critical_point_indices)

        if count_critical_points < 2:
            return [-1, -1]

        min_dist_critical = float('inf')
        for idx in range(1, count_critical_points):
            consecutive_dist = critical_point_indices[idx] - critical_point_indices[idx - 1]
            min_dist_critical = min(min_dist_critical, consecutive_dist)

        max_dist_critical = critical_point_indices[-1] - critical_point_indices[0]

        return [int(min_dist_critical), max_dist_critical]