# LeetCode Daily Challenge
# Date: 2026-06-06
# Problem: Left and Right Sum Differences
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def leftRigthDifference(self, integer_list: List[int]) -> List[int]:
        difference_values = []
        current_position = 0
        list_length = len(integer_list)
        while current_position < list_length:
            left_segment_sum = sum(integer_list[:current_position])
            right_segment_sum = sum(integer_list[current_position + 1:])
            absolute_difference = abs(left_segment_sum - right_segment_sum)
            difference_values.append(absolute_difference)
            current_position += 1
        return difference_values