# LeetCode Daily Challenge
# Date: 2026-04-11
# Problem: Minimum Distance Between Three Equal Elements II
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from collections import defaultdict
import math
from typing import List

class Solution:
    def minimumDistance(self, number_array: List[int]) -> int:
        value_to_indices = defaultdict(list)

        element_idx = 0
        while element_idx < len(number_array):
            current_number = number_array[element_idx]
            value_to_indices[current_number].append(element_idx)
            element_idx += 1

        overall_min_dist = math.inf

        all_occurrence_lists = list(value_to_indices.values())
        list_iterator = 0
        while list_iterator < len(all_occurrence_lists):
            indices_of_occurrences = all_occurrence_lists[list_iterator]

            if len(indices_of_occurrences) >= 3:
                triplet_end_pointer = 2
                while triplet_end_pointer < len(indices_of_occurrences):
                    first_pos = indices_of_occurrences[triplet_end_pointer - 2]
                    second_pos = indices_of_occurrences[triplet_end_pointer - 1]
                    third_pos = indices_of_occurrences[triplet_end_pointer]

                    current_triplet_distance = abs(first_pos - second_pos) + \
                                               abs(second_pos - third_pos) + \
                                               abs(third_pos - first_pos)
                    
                    overall_min_dist = min(overall_min_dist, current_triplet_distance)
                    
                    triplet_end_pointer += 1
            
            list_iterator += 1

        return overall_min_dist if overall_min_dist != math.inf else -1