# LeetCode Daily Challenge
# Date: 2026-08-17
# Problem: Stone Game V
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def stoneGameV(self, rock_weights: list[int]) -> int:
        num_rocks = len(rock_weights)
        
        max_scores_memo = [[0] * num_rocks for _ in range(num_rocks)]
        segment_max_values = [[0] * num_rocks for _ in range(num_rocks)]

        initial_index_val = 0
        while initial_index_val < num_rocks:
            segment_max_values[initial_index_val][initial_index_val] = rock_weights[initial_index_val]
            initial_index_val += 1

        current_end_boundary = 1
        while current_end_boundary < num_rocks:
            split_point_marker = current_end_boundary
            segment_aggregate_sum = rock_weights[current_end_boundary]
            right_portion_sum = 0

            current_start_boundary = current_end_boundary - 1
            while current_start_boundary >= 0:
                segment_aggregate_sum += rock_weights[current_start_boundary]

                while split_point_marker > current_start_boundary and \
                      (right_portion_sum + rock_weights[split_point_marker]) * 2 <= segment_aggregate_sum:
                    right_portion_sum += rock_weights[split_point_marker]
                    split_point_marker -= 1
                
                calculated_max_score = 0
                
                if right_portion_sum * 2 == segment_aggregate_sum:
                    calculated_max_score = segment_max_values[current_start_boundary][split_point_marker]
                else:
                    if split_point_marker == current_start_boundary:
                        calculated_max_score = 0
                    else:
                        calculated_max_score = segment_max_values[current_start_boundary][split_point_marker - 1]
                
                if split_point_marker == current_end_boundary:
                    calculated_max_score = max(calculated_max_score, 0)
                else:
                    calculated_max_score = max(calculated_max_score, segment_max_values[current_end_boundary][split_point_marker + 1])
                
                max_scores_memo[current_start_boundary][current_end_boundary] = calculated_max_score

                segment_max_values[current_start_boundary][current_end_boundary] = max(
                    segment_max_values[current_start_boundary][current_end_boundary - 1],
                    max_scores_memo[current_start_boundary][current_end_boundary] + segment_aggregate_sum
                )
                
                segment_max_values[current_end_boundary][current_start_boundary] = max(
                    segment_max_values[current_end_boundary][current_start_boundary + 1],
                    max_scores_memo[current_start_boundary][current_end_boundary] + segment_aggregate_sum
                )
                
                current_start_boundary -= 1
            
            current_end_boundary += 1
            
        return max_scores_memo[0][num_rocks - 1]