# LeetCode Daily Challenge
# Date: 2026-03-15
# Problem: Fancy Sequence
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    _MODULUS_CONSTANT = 1_000_000_007

    def __init__(self):
        self.tracked_elements = []
        self.cumulative_offsets = [0]
        self.cumulative_factors = [1]

    def add_new_value(self, value_to_add):
        self.tracked_elements.append(value_to_add)
        self.cumulative_offsets.append(self.cumulative_offsets[-1])
        self.cumulative_factors.append(self.cumulative_factors[-1])

    def apply_global_increment(self, increment_by):
        self.cumulative_offsets[-1] += increment_by

    def apply_global_scale(self, scale_by):
        current_modulo = Solution._MODULUS_CONSTANT
        self.cumulative_offsets[-1] = (self.cumulative_offsets[-1] * scale_by) % current_modulo
        self.cumulative_factors[-1] = (self.cumulative_factors[-1] * scale_by) % current_modulo

    def fetch_element_value(self, element_index):
        if element_index >= len(self.tracked_elements):
            return -1
        
        current_modulo = Solution._MODULUS_CONSTANT
        
        inverse_factor_at_index = pow(self.cumulative_factors[element_index], current_modulo - 2, current_modulo)
        element_specific_factor = (self.cumulative_factors[-1] * inverse_factor_at_index) % current_modulo
        
        element_specific_offset = self.cumulative_offsets[-1] - (self.cumulative_offsets[element_index] * element_specific_factor)
        
        resultant_value = (self.tracked_elements[element_index] * element_specific_factor + element_specific_offset) % current_modulo
        
        return resultant_value