# LeetCode Daily Challenge
# Date: 2026-04-30
# Problem: Maximum Path Score in a Grid
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

from typing import List

class Solution:
    def maxPathScore(self, input_grid: List[List[int]], max_allowed_cost: int) -> int:
        num_rows, num_cols = len(input_grid), len(input_grid[0])
        
        current_column_dp_states = [dict() for _ in range(num_cols)]
        current_column_dp_states[0][0] = 0 
        
        row_iterator = 0
        while row_iterator < num_rows:
            new_row_dp_states = [dict() for _ in range(num_cols)]
            
            col_iterator = 0
            while col_iterator < num_cols:
                cell_entry_cost = min(1, input_grid[row_iterator][col_iterator])
                
                for previous_row_cost in current_column_dp_states[col_iterator]:
                    total_current_cost = previous_row_cost + cell_entry_cost
                    
                    if total_current_cost <= max_allowed_cost:
                        current_path_total_score = current_column_dp_states[col_iterator][previous_row_cost] + input_grid[row_iterator][col_iterator]
                        
                        new_row_dp_states[col_iterator][total_current_cost] = max(
                            new_row_dp_states[col_iterator].get(total_current_cost, -1), 
                            current_path_total_score
                        )
                
                if col_iterator < num_cols - 1: 
                    right_cell_entry_cost = min(1, input_grid[row_iterator][col_iterator + 1])
                    
                    for cost_to_current_cell in new_row_dp_states[col_iterator]:
                        cost_to_right_cell = cost_to_current_cell + right_cell_entry_cost
                        
                        if cost_to_right_cell <= max_allowed_cost:
                            right_path_total_score = new_row_dp_states[col_iterator][cost_to_current_cell] + input_grid[row_iterator][col_iterator + 1]
                            
                            new_row_dp_states[col_iterator + 1][cost_to_right_cell] = max(
                                new_row_dp_states[col_iterator + 1].get(cost_to_right_cell, -1), 
                                right_path_total_score                                
                            )
                
                col_iterator += 1
            
            current_column_dp_states = new_row_dp_states
            row_iterator += 1

        final_cell_states = current_column_dp_states[num_cols - 1]
        
        if not final_cell_states:
            return -1 

        return max(final_cell_states.values())