# LeetCode Daily Challenge
# Date: 2026-06-14
# Problem: Maximum Twin Sum of a Linked List
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def pairSum(self, initial_node: Optional[ListNode]) -> int:
        def reverse_list_segment(segment_head: Optional[ListNode]) -> Optional[ListNode]:
            previous_node, current_node = None, segment_head
            while current_node:
                temp_next_node = current_node.next
                current_node.next = previous_node
                previous_node = current_node
                current_node = temp_next_node
            return previous_node
        
        slow_ptr, fast_ptr = initial_node, initial_node
        while fast_ptr and fast_ptr.next:
            slow_ptr = slow_ptr.next
            fast_ptr = fast_ptr.next.next
        
        first_half_current = initial_node
        second_half_reversed_current = reverse_list_segment(slow_ptr)
        
        maximum_pairwise_sum = 0
        
        while second_half_reversed_current:
            current_pair_total = first_half_current.val + second_half_reversed_current.val
            if current_pair_total > maximum_pairwise_sum:
                maximum_pairwise_sum = current_pair_total
            
            first_half_current = first_half_current.next
            second_half_reversed_current = second_half_reversed_current.next
        
        return maximum_pairwise_sum