# LeetCode Daily Challenge
# Date: 2026-05-19
# Problem: Minimum Common Value
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def getCommon(self, first_array_elements, second_array_elements):
        # Initialize index pointers for both sorted input lists
        pointer_alpha = 0
        pointer_beta = 0

        # Cache array lengths to avoid repeated calculations in the loop condition
        length_of_alpha = len(first_array_elements)
        length_of_beta = len(second_array_elements)

        # Iterate through both arrays using a two-pointer approach
        while pointer_alpha < length_of_alpha and pointer_beta < length_of_beta:
            # Fetch the current values at the respective pointers
            current_val_alpha = first_array_elements[pointer_alpha]
            current_val_beta = second_array_elements[pointer_beta]

            # If the values are equal, we've found the first common element
            if current_val_alpha == current_val_beta:
                return current_val_alpha
            # If the value from the first array is smaller, advance its pointer
            elif current_val_alpha < current_val_beta:
                pointer_alpha += 1
            # Otherwise (value from second array is smaller), advance its pointer
            else:
                pointer_beta += 1

        # If the loop completes without finding a common element, return -1
        return -1