# LeetCode Daily Challenge
# Date: 2026-03-30
# Problem: Check if Strings Can be Made Equal With Operations II
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

from collections import defaultdict

class Solution:
    def checkStrings(self, input_string_one: str, input_string_two: str) -> bool:
        # Dictionaries to store character frequencies for even-indexed positions in the first string
        even_pos_freq_one = defaultdict(int)
        # Dictionaries to store character frequencies for odd-indexed positions in the first string
        odd_pos_freq_one = defaultdict(int)

        # Dictionaries to store character frequencies for even-indexed positions in the second string
        even_pos_freq_two = defaultdict(int)
        # Dictionaries to store character frequencies for odd-indexed positions in the second string
        odd_pos_freq_two = defaultdict(int)

        current_pos = 0
        total_length = len(input_string_one)

        while current_pos < total_length:
            char_from_s1 = input_string_one[current_pos]
            char_from_s2 = input_string_two[current_pos]

            if current_pos % 2 == 0:
                even_pos_freq_one[char_from_s1] += 1
                even_pos_freq_two[char_from_s2] += 1
            else:
                odd_pos_freq_one[char_from_s1] += 1
                odd_pos_freq_two[char_from_s2] += 1
            
            current_pos += 1
        
        # Compare the frequency maps for even and odd positions
        return (even_pos_freq_one == even_pos_freq_two) and (odd_pos_freq_one == odd_pos_freq_two)