# LeetCode Daily Challenge
# Date: 2026-03-22
# Problem: Determine Whether Matrix Can Be Obtained By Rotation
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def findRotation(self, current_matrix: List[List[int]], desired_matrix: List[List[int]]) -> bool:
        rotation_count = 0
        while rotation_count < 4:
            if current_matrix == desired_matrix:
                return True
            
            # Perform a 90-degree clockwise rotation
            # Step 1: Reverse the order of rows
            reversed_rows_list = current_matrix[::-1]
            
            # Step 2: Transpose the matrix (columns become rows)
            # and convert each resulting tuple back to a list
            current_matrix = [list(column_values) for column_values in zip(*reversed_rows_list)]
            
            rotation_count += 1
            
        return False