# LeetCode Daily Challenge
# Date: 2026-05-21
# Problem: Find the Length of the Longest Common Prefix
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

from typing import List
from bisect import bisect_left

class Solution:
    def longestCommonPrefix(self, input_list_one: List[int], input_list_two: List[int]) -> int:
        def calculate_matching_prefix_length(first_str_val: str, second_str_val: str) -> int:
            shorter_string_length = min(len(first_str_val), len(second_str_val))
            current_char_index = 0
            while current_char_index < shorter_string_length:
                if first_str_val[current_char_index] != second_str_val[current_char_index]:
                    return current_char_index
                current_char_index += 1
            return shorter_string_length

        string_elements_list_one = [str(numeric_val) for numeric_val in input_list_one]
        string_elements_list_two = [str(numeric_val) for numeric_val in input_list_two]

        string_elements_list_one.sort()
        string_elements_list_two.sort()

        maximum_common_prefix_found = 0

        for current_string_from_list_one in string_elements_list_one:
            insertion_point_idx = bisect_left(string_elements_list_two, current_string_from_list_one)

            if insertion_point_idx < len(string_elements_list_two):
                current_match_length = calculate_matching_prefix_length(current_string_from_list_one, string_elements_list_two[insertion_point_idx])
                maximum_common_prefix_found = max(maximum_common_prefix_found, current_match_length)
            
            if insertion_point_idx > 0:
                previous_match_length = calculate_matching_prefix_length(current_string_from_list_one, string_elements_list_two[insertion_point_idx - 1])
                maximum_common_prefix_found = max(maximum_common_prefix_found, previous_match_length)
        
        return maximum_common_prefix_found