# LeetCode Daily Challenge
# Date: 2026-06-08
# Problem: Partition Array According to Given Pivot
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:\n\t\tdef pivotArray(self, nums: List[int], pivot: int) -> List[int]:\n\n\t\t\tans=[]\n\n\t\t\tnums.remove(pivot)\n\n\t\t\ti=0\n\t\t\tans.append(pivot)\n\n\t\t\tfor j in nums:\n\t\t\t\tif j<pivot:\n\t\t\t\t\tans.insert(i,j)\n\t\t\t\t\ti=i+1\n\t\t\t\telif j==pivot:\n\t\t\t\t\tans.insert(i+1,j)\n\t\t\t\telse:\n\t\t\t\t\tans.append(j)\n\n\t\t\treturn ans