# LeetCode Daily Challenge
# Date: 2026-03-24
# Problem: Construct Product Matrix
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from typing import List

class Solution:
    def constructProductMatrix(self, input_matrix: List[List[int]]) -> List[List[int]]:

        # Define the modulo value as a constant for clarity
        MODULO_DIVISOR = 12345

        # Determine matrix dimensions
        num_rows = len(input_matrix)
        num_cols = len(input_matrix[0])
        total_elements = num_rows * num_cols

        # Initialize lists to store cumulative products
        # 'products_from_start' will store the product of all elements encountered so far,
        # including a leading 1 for the "product before the first element".
        products_from_start = [1]
        # 'products_from_end' will store the product of all elements encountered so far
        # when iterating backwards, including a leading 1 for the "product after the last element".
        products_from_end = [1]

        # Calculate products from the beginning of the flattened matrix
        current_row_index = 0
        while current_row_index < num_rows:
            current_col_index = 0
            while current_col_index < num_cols:
                element_val = input_matrix[current_row_index][current_col_index]
                # Calculate the new cumulative product, applying modulo at each step
                next_product_fwd = (products_from_start[-1] * element_val) % MODULO_DIVISOR
                products_from_start.append(next_product_fwd)
                current_col_index += 1
            current_row_index += 1

        # Calculate products from the end of the flattened matrix
        # Iterate rows in reverse
        row_reverse_idx = num_rows - 1
        while row_reverse_idx >= 0:
            # Iterate columns in reverse
            col_reverse_idx = num_cols - 1
            while col_reverse_idx >= 0:
                element_val = input_matrix[row_reverse_idx][col_reverse_idx]
                # Calculate the new cumulative product, applying modulo at each step
                next_product_bwd = (products_from_end[-1] * element_val) % MODULO_DIVISOR
                products_from_end.append(next_product_bwd)
                col_reverse_idx -= 1
            row_reverse_idx -= 1

        # Populate the result matrix (modifying the input_matrix in place)
        # For each element at (r, c), its product will be
        # (product of elements before it) * (product of elements after it).
        # The 'before it' product comes from 'products_from_start'.
        # The 'after it' product comes from 'products_from_end'.
        r_idx_final = 0
        while r_idx_final < num_rows:
            c_idx_final = 0
            while c_idx_final < num_cols:
                # Calculate the 1D (flattened) index for the current cell
                flat_element_pos = r_idx_final * num_cols + c_idx_final

                # The product of elements strictly before the current one
                # is at index `flat_element_pos` in `products_from_start`
                # (since `products_from_start[0]` is the initial 1, and `products_from_start[k+1]`
                # is the product up to element `k`).
                product_before_this_element = products_from_start[flat_element_pos]

                # The product of elements strictly after the current one
                # is at index `total_elements - 1 - flat_element_pos` in `products_from_end`.
                # This accounts for the `products_from_end[0]` initial 1 and the reverse order.
                product_after_this_element = products_from_end[total_elements - 1 - flat_element_pos]

                # The final product for the current cell is the product of these two parts
                # (modulo MODULO_DIVISOR)
                input_matrix[r_idx_final][c_idx_final] = (product_before_this_element * product_after_this_element) % MODULO_DIVISOR

                c_idx_final += 1
            r_idx_final += 1

        # The modified input_matrix is the result
        return input_matrix