# LeetCode Daily Challenge
# Date: 2026-03-23
# Problem: Maximum Non Negative Product in a Matrix
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def maxProductPath(self, grid: list[list[int]]) -> int:
        rows_count, cols_count = len(grid), len(grid[0])
        
        # Define a constant for the modulo operation.
        # This enhances readability and makes the value easier to update if needed.
        MODULO_DIVISOR = 1_000_000_007

        @lru_cache(None)
        def determine_extrema_products(current_row_pos: int, current_col_pos: int) -> tuple[float, float]: 
            """
            Calculates the maximum and minimum product paths that end at the given
            (current_row_pos, current_col_pos) cell within the grid.
            Returns a tuple: (highest_product_found, lowest_product_found).
            """
            
            # Base case: For the starting cell (top-left corner), 
            # the product path is simply its own value.
            if current_row_pos == 0 and current_col_pos == 0:
                initial_cell_content = float(grid[0][0])
                return initial_cell_content, initial_cell_content
            
            # Base case: If the coordinates are outside the grid boundaries,
            # these paths are considered invalid. We return extreme values
            # to ensure they do not incorrectly influence valid path computations.
            if current_row_pos < 0 or current_col_pos < 0:
                return float('-inf'), float('inf')
            
            current_cell_content = float(grid[current_row_pos][current_col_pos])
            
            # If the current cell's value is zero, any product path passing through it
            # will result in a zero product.
            if current_cell_content == 0:
                return 0.0, 0.0
            
            # Recursively fetch the max and min products from the cell immediately above.
            max_product_from_up, min_product_from_up = determine_extrema_products(current_row_pos - 1, current_col_pos)
            
            # Recursively fetch the max and min products from the cell immediately to the left.
            max_product_from_left, min_product_from_left = determine_extrema_products(current_row_pos, current_col_pos - 1)
            
            # Compute all four possible product values by multiplying the previous extrema
            # with the current cell's value. This method correctly handles cases where
            # current_cell_content is positive or negative.
            candidate_products = [
                max_product_from_up * current_cell_content,
                min_product_from_up * current_cell_content,
                max_product_from_left * current_cell_content,
                min_product_from_left * current_cell_content
            ]
            
            # The maximum product ending at this cell is the largest among the candidates.
            current_cell_highest_product = max(candidate_products)
            # The minimum product ending at this cell is the smallest among the candidates.
            current_cell_lowest_product = min(candidate_products)
            
            return current_cell_highest_product, current_cell_lowest_product
        
        # After calculating all path extrema up to the bottom-right cell,
        # we retrieve the overall maximum product.
        final_max_path_value, _ = determine_extrema_products(rows_count - 1, cols_count - 1)
        
        # As per problem requirements, if the maximum product is negative, we return -1.
        if final_max_path_value < 0:
            return -1
        else:
            # Otherwise, we return the maximum product modulo the specified constant.
            # The result is cast to an integer, as implied by the problem.
            return int(final_max_path_value % MODULO_DIVISOR)