# LeetCode Daily Challenge
# Date: 2026-09-01
# Problem: #3568 Minimum Moves to Clean the Classroom
# Language: python3
# Submission Result: Accepted
# Auto-generated by LeetCode Agent

from typing import List
from collections import deque


class Solution:
    def minMoves(self, classroom: List[str], energy: int) -> int:
        """
        Calculates the minimum moves required to collect all litter items in the classroom.
        Uses BFS with state (row, col, energy, collected_litter_mask).
        """
        m, n = len(classroom), len(classroom[0])
        start = None
        litter = {}

        for r in range(m):
            for c in range(n):
                if classroom[r][c] == 'S':
                    start = (r, c)
                elif classroom[r][c] == 'L':
                    litter[(r, c)] = len(litter)

        k = len(litter)
        if k == 0:
            return 0

        target_mask = (1 << k) - 1

        # visited[r][c][mask] stores the maximum energy remaining when reaching (r, c) with mask
        visited = [[[-1] * (1 << k) for _ in range(n)] for _ in range(m)]
        q = deque()

        sr, sc = start
        init_mask = 0
        init_e = energy
        if (sr, sc) in litter:
            init_mask |= (1 << litter[(sr, sc)])
        if classroom[sr][sc] == 'R':
            init_e = energy

        visited[sr][sc][init_mask] = init_e
        q.append((sr, sc, init_e, init_mask, 0))

        while q:
            r, c, e, mask, moves = q.popleft()

            if mask == target_mask:
                return moves

            if e == 0:
                continue

            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                nr, nc = r + dr, c + dc
                if 0 <= nr < m and 0 <= nc < n and classroom[nr][nc] != 'X':
                    ne = e - 1
                    nmask = mask
                    if (nr, nc) in litter:
                        nmask |= (1 << litter[(nr, nc)])
                    if classroom[nr][nc] == 'R':
                        ne = energy

                    if ne > visited[nr][nc][nmask]:
                        visited[nr][nc][nmask] = ne
                        q.append((nr, nc, ne, nmask, moves + 1))

        return -1