# LeetCode Daily Challenge
# Date: 2026-04-20
# Problem: Two Furthest Houses With Different Colors
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def maxDistance(self, hues: List[int]) -> int:
        start_idx = 0
        total_hues = len(hues)
        end_idx = total_hues - 1

        # Locate the rightmost house whose color is different from the very first house
        while hues[end_idx] == hues[0]:
            end_idx -= 1
        
        # Locate the leftmost house whose color is different from the very last house
        while hues[start_idx] == hues[total_hues - 1]:
            start_idx += 1
            
        # The maximum distance is the greater of two possibilities:
        # 1. Distance from the first house (index 0) to 'end_idx'
        # 2. Distance from 'start_idx' to the last house (index total_hues - 1)
        return max(end_idx, total_hues - 1 - start_idx)

O(n^2)
        maximum_difference = 0
        house_count = len(hues) # Assuming 'hues' is the input list, consistent with the above solution
        
        first_house_index = 0
        while first_house_index < house_count:
            second_house_index = 0
            while second_house_index < house_count:
                if hues[first_house_index] != hues[second_house_index]:
                    current_span = abs(second_house_index - first_house_index)
                    if current_span > maximum_difference:
                        maximum_difference = current_span
                second_house_index += 1
            first_house_index += 1
        return maximum_difference