# LeetCode Daily Challenge
# Date: 2026-04-13
# Problem: Minimum Distance to the Target Element
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def getMinDistance(self, number_sequence: List[int], search_value: int, initial_position: int) -> int:
        left_pointer = initial_position
        right_pointer = initial_position
        sequence_length = len(number_sequence)

        while left_pointer >= 0 or right_pointer < sequence_length:
            if left_pointer >= 0 and number_sequence[left_pointer] == search_value:
                return initial_position - left_pointer
            if right_pointer < sequence_length and number_sequence[right_pointer] == search_value:
                return right_pointer - initial_position
            left_pointer -= 1
            right_pointer += 1