# LeetCode Daily Challenge
# Date: 2026-03-28
# Problem: Find the String with LCP
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution(object):
    def findTheString(self, lcp_matrix):
        string_length = len(lcp_matrix)

        # First pass: Validate LCP matrix properties
        row_idx = 0
        while row_idx < string_length:
            col_idx = 0
            while col_idx < string_length:
                # Property 2: Diagonal elements must reflect remaining length
                if row_idx == col_idx and lcp_matrix[row_idx][col_idx] != string_length - row_idx:
                    return ""

                # Property 3: LCP matrix must be symmetric
                if lcp_matrix[row_idx][col_idx] != lcp_matrix[col_idx][row_idx]:
                    return ""

                # Property 5: LCP value cannot exceed remaining string length from either index
                if lcp_matrix[row_idx][col_idx] > string_length - max(row_idx, col_idx):
                    return ""

                # Property 4: LCP values of substrings must decrease by one
                if row_idx < string_length - 1 and col_idx < string_length - 1:
                    if lcp_matrix[row_idx][col_idx] > 0:
                        if lcp_matrix[row_idx + 1][col_idx + 1] != lcp_matrix[row_idx][col_idx] - 1:
                            return ""
                col_idx += 1
            row_idx += 1

        # Second pass: Construct the candidate string
        next_available_char = 'a'
        candidate_string_chars = ['#'] * string_length # Using list multiplication for initialization

        current_char_pos = 0
        while current_char_pos < string_length:
            if candidate_string_chars[current_char_pos] != '#':
                current_char_pos += 1
                continue

            if next_available_char > 'z':
                return "" # Exhausted character set

            fill_target_pos = current_char_pos
            while fill_target_pos < string_length:
                # If lcp[current_char_pos][fill_target_pos] > 0, it means s[current_char_pos] == s[fill_target_pos]
                # so they should be assigned the same character.
                if lcp_matrix[current_char_pos][fill_target_pos] > 0:
                    candidate_string_chars[fill_target_pos] = next_available_char
                fill_target_pos += 1
            
            next_available_char = chr(ord(next_available_char) + 1)
            current_char_pos += 1

        # Third pass: Final verification against the constructed string
        primary_index = 0
        while primary_index < string_length:
            secondary_index = 0
            while secondary_index < string_length:
                required_lcp_length = lcp_matrix[primary_index][secondary_index]

                if required_lcp_length > 0:
                    # Extract substrings from the constructed string
                    substring_from_primary = candidate_string_chars[primary_index : primary_index + required_lcp_length]
                    substring_from_secondary = candidate_string_chars[secondary_index : secondary_index + required_lcp_length]

                    # Check if the substrings match as per LCP value
                    if substring_from_primary != substring_from_secondary:
                        return ""
                secondary_index += 1
            primary_index += 1

        return "".join(candidate_string_chars)