# LeetCode Daily Challenge
# Date: 2026-09-23
# Problem: #1658 Minimum Operations to Reduce X to Zero
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def minOperations(self, nums: List[int], x: int) -> int:
        total_sum = sum(nums)
        if total_sum < x:
            return -1
        if total_sum == x:
            return len(nums)
        
        target_sum = total_sum - x
        window_left = window_sum = max_window_len = 0
        
        for window_right, current_val in enumerate(nums):
            window_sum += current_val
            while window_sum > target_sum:
                window_sum -= nums[window_left]
                window_left += 1
            if window_sum == target_sum:
                max_window_len = max(max_window_len, window_right - window_left + 1)
                
        return len(nums) - max_window_len if max_window_len > 0 else -1