# LeetCode Daily Challenge
# Date: 2026-03-04
# Problem: Special Positions in a Binary Matrix
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def numSpecial(self, mat: List[List[int]]) -> int:
        rows = [sum(r) for r in mat]; cols = [sum(c) for c in zip(*mat)]
        return sum(mat[i][j] and rows[i] == cols[j] == 1 for i in range(len(mat)) for j in range(len(mat[0])))