# LeetCode Daily Challenge
# Date: 2026-07-27
# Problem: Maximum Product of Two Elements in an Array
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import heapq
from typing import List

class Solution:
    def maxProduct(self, number_array: List[int]) -> int:
        
        top_two_elements = [-1] 

        for current_value in number_array:
            if current_value > top_two_elements[0]:
                if len(top_two_elements) == 2:
                    heapq.heappop(top_two_elements)
                heapq.heappush(top_two_elements, current_value)
                
        first_largest = heapq.heappop(top_two_elements)
        second_largest = heapq.heappop(top_two_elements)
        
        return (first_largest - 1) * (second_largest - 1)