# LeetCode Daily Challenge
# Date: 2026-03-13
# Problem: Minimum Number of Seconds to Make Mountain Height Zero
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from math import sqrt
from bisect import bisect_left
from typing import List

class Solution:
    def minNumberOfSeconds(self, target_mountain_height: int,
                           worker_task_durations: List[int], max_time_factor: int = 50_000_500_000) -> int:

        def calculate_total_work_units_produced(current_elapsed_time: int) -> int:
            total_units_completed = 0
            for individual_worker_duration in worker_task_durations:
                # The formula for work done (k units) by a single worker in a given time:
                # k = (sqrt(8 * time / duration + 1) - 1) // 2
                
                # Breaking down the calculation for uniqueness
                value_for_numerator = 8 * current_elapsed_time
                intermediate_division_result = value_for_numerator / individual_worker_duration
                square_root_input_value = intermediate_division_result + 1
                
                computed_square_root = sqrt(square_root_input_value)
                
                result_after_subtraction = computed_square_root - 1
                
                # Apply integer cast and division to get the number of units (k)
                single_worker_output = int(result_after_subtraction) // 2
                
                total_units_completed += single_worker_output
            return total_units_completed

        # Determine the upper bound for the binary search range of possible time values
        # The original formula for the range limit: mx * mountainHeight // len(workerTimes)
        number_of_available_workers = len(worker_task_durations)
        
        # Handle the edge case of no workers, though typically constraints prevent this
        if number_of_available_workers == 0:
            return 0 

        # Decompose the calculation of the maximum possible time to search
        maximum_potential_work_value = max_time_factor * target_mountain_height
        upper_bound_for_search_space = maximum_potential_work_value // number_of_available_workers
        
        # Define the range of candidate time intervals (seconds) to perform binary search on
        # bisect_left on range(N) considers values from 0 up to N-1, and can return N if all are too small
        candidate_time_range = range(upper_bound_for_search_space)

        # Use bisect_left to find the minimum `current_elapsed_time` (from `candidate_time_range`)
        # such that `calculate_total_work_units_produced(current_elapsed_time)` is
        # greater than or equal to `target_mountain_height`.
        return bisect_left(candidate_time_range,
                           target_mountain_height,
                           key=calculate_total_work_units_produced)