# LeetCode Daily Challenge
# Date: 2026-07-31
# Problem: Minimum Number of Pushes to Type Word II
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import heapq

class Solution:
    def minimumPushes(self, word_to_type: str) -> int:
        letter_occurrence_map = {}
        for char_token in word_to_type:
            letter_occurrence_map[char_token] = letter_occurrence_map.get(char_token, 0) + 1
        
        priority_queue_of_frequencies = []
        for freq_val in letter_occurrence_map.values():
            priority_queue_of_frequencies.append(-freq_val)
        
        heapq.heapify(priority_queue_of_frequencies)
        
        final_push_count = 0
        current_assignment_slot = 0
        
        while len(priority_queue_of_frequencies) > 0:
            highest_frequency_value = -heapq.heappop(priority_queue_of_frequencies)
            
            key_press_multiplier = (current_assignment_slot // 8) + 1
            
            final_push_count += key_press_multiplier * highest_frequency_value
            
            current_assignment_slot += 1
        
        return final_push_count