# LeetCode Daily Challenge
# Date: 2026-08-31
# Problem: #2058 Find the Minimum and Maximum Number of Nodes Between Critical Points
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def nodesBetweenCriticalPoints(self, head: ListNode) -> List[int]:
        currentNodeIndex = 0
        criticalPointIndices = []
        previousNodeValue = head.val
        currentListNode = head

        while currentListNode.next:
            # A critical point is a local extremum (peak or valley).
            # This condition checks if the current node's value is
            # strictly greater than both its predecessor and successor (peak),
            # or strictly less than both (valley).
            # The product (A-B)*(B-C) < 0 holds if (A>B and B<C) or (A<B and B>C).
            if (previousNodeValue - currentListNode.val) * (currentListNode.val - currentListNode.next.val) < 0:
                criticalPointIndices.append(currentNodeIndex)

            previousNodeValue = currentListNode.val
            currentListNode = currentListNode.next
            currentNodeIndex += 1

        numCriticalPointsFound = len(criticalPointIndices)
        if numCriticalPointsFound < 2:
            return [-1, -1]

        minDistanceBetweenAdjacent = min(criticalPointIndices[i] - criticalPointIndices[i-1]
                                         for i in range(1, numCriticalPointsFound))
        maxDistanceBetweenExtremes = criticalPointIndices[-1] - criticalPointIndices[0]

        return [minDistanceBetweenAdjacent, maxDistanceBetweenExtremes]