# LeetCode Daily Challenge
# Date: 2026-05-30
# Problem: Block Placement Queries
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def getResults(self, input_queries: List[List[int]]) -> List[bool]:

        # Sorted collection of block locations along the axis
        measurement_points = SortedList()

        # Segment tree to keep track of the maximum interval (gap) encountered from 0 to any block
        max_gap_tracker = SegTree(max(current_query_data[1] for current_query_data in input_queries))

        outcome_list = []
        measurement_points.add(0)
        max_gap_tracker.update_value(0, 0) # The gap from point 0 to point 0 is zero

        total_queries = len(input_queries)
        current_query_index = 0
        while current_query_index < total_queries:
            current_query_data = input_queries[current_query_index]
            query_operation_type = current_query_data[0]
            query_position_val = current_query_data[1]

            if query_operation_type == 1:
                # Operation type 1: Add a new block at 'query_position_val'
                insertion_location_idx = measurement_points.bisect_right(query_position_val) 

                if insertion_location_idx < len(measurement_points):
                    # If there's a block after the new one, its interval needs adjustment
                    succeeding_point = measurement_points[insertion_location_idx]
                    max_gap_tracker.update_value(succeeding_point, succeeding_point - query_position_val)
                
                # Set the interval for the newly added block itself
                preceding_point = measurement_points[insertion_location_idx - 1]
                max_gap_tracker.update_value(query_position_val, query_position_val - preceding_point)
                
                # Place the new block onto the axis
                measurement_points.add(query_position_val)
            else:
                # Operation type 2: Check if a minimum required gap 'query_check_value' can be formed
                query_check_value = current_query_data[2]
                
                # Identify the block immediately before 'query_position_val'
                # bisect_right provides the index where query_position_val would be inserted,
                # so index - 1 is the largest element less than or equal to query_position_val.
                last_block_before_target = measurement_points[measurement_points.bisect_right(query_position_val) - 1]
                
                # Determine the largest possible span up to 'query_position_val'.
                # This is either the direct gap from 'last_block_before_target' to 'query_position_val',
                # or the maximum gap previously recorded by the segment tree up to 'last_block_before_target'.
                gap_to_target = query_position_val - last_block_before_target
                max_recorded_gap_prefix = max_gap_tracker.query_max_prefix(last_block_before_target)
                
                overall_max_span = (gap_to_target if gap_to_target > max_recorded_gap_prefix else max_recorded_gap_prefix)

                outcome_list.append(query_check_value <= overall_max_span)
            
            current_query_index += 1
        return outcome_list

class SegTree:

    def __init__(self, maximum_possible_coordinate: int):
        # Calculate the size of the segment tree array (power of 2)
        self.segment_tree_array_size = 1 << maximum_possible_coordinate.bit_length()
        # Initialize the segment tree storage with zeros
        self.segment_data_nodes = [0] * (self.segment_tree_array_size * 2)

    def update_value(self, target_coord_index: int, new_segment_value: int):
        # Map the coordinate to a leaf node index in the segment tree
        current_node_idx = target_coord_index + self.segment_tree_array_size
        self.segment_data_nodes[current_node_idx] = new_segment_value
        
        # Propagate the update upwards to the root
        while current_node_idx > 1:
            current_node_idx //= 2
            # The parent node stores the maximum of its two children
            self.segment_data_nodes[current_node_idx] = (self.segment_data_nodes[current_node_idx * 2] if self.segment_data_nodes[current_node_idx * 2] > self.segment_data_nodes[current_node_idx * 2 + 1] else self.segment_data_nodes[current_node_idx * 2 + 1])
    
    def query_max_prefix(self, end_coord_index: int) -> int:
        # Map the query end coordinate to a leaf node index
        current_query_node_idx = end_coord_index + self.segment_tree_array_size
        max_value_found_so_far = self.segment_data_nodes[current_query_node_idx]
        
        # Traverse up from the leaf to the root
        while current_query_node_idx > 1:
            if current_query_node_idx % 2 == 1: # If the current node is a right child
                # Its left sibling covers a segment that is part of the prefix
                max_value_found_so_far = (max_value_found_so_far if max_value_found_so_far > self.segment_data_nodes[current_query_node_idx - 1] else self.segment_data_nodes[current_query_node_idx - 1])
            current_query_node_idx //= 2
        return max_value_found_so_far