# LeetCode Daily Challenge
# Date: 2026-04-22
# Problem: Words Within Two Edits of Dictionary
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def twoEditWords(self, candidate_words: List[str], reference_dictionary: List[str]) -> List[str]:
        matched_queries = []
        
        query_iterator_idx = 0
        total_queries = len(candidate_words)
        
        while query_iterator_idx < total_queries:
            current_query_string = candidate_words[query_iterator_idx]
            
            found_suitable_match = False
            dict_iterator_idx = 0
            total_dict_entries = len(reference_dictionary)
            
            while dict_iterator_idx < total_dict_entries:
                current_dict_entry = reference_dictionary[dict_iterator_idx]
                
                character_mismatch_count = 0
                string_length_common = len(current_query_string) 
                
                char_comparator_idx = 0
                while char_comparator_idx < string_length_common:
                    if current_query_string[char_comparator_idx] != current_dict_entry[char_comparator_idx]:
                        character_mismatch_count += 1
                    char_comparator_idx += 1
                
                if character_mismatch_count <= 2:
                    found_suitable_match = True
                    break 
                
                dict_iterator_idx += 1
            
            if found_suitable_match:
                matched_queries.append(current_query_string)
            
            query_iterator_idx += 1
            
        return matched_queries