# LeetCode Daily Challenge
# Date: 2026-07-12
# Problem: Rank Transform of an Array
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution(object):
    def arrayRankTransform(self, numerical_data):
        # Step 1: Identify all unique numerical values present in the input collection.
        # Then, arrange these distinct values in ascending order.
        unique_sorted_values = sorted(list(set(numerical_data)))

        # Step 2: Construct a dictionary to map each unique value to its corresponding rank.
        # Dense ranking assigns consecutive integers starting from 1.
        value_rank_map = {}
        current_rank_val = 1
        idx_unique = 0
        while idx_unique < len(unique_sorted_values):
            value_rank_map[unique_sorted_values[idx_unique]] = current_rank_val
            current_rank_val += 1
            idx_unique += 1

        # Step 3: Generate the final ranked array by iterating through the original input
        # and substituting each element with its assigned rank from the map.
        result_array_ranks = []
        for element_val in numerical_data:
            result_array_ranks.append(value_rank_map[element_val])

        return result_array_ranks