# LeetCode Daily Challenge
# Date: 2026-07-02
# Problem: Find a Safe Walk Through a Grid
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

from typing import List
from functools import lru_cache

class Solution:
    def findSafeWalk(self, terrain_grid: List[List[int]], max_hp_limit: int) -> bool:

        num_rows = len(terrain_grid)
        num_cols = len(terrain_grid[0])

        # Initialize the set of all traversable coordinates
        all_coords_available = set()
        current_row_idx = 0
        while current_row_idx < num_rows:
            current_col_idx = 0
            while current_col_idx < num_cols:
                all_coords_available.add((current_row_idx, current_col_idx))
                current_col_idx += 1
            current_row_idx += 1

        @lru_cache(None)
        def calculate_path_cost(r_coord: int, c_coord: int, current_expended_hp: int) -> float:
            # Base cases for invalid paths or exceeding health limit
            if current_expended_hp >= max_hp_limit or (r_coord, c_coord) not in all_coords_available:
                return float('inf')

            # Calculate health cost after moving to the current cell
            accumulated_hp_cost = current_expended_hp + terrain_grid[r_coord][c_coord]

            # If the destination is reached, return the accumulated cost
            if (r_coord, c_coord) == (num_rows - 1, num_cols - 1):
                return accumulated_hp_cost

            # Temporarily remove current cell from available ones to prevent cycles in this path
            all_coords_available.discard((r_coord, c_coord))

            # Recursively explore all four adjacent directions
            minimum_cost_from_here = min(
                calculate_path_cost(r_coord + 1, c_coord, accumulated_hp_cost),
                calculate_path_cost(r_coord, c_coord + 1, accumulated_hp_cost),
                calculate_path_cost(r_coord - 1, c_coord, accumulated_hp_cost),
                calculate_path_cost(r_coord, c_coord - 1, accumulated_hp_cost)
            )

            # Restore the current cell to available for other path explorations (backtracking)
            all_coords_available.add((r_coord, c_coord))

            return minimum_cost_from_here

        # Initiate the search from the starting point (0,0) with zero health spent
        final_minimum_path_hp_cost = calculate_path_cost(0, 0, 0)

        # Determine if a safe walk (within health limits) is possible
        return final_minimum_path_hp_cost < max_hp_limit