# LeetCode Daily Challenge
# Date: 2026-09-14
# Problem: #836 Rectangle Overlap
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def isRectangleOverlap(self, rec1: List[int], rec2: List[int]) -> bool:
        left_1, bottom_1, right_1, top_1 = rec1
        left_2, bottom_2, right_2, top_2 = rec2
        
        return (
            left_1 < right_2 and
            bottom_1 < top_2 and
            right_1 > left_2 and
            top_1 > bottom_2
        )