# LeetCode Daily Challenge
# Date: 2026-03-18
# Problem: Count Submatrices with Top-Left Element and Sum Less Than k
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def countSubmatrices(self, grid: List[List[int]], sum_threshold: int) -> int:
        num_rows = len(grid)
        num_cols = len(grid[0])
        count_of_valid_submatrices = 0

        current_row_index = 0
        while current_row_index < num_rows:
            current_col_index = 0
            while current_col_index < num_cols:
                
                if current_row_index > 0:
                    grid[current_row_index][current_col_index] = grid[current_row_index][current_col_index] + grid[current_row_index - 1][current_col_index]
                
                if current_col_index > 0:
                    grid[current_row_index][current_col_index] = grid[current_row_index][current_col_index] + grid[current_row_index][current_col_index - 1]
                
                if current_row_index > 0 and current_col_index > 0:
                    grid[current_row_index][current_col_index] = grid[current_row_index][current_col_index] - grid[current_row_index - 1][current_col_index - 1]

                if grid[current_row_index][current_col_index] <= sum_threshold:
                    count_of_valid_submatrices = count_of_valid_submatrices + 1
                else:
                    break
                
                current_col_index = current_col_index + 1
            
            current_row_index = current_row_index + 1

        return count_of_valid_submatrices