# LeetCode Daily Challenge
# Date: 2026-09-06
# Problem: #115 Distinct Subsequences
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def numDistinct(self, s: str, t: str) -> int:
        table_dp = [[0] * (len(s) + 1) for _ in range(len(t) + 1)]
        
        for col_idx in range(len(table_dp[0])):
            table_dp[0][col_idx] = 1
            
        for source_idx in range(1, len(s) + 1):
            for target_idx in range(1, len(t) + 1):
                if s[source_idx - 1] == t[target_idx - 1]:
                    table_dp[target_idx][source_idx] = table_dp[target_idx - 1][source_idx - 1] + table_dp[target_idx][source_idx - 1]
                else:
                    table_dp[target_idx][source_idx] = table_dp[target_idx][source_idx - 1]
                    
        return table_dp[-1][-1]