# LeetCode Daily Challenge
# Date: 2026-06-19
# Problem: Find the Highest Altitude
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def largestAltitude(self, gain_values: List[int]) -> int:
        current_elevation = 0
        maximum_elevation_achieved = 0
        
        index_tracker = 0
        total_points = len(gain_values)
        
        while index_tracker < total_points:
            current_elevation += gain_values[index_tracker]
            maximum_elevation_achieved = max(maximum_elevation_achieved, current_elevation)
            index_tracker += 1
            
        return maximum_elevation_achieved