# LeetCode Daily Challenge
# Date: 2026-10-03
# Problem: #32 Longest Valid Parentheses
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def longestValidParentheses(self, s: str) -> int:
        max_valid_length = 0
        index_stack = [-1]
        
        for current_index, char in enumerate(s):
            if char == '(':
                index_stack.append(current_index)
            else:
                index_stack.pop()
                if not index_stack:
                    index_stack.append(current_index)
                else:
                    max_valid_length = max(max_valid_length, current_index - index_stack[-1])
                    
        return max_valid_length