# LeetCode Daily Challenge
# Date: 2026-05-09
# Problem: Cyclically Rotating a Grid
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def rotateGrid(self, input_matrix: List[List[int]], rotation_steps: int) -> List[List[int]]:

        rows_count, cols_count = len(input_matrix), len(input_matrix[0])

        # --- Extract elements of the current grid's outer layer ---
        
        # Elements from the top row
        current_column_index = 0
        top_elements_list = []
        while current_column_index < cols_count:
            top_elements_list.append(input_matrix[0][current_column_index])
            current_column_index += 1

        # Elements from the rightmost column (excluding corners)
        current_row_index_for_right = 1
        right_elements_list = []
        while current_row_index_for_right < rows_count - 1:
            right_elements_list.append(input_matrix[current_row_index_for_right][cols_count - 1])
            current_row_index_for_right += 1

        # Elements from the bottom row (collected in reverse order)
        current_column_index_for_bottom = cols_count - 1
        bottom_elements_list = []
        while current_column_index_for_bottom >= 0:
            bottom_elements_list.append(input_matrix[rows_count - 1][current_column_index_for_bottom])
            current_column_index_for_bottom -= 1

        # Elements from the leftmost column (excluding corners, collected in reverse order)
        current_row_index_for_left = rows_count - 2 
        left_elements_list = []
        while current_row_index_for_left >= 1:
            left_elements_list.append(input_matrix[current_row_index_for_left][0])
            current_row_index_for_left -= 1
        
        outer_layer_combined = top_elements_list + right_elements_list + bottom_elements_list + left_elements_list

        # --- Extract the inner subgrid ---
        
        inner_matrix_segment = []
        # An inner subgrid exists if both dimensions are greater than 2
        if rows_count > 2 and cols_count > 2: 
            inner_segment_row_idx = 1
            while inner_segment_row_idx < rows_count - 1:
                current_inner_segment_row = []
                inner_segment_col_idx = 1
                while inner_segment_col_idx < cols_count - 1:
                    current_inner_segment_row.append(input_matrix[inner_segment_row_idx][inner_segment_col_idx])
                    inner_segment_col_idx += 1
                inner_matrix_segment.append(current_inner_segment_row)
                inner_segment_row_idx += 1

        # --- Perform rotation on the outer layer ---
        
        combined_layer_length = len(outer_layer_combined)
        actual_rotations_needed = rotation_steps % combined_layer_length
        rotated_layer_result = outer_layer_combined[actual_rotations_needed:] + outer_layer_combined[:actual_rotations_needed]

        # --- Recursively rotate the inner subgrid if it exists ---
        
        # Check if inner_matrix_segment is not empty and has at least one row
        if inner_matrix_segment and inner_matrix_segment[0]: 
            inner_matrix_segment = self.rotateGrid(inner_matrix_segment, rotation_steps)

        # --- Reconstruct the full grid from rotated parts ---
        
        # Pointers for extracting segments from the rotated_layer_result
        current_segment_start_index = 0
        
        reconstructed_top_row = rotated_layer_result[current_segment_start_index : current_segment_start_index + cols_count]
        current_segment_start_index += cols_count
        
        reconstructed_right_col = rotated_layer_result[current_segment_start_index : current_segment_start_index + (rows_count - 2)]
        current_segment_start_index += (rows_count - 2)
        
        # Bottom row was collected reversed, so it needs to be reversed again for reconstruction
        reconstructed_bottom_row_temp = rotated_layer_result[current_segment_start_index : current_segment_start_index + cols_count]
        current_segment_start_index += cols_count
        reconstructed_bottom_row = reconstructed_bottom_row_temp[::-1] 

        # Left column was collected reversed, so it needs to be reversed again for reconstruction
        reconstructed_left_col_temp = rotated_layer_result[current_segment_start_index : current_segment_start_index + (rows_count - 2)]
        reconstructed_left_col = reconstructed_left_col_temp[::-1] 

        # Build the intermediate rows of the grid
        middle_grid_rows = []
        
        row_build_counter = 0
        # Number of middle rows is rows_count - 2
        while row_build_counter < (rows_count - 2): 
            leftmost_element = [reconstructed_left_col[row_build_counter]]
            rightmost_element = [reconstructed_right_col[row_build_counter]]
            
            # If inner_matrix_segment is empty (e.g., 2xN or Nx2 grid), this part will be empty
            central_row_segment = inner_matrix_segment[row_build_counter] if inner_matrix_segment else []
            
            middle_grid_rows.append(leftmost_element + central_row_segment + rightmost_element)
            row_build_counter += 1

        # Assemble the final matrix
        final_result_matrix = [reconstructed_top_row] + middle_grid_rows + [reconstructed_bottom_row]

        return final_result_matrix