# LeetCode Daily Challenge
# Date: 2026-08-30
# Problem: Removing Minimum and Maximum From Array
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def minimumDeletions(self, nums: List[int]) -> int:
        array_size = len(nums)
        
        if array_size == 0:
            return 0
        
        current_min_value = float('inf')
        current_max_value = float('-inf')
        
        index_of_min_val = -1
        index_of_max_val = -1
        
        loop_counter = 0
        while loop_counter < array_size:
            element_at_current_pos = nums[loop_counter]
            
            if element_at_current_pos < current_min_value:
                current_min_value = element_at_current_pos
                index_of_min_val = loop_counter
            
            if element_at_current_pos > current_max_value:
                current_max_value = element_at_current_pos
                index_of_max_val = loop_counter
            
            loop_counter += 1
        
        # Strategy 1: Remove both targets from the left side.
        # Requires deleting all elements up to and including the one that is further from the left.
        deletions_from_left_side_only = max(index_of_min_val, index_of_max_val) + 1
        
        # Strategy 2: Remove both targets from the right side.
        # Requires deleting all elements up to and including the one that is further from the right.
        # The 0-indexed position from the right for an element at index 'i' is (array_size - 1 - i).
        deletions_from_right_side_only = max(array_size - 1 - index_of_min_val, array_size - 1 - index_of_max_val) + 1
        
        # Strategy 3: Remove one target from the left and the other from the right.
        # There are two sub-cases:
        
        # Sub-case A: Minimum from left, Maximum from right
        # Elements to remove from left: (index_of_min_val + 1)
        # Elements to remove from right: (array_size - index_of_max_val)
        deletions_min_from_left_max_from_right = (index_of_min_val + 1) + (array_size - index_of_max_val)
        
        # Sub-case B: Maximum from left, Minimum from right
        # Elements to remove from left: (index_of_max_val + 1)
        # Elements to remove from right: (array_size - index_of_min_val)
        deletions_max_from_left_min_from_right = (index_of_max_val + 1) + (array_size - index_of_min_val)
        
        # The minimum number of deletions is the smallest among all calculated strategies.
        return min(deletions_from_left_side_only,
                   deletions_from_right_side_only,
                   deletions_min_from_left_max_from_right,
                   deletions_max_from_left_min_from_right)