# LeetCode Daily Challenge
# Date: 2026-04-05
# Problem: Robot Return to Origin
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def judgeCircle(self, movement_path: str) -> bool:
        # Calculate the total count for each directional movement
        count_left_moves = movement_path.count('L')
        count_right_moves = movement_path.count('R')
        count_up_moves = movement_path.count('U')
        count_down_moves = movement_path.count('D')

        # Determine if horizontal movement cancels out
        horizontal_equilibrium = (count_left_moves == count_right_moves)
        
        # Determine if vertical movement cancels out
        vertical_equilibrium = (count_up_moves == count_down_moves)
        
        # The robot returns to the starting point if both horizontal and vertical movements are balanced
        return horizontal_equilibrium and vertical_equilibrium