# LeetCode Daily Challenge
# Date: 2026-04-27
# Problem: Check if There is a Valid Path in a Grid
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

from collections import deque

class Solution:
    road_segments = [
        [(0, -1), (0, 1)],
        [(-1, 0), (1, 0)],
        [(0, -1), (1, 0)],
        [(0, 1), (1, 0)],
        [(0, -1), (-1, 0)],
        [(0, 1), (-1, 0)]
    ]

    def hasValidPath(self, road_map: list[list[int]]) -> bool:
        grid_height = len(road_map)
        grid_width = len(road_map[0])

        traversed_cells = [[False for _ in range(grid_width)] for _ in range(grid_height)]
        
        exploration_queue = deque()

        exploration_queue.append((0, 0))
        traversed_cells[0][0] = True

        while exploration_queue:
            current_row_idx, current_col_idx = exploration_queue.popleft()
            
            current_road_id = road_map[current_row_idx][current_col_idx] - 1

            for row_change, col_change in self.road_segments[current_road_id]:
                next_row_pos = current_row_idx + row_change
                next_col_pos = current_col_idx + col_change

                if (0 <= next_row_pos < grid_height and 
                    0 <= next_col_pos < grid_width and 
                    not traversed_cells[next_row_pos][next_col_pos]):
                    
                    next_road_id = road_map[next_row_pos][next_col_pos] - 1
                    for reverse_row_change, reverse_col_change in self.road_segments[next_road_id]:
                        if (next_row_pos + reverse_row_change == current_row_idx and 
                            next_col_pos + reverse_col_change == current_col_idx):
                            
                            traversed_cells[next_row_pos][next_col_pos] = True
                            exploration_queue.append((next_row_pos, next_col_pos))
                            break 
        
        return traversed_cells[grid_height - 1][grid_width - 1]