# LeetCode Daily Challenge
# Date: 2026-07-08
# Problem: Concatenate Non-Zero Digits and Multiply by Sum II
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def sumAndMultiply(self, s: str, queries: list[list[int]]) -> list[int]:
        sequence_length = len(s)
        
        sum_prefix_array = [0] * (sequence_length + 1)
        value_prefix_array = [0] * (sequence_length + 1)
        nonzero_count_prefix = [0] * (sequence_length + 1)

        current_idx = 0
        while current_idx < sequence_length:
            digit_val = int(s[current_idx])
            
            sum_prefix_array[current_idx + 1] = sum_prefix_array[current_idx] + digit_val
            
            if digit_val != 0:
                value_prefix_array[current_idx + 1] = (value_prefix_array[current_idx] * 10 + digit_val) % MOD
                nonzero_count_prefix[current_idx + 1] = nonzero_count_prefix[current_idx] + 1
            else:
                value_prefix_array[current_idx + 1] = value_prefix_array[current_idx]
                nonzero_count_prefix[current_idx + 1] = nonzero_count_prefix[current_idx]
            
            current_idx += 1

        final_results_list = []

        for left_boundary, right_boundary in queries:
            adjusted_right_boundary = right_boundary + 1

            power_exponent = nonzero_count_prefix[adjusted_right_boundary] - nonzero_count_prefix[left_boundary]
            prefix_value_to_remove = (value_prefix_array[left_boundary] * pow[power_exponent]) % MOD
            
            segment_value_mod = (value_prefix_array[adjusted_right_boundary] - prefix_value_to_remove + MOD) % MOD

            segment_digit_sum = sum_prefix_array[adjusted_right_boundary] - sum_prefix_array[left_boundary]

            final_results_list.append((segment_value_mod * segment_digit_sum) % MOD)

        return final_results_list