# LeetCode Daily Challenge
# Date: 2026-07-01
# Problem: Find the Safest Path in a Grid
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

import collections

class Solution:
    _row_directions = [-1, 1, 0, 0]
    _col_directions = [0, 0, -1, 1]

    def _is_valid_position(self, current_row: int, current_col: int, grid_visited: list[list[bool]]) -> bool:
        rows_count = len(grid_visited)
        cols_count = len(grid_visited[0])
        
        if (current_row < 0 or current_col < 0 or 
            current_row >= rows_count or current_col >= cols_count or 
            grid_visited[current_row][current_col]):
            return False
        return True

    def _can_reach_destination_with_safeness(self, min_distance_matrix: list[list[int]], required_safeness: int) -> bool:
        grid_dimension = len(min_distance_matrix)
        bfs_queue = collections.deque()
        
        if min_distance_matrix[0][0] < required_safeness:
            return False
        
        bfs_queue.append((0, 0))
        
        visited_cells = [[False for _ in range(grid_dimension)] for _ in range(grid_dimension)]
        visited_cells[0][0] = True
        
        while bfs_queue:
            current_r, current_c = bfs_queue.popleft()
            
            if current_r == grid_dimension - 1 and current_c == grid_dimension - 1:
                return True
            
            direction_index = 0
            while direction_index < 4: 
                next_r = current_r + self._row_directions[direction_index]
                next_c = current_c + self._col_directions[direction_index]
                
                if self._is_valid_position(next_r, next_c, visited_cells):
                    if min_distance_matrix[next_r][next_c] < required_safeness:
                        pass
                    else:
                        visited_cells[next_r][next_c] = True
                        bfs_queue.append((next_r, next_c))
                direction_index += 1
        
        return False

    def maximumSafenessFactor(self, grid: list[list[int]]) -> int:
        grid_size = len(grid)
        
        multi_source_bfs_queue = collections.deque()
        bfs_visited_cells = [[False for _ in range(grid_size)] for _ in range(grid_size)]
        
        distance_to_nearest_thief = [[float('inf') for _ in range(grid_size)] for _ in range(grid_size)]
        
        for row_idx in range(grid_size):
            for col_idx in range(grid_size):
                if grid[row_idx][col_idx] == 1:
                    bfs_visited_cells[row_idx][col_idx] = True
                    multi_source_bfs_queue.append((row_idx, col_idx))
                    distance_to_nearest_thief[row_idx][col_idx] = 0

        current_distance_level = 0
        while multi_source_bfs_queue:
            level_items_count = len(multi_source_bfs_queue)
            
            for _ in range(level_items_count): 
                r_coord, c_coord = multi_source_bfs_queue.popleft()
                
                dir_idx_iterator = 0
                while dir_idx_iterator < 4:
                    next_r_coord = r_coord + self._row_directions[dir_idx_iterator]
                    next_c_coord = c_coord + self._col_directions[dir_idx_iterator]
                    
                    if not self._is_valid_position(next_r_coord, next_c_coord, bfs_visited_cells):
                        dir_idx_iterator += 1
                        continue 
                    
                    bfs_visited_cells[next_r_coord][next_c_coord] = True
                    distance_to_nearest_thief[next_r_coord][next_c_coord] = current_distance_level + 1
                    multi_source_bfs_queue.append((next_r_coord, next_c_coord))
                    dir_idx_iterator += 1
            current_distance_level += 1

        lower_bound_safeness = 0
        upper_bound_safeness = grid_size * grid_size * 2
        best_safeness_found = 0
        
        while lower_bound_safeness <= upper_bound_safeness:
            current_mid_safeness = lower_bound_safeness + (upper_bound_safeness - lower_bound_safeness) // 2
            
            if self._can_reach_destination_with_safeness(distance_to_nearest_thief, current_mid_safeness):
                best_safeness_found = current_mid_safeness
                lower_bound_safeness = current_mid_safeness + 1
            else:
                upper_bound_safeness = current_mid_safeness - 1
        
        return best_safeness_found