# LeetCode Daily Challenge
# Date: 2026-06-25
# Problem: Count Subarrays With Majority Element I
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def countMajoritySubarrays(self, nums: list[int], target: int) -> int:
        input_size = len(nums)

        # This array stores the frequency of each (balance_value + input_size).
        # The balance_value ranges from -input_size to +input_size.
        # So, indices range from 0 to 2 * input_size.
        prefix_balance_map = [0] * (2 * input_size + 1)

        # An initial balance of 0 (empty prefix) is considered.
        # Its shifted index is 'input_size'.
        prefix_balance_map[input_size] = 1

        # 'shifted_balance_sum' tracks the current running balance,
        # shifted by 'input_size' to keep it non-negative.
        # Starts at 'input_size' for an initial balance of 0.
        shifted_balance_sum = input_size

        # 'less_equal_balance_count' accumulates the sum of frequencies
        # for all shifted balances less than or equal to 'shifted_balance_sum'.
        # This effectively counts valid starting points for current ending point.
        less_equal_balance_count = 0

        # 'majority_subarray_tally' will store the final count of desired subarrays.
        majority_subarray_tally = 0

        # Iterate through the input numbers using an index for a 'while' loop.
        current_index = 0
        while current_index < input_size:
            element_value = nums[current_index]

            if element_value == target:
                # If the current element is the target, the balance increases.
                # Before updating the balance, add the count of the *current*
                # shifted_balance_sum from prefix_balance_map to less_equal_balance_count.
                # This contributes to subarrays ending here with the *previous* balance.
                less_equal_balance_count += prefix_balance_map[shifted_balance_sum]

                # Increment the shifted balance.
                shifted_balance_sum += 1
                # Mark the occurrence of this new shifted balance.
                prefix_balance_map[shifted_balance_sum] += 1
            else:
                # If the current element is not the target, the balance decreases.
                # First, decrement the shifted balance.
                shifted_balance_sum -= 1
                # Then, subtract the count of this *new* shifted_balance_sum
                # from less_equal_balance_count. This adjusts the cumulative sum
                # to reflect the new, lower upper bound.
                less_equal_balance_count -= prefix_balance_map[shifted_balance_sum]
                # Mark the occurrence of this new shifted balance.
                prefix_balance_map[shifted_balance_sum] += 1

            # Add the accumulated less_equal_balance_count to the total tally.
            # This represents all subarrays ending at current_index that satisfy the condition.
            majority_subarray_tally += less_equal_balance_count
            current_index += 1

        return majority_subarray_tally