# LeetCode Daily Challenge
# Date: 2026-09-30
# Problem: #1111 Maximum Nesting Depth of Two Valid Parentheses Strings
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def maxDepthAfterSplit(self, seq: str) -> List[int]:
        split_result = []
        current_depth_indicator = 1
        
        for char in seq:
            if char == '(':
                if current_depth_indicator == 0:
                    split_result.append(1)
                else:
                    split_result.append(0)
            else:
                split_result.append(current_depth_indicator)
                
            if current_depth_indicator == 0:
                current_depth_indicator = 1
            else:
                current_depth_indicator = 0
                
        return split_result