# LeetCode Daily Challenge
# Date: 2026-08-19
# Problem: Cinema Seat Allocation
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def maxNumberOfFamilies(self, total_rows: int, seat_reservations: list[list[int]]) -> int:
        # A dictionary to store the bitmask of occupied seats for each row.
        # The key is the row index (1-based), and the value is an integer
        # where the k-th bit is set if seat 'k' in that row is reserved.
        occupied_seats_by_row = {}

        # Iterate through each reservation entry to populate the occupancy bitmasks.
        for reservation_entry in seat_reservations:
            row_identifier = reservation_entry[0]
            seat_column_index = reservation_entry[1]
            # Use bitwise OR to set the specific bit corresponding to the reserved seat.
            # If the row is not yet in the dictionary, default to 0 (no seats reserved).
            occupied_seats_by_row[row_identifier] = occupied_seats_by_row.get(row_identifier, 0) | (1 << seat_column_index)

        # Initialize a counter for the total number of families that can be seated
        # in rows that have at least one reservation.
        families_in_processed_rows = 0

        # Define bitmasks for the three possible 4-seat family groupings.
        # Group 1: Seats 2, 3, 4, 5 (binary: 00111100)
        LEFT_AISLE_GROUP = 0b00111100
        # Group 2: Seats 6, 7, 8, 9 (binary: 1111000000)
        RIGHT_AISLE_GROUP = 0b1111000000
        # Group 3: Seats 4, 5, 6, 7 (binary: 0011110000)
        MIDDLE_AISLE_GROUP = 0b0011110000

        # Process each row that has at least one reserved seat.
        # We iterate over items to get both row_id and its mask directly.
        for current_row_id, current_row_occupancy_mask in occupied_seats_by_row.items():
            
            # Determine how many families can be seated in the current row.
            families_for_this_row = 0

            # Check if the left aisle group (seats 2-5) is completely free.
            is_left_available = (current_row_occupancy_mask & LEFT_AISLE_GROUP) == 0
            # Check if the right aisle group (seats 6-9) is completely free.
            is_right_available = (current_row_occupancy_mask & RIGHT_AISLE_GROUP) == 0

            if is_left_available and is_right_available:
                # If both independent groups are available, two families can be seated.
                families_for_this_row = 2
            elif is_left_available or is_right_available:
                # If only one of the independent groups (left or right) is available, one family can be seated.
                families_for_this_row = 1
            else:
                # If neither the left nor the right aisle group is fully available,
                # check if the middle group (seats 4-7) is available.
                # This check is only performed if no families could be seated in the aisle groups.
                if (current_row_occupancy_mask & MIDDLE_AISLE_GROUP) == 0:
                    families_for_this_row = 1
            
            families_in_processed_rows += families_for_this_row
        
        # Calculate the number of rows that had no reservations at all.
        # Each such row can accommodate two families (one in the left group, one in the right).
        unreserved_row_count = total_rows - len(occupied_seats_by_row)
        families_in_unreserved_rows = unreserved_row_count * 2

        # The total maximum number of families is the sum from rows with reservations
        # and rows without any reservations.
        return families_in_processed_rows + families_in_unreserved_rows