# LeetCode Daily Challenge
# Date: 2026-09-04
# Problem: #3903 Smallest Stable Index I
# Language: python3
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution:
    def firstStableIndex(self, nums: list[int], k: int) -> int:
        total_elements = len(nums)
        suffix_minimums = [0] * total_elements

        current_min = nums[-1]
        for index in range(total_elements - 1, -1, -1):
            current_min = min(current_min, nums[index])
            suffix_minimums[index] = current_min
        
        current_max = nums[0]
        for index, value in enumerate(nums):
            current_max = max(current_max, value)
            if current_max - suffix_minimums[index] <= k:
                return index

        return -1