# LeetCode Daily Challenge
# Date: 2026-05-13
# Problem: Minimum Moves to Make Array Complementary
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from typing import List
import collections
import math

class Solution:
    def minMoves(self, nums: List[int], limit: int) -> int:
        move_adjustments = collections.defaultdict(int)
        
        array_length = len(nums)
        
        current_pair_index = 0
        while current_pair_index < array_length // 2:
            left_num = nums[current_pair_index]
            right_num = nums[array_length - 1 - current_pair_index]
            
            move_adjustments[2] += 2
            move_adjustments[min(left_num, right_num) + 1] -= 1
            move_adjustments[left_num + right_num] -= 1
            move_adjustments[left_num + right_num + 1] += 1
            move_adjustments[max(left_num, right_num) + limit + 1] += 1
            
            current_pair_index += 1
            
        accumulated_moves_count = 0            
        minimum_overall_moves = math.inf
        
        current_sum_target = 2
        max_sum_target = 2 * limit
        
        while current_sum_target <= max_sum_target:
            accumulated_moves_count += move_adjustments[current_sum_target]
            minimum_overall_moves = min(minimum_overall_moves, accumulated_moves_count)
            current_sum_target += 1
            
        return minimum_overall_moves