# LeetCode Daily Challenge
# Date: 2026-07-11
# Problem: Count the Number of Complete Components
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def _explore_component(self, current_vertex_id, graph_connections, visited_tracker):
        traversal_stack = [current_vertex_id]
        visited_tracker[current_vertex_id] = True
        
        component_vertex_count = 0
        component_degree_sum = 0
        
        while traversal_stack:
            processed_vertex = traversal_stack.pop()
            component_vertex_count += 1
            component_degree_sum += len(graph_connections[processed_vertex])
            
            for adjacent_vertex in graph_connections[processed_vertex]:
                if not visited_tracker[adjacent_vertex]:
                    visited_tracker[adjacent_vertex] = True
                    traversal_stack.append(adjacent_vertex)
                    
        return component_vertex_count, component_degree_sum

    def countCompleteComponents(self, total_vertices, input_edges):
        adj_list = [[] for _ in range(total_vertices)]
        
        edge_idx = 0
        while edge_idx < len(input_edges):
            current_edge = input_edges[edge_idx]
            vertex_a, vertex_b = current_edge[0], current_edge[1]
            adj_list[vertex_a].append(vertex_b)
            adj_list[vertex_b].append(vertex_a)
            edge_idx += 1

        node_is_visited = [False] * total_vertices
        num_complete_components = 0

        vertex_scanner = 0
        while vertex_scanner < total_vertices:
            if not node_is_visited[vertex_scanner]:
                current_component_vertices, current_component_degrees = \
                    self._explore_component(vertex_scanner, adj_list, node_is_visited)

                # For a complete graph with V vertices, the number of edges E = V * (V - 1) / 2.
                # The sum of degrees for such a graph is 2 * E = V * (V - 1).
                if current_component_vertices * (current_component_vertices - 1) == current_component_degrees:
                    num_complete_components += 1
            vertex_scanner += 1

        return num_complete_components