# LeetCode Daily Challenge
# Date: 2026-08-05
# Problem: Remove Methods From Project
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from collections import deque

class Solution:
    def remainingMethods(self, n: int, k: int, invocations: List[List[int]]) -> List[int]:
        method_dependencies = {method_idx: [] for method_idx in range(n)}
        for calling_method, called_method in invocations:
            method_dependencies[calling_method].append(called_method)

        exploration_queue = deque([k])
        reachable_methods_set = {k}
        while exploration_queue:
            current_node_identifier = exploration_queue.popleft()
            for connected_node in method_dependencies[current_node_identifier]:
                if connected_node not in reachable_methods_set:
                    reachable_methods_set.add(connected_node)
                    exploration_queue.append(connected_node)
                    
        unaffected_method_identifiers = []
        current_method_evaluator = 0
        while current_method_evaluator < n:
            if current_method_evaluator in reachable_methods_set:
                current_method_evaluator += 1
                continue
            
            for invoked_dependency in method_dependencies[current_method_evaluator]:
                if invoked_dependency in reachable_methods_set:
                    return list(range(n))
            
            unaffected_method_identifiers.append(current_method_evaluator)
            current_method_evaluator += 1
            
        return unaffected_method_identifiers