# LeetCode Daily Challenge
# Date: 2026-04-28
# Problem: Minimum Operations to Make a Uni-Value Grid
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def minOperations(self, grid: list[list[int]], x: int) -> int:
        all_grid_values = []
        grid_rows_count = len(grid)
        grid_cols_count = len(grid[0])

        current_row_index = 0
        while current_row_index < grid_rows_count:
            current_col_index = 0
            while current_col_index < grid_cols_count:
                all_grid_values.append(grid[current_row_index][current_col_index])
                current_col_index += 1
            current_row_index += 1

        all_grid_values.sort()

        total_elements_count = len(all_grid_values)
        median_element_index = total_elements_count // 2
        central_pivot_value = all_grid_values[median_element_index]

        cumulative_operations = 0
        
        iteration_pointer = 0
        while iteration_pointer < total_elements_count:
            current_grid_item = all_grid_values[iteration_pointer]
            absolute_val_difference = abs(current_grid_item - central_pivot_value)
            
            if absolute_val_difference % x != 0:
                return -1
            
            cumulative_operations += absolute_val_difference // x
            iteration_pointer += 1
            
        return cumulative_operations