# LeetCode Daily Challenge
# Date: 2026-09-05
# Problem: #3904 Smallest Stable Index II
# Language: mysql
# Submission Result: Submission Sent (Check LeetCode Profile)
# Auto-generated by LeetCode Agent

class Solution {
public:
    int firstStableIndex(vector<int>& nums, int k) {
        int length_nums = nums.size();

        int candidate_index = 0;         
        int max_overall = INT_MIN;          
        int max_candidate = INT_MIN;   

        for (int idx = 0; idx < length_nums; idx++) {
            max_overall = max(max_overall, nums[idx]);

            if (idx == candidate_index)
                max_candidate = max(max_candidate, nums[idx]);

            if (nums[idx] < max_candidate - k) {
                candidate_index = idx + 1;
                max_candidate = max_overall;
            }
        }

        return candidate_index < length_nums ? candidate_index : -1;
    }
};