# LeetCode Daily Challenge
# Date: 2026-07-04
# Problem: Minimum Score of a Path Between Two Cities
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

from queue import Queue
from sys import maxsize

class Solution:
    def minScore(self, n: int, roads_data: list[list[int]]) -> int:
        minimum_path_score = maxsize
        
        # Initialize an adjacency list for the graph
        graph_connections = [[] for _ in range(n + 1)]
        
        # Populate the adjacency list with road information
        # Each road connects two cities with a specific distance
        for current_road_details in roads_data:
            city_a = current_road_details[0]
            city_b = current_road_details[1]
            road_distance = current_road_details[2]
            
            graph_connections[city_a].append((city_b, road_distance))
            graph_connections[city_b].append((city_a, road_distance))

        # Initialize a tracker for visited cities using booleans
        cities_visited_status = [False] * (n + 1)
        
        # Use a queue for Breadth-First Search (BFS)
        cities_queue = Queue()
        
        # Start BFS from city 1 (as per problem statement, all cities are reachable from 1)
        cities_queue.put(1)
        cities_visited_status[1] = True
        
        # Process cities in the queue until it's empty
        while not cities_queue.empty():
            current_city_id = cities_queue.get()
            
            # Explore all neighbors of the current city
            for connected_city, segment_distance in graph_connections[current_city_id]:
                # Update the minimum score found so far
                minimum_path_score = min(minimum_path_score, segment_distance)
                
                # If the connected city has not been visited yet
                if not cities_visited_status[connected_city]:
                    cities_visited_status[connected_city] = True
                    cities_queue.put(connected_city)
        
        return minimum_path_score