# LeetCode Daily Challenge
# Date: 2026-08-14
# Problem: Maximum Length Substring With Two Occurrences
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

from collections import defaultdict

class Solution:
    def maximumLengthSubstring(self, s: str) -> int:
        char_frequencies = defaultdict(int)
        max_valid_length = 0
        left_index = 0
        right_index = 0
        string_length = len(s)

        while right_index < string_length:
            char_at_right = s[right_index]
            char_frequencies[char_at_right] += 1

            while char_frequencies[char_at_right] > 2:
                char_at_left = s[left_index]
                char_frequencies[char_at_left] -= 1
                left_index += 1

            current_window_span = right_index - left_index + 1
            max_valid_length = max(max_valid_length, current_window_span)

            right_index += 1

        return max_valid_length