# LeetCode Daily Challenge
# Date: 2026-07-19
# Problem: Smallest Subsequence of Distinct Characters
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution(object):
    def smallestSubsequence(self, text):
        """
        :type text: str
        :rtype: str
        """
        last_occurrence_map = {}
        result_characters = []
        present_in_result = set()

        # First pass: Determine the last index of each character in the input string
        current_position_index = 0
        string_total_length = len(text)
        while current_position_index < string_total_length:
            character_at_pos = text[current_position_index]
            last_occurrence_map[character_at_pos] = current_position_index
            current_position_index += 1

        # Second pass: Build the lexicographically smallest subsequence
        current_position_index = 0
        while current_position_index < string_total_length:
            processing_char_value = text[current_position_index]

            if processing_char_value in present_in_result:
                current_position_index += 1
                continue

            # While the result sequence is not empty,
            # the current character is smaller than the last character in the result,
            # and the last character in the result will appear again later in the string,
            # pop from the result.
            while (result_characters and
                   processing_char_value < result_characters[-1] and
                   last_occurrence_map[result_characters[-1]] > current_position_index):
                
                popped_from_result = result_characters.pop()
                present_in_result.remove(popped_from_result)
            
            present_in_result.add(processing_char_value)
            result_characters.append(processing_char_value)
            current_position_index += 1
            
        return ''.join(result_characters)