# LeetCode Daily Challenge
# Date: 2026-05-11
# Problem: Separate the Digits in an Array
# Submission Result: Error interacting with browser
# Auto-generated by LeetCode Agent

class Solution:
    def separateDigits(self, numbers_list: List[int]) -> List[int]:
        result_collector = []
        
        current_index = 0
        list_length = len(numbers_list)

        while current_index < list_length:
            processing_number = numbers_list[current_index]
            
            # Convert the number to its individual digits using a list comprehension
            extracted_digit_sequence = [int(char_digit) for char_digit in str(processing_number)]
            
            result_collector.extend(extracted_digit_sequence)
            
            current_index += 1
            
        return result_collector