# LeetCode Daily Challenge
# Date: 2026-03-08
# Problem: Find Unique Binary String
# Submission Result: Timeout waiting for result (check browser)
# Auto-generated by LeetCode Agent

class Solution:
    def findDifferentBinaryString(self, nums: List[str]) -> str:
        # Convert all input binary strings to their integer representations and store in a set for quick lookup
        existing_integer_values = {int(binary_string_val, 2) for binary_string_val in nums}

        # Determine the fixed length of the binary strings
        target_length = len(nums[0])

        # Calculate the total number of possible binary strings of this length (2^target_length)
        # We will iterate through all possible integer values from 0 up to (2^target_length - 1)
        total_possible_count = 1 << target_length # Using bit shift for 2^N

        current_candidate_integer = 0
        while current_candidate_integer < total_possible_count:
            # If the current integer value is not found in our set of existing values,
            # then its binary representation is the different string we are looking for.
            if current_candidate_integer not in existing_integer_values:
                # Convert the integer back to its binary string representation (e.g., bin(3) -> '0b11')
                # Remove the '0b' prefix
                unpadded_binary_string = bin(current_candidate_integer)[2:]

                # Pad the binary string with leading zeros to match the target length
                # Example: if target_length=3 and unpadded_binary_string='11', it becomes '011'
                return unpadded_binary_string.zfill(target_length)
            
            # Move to the next integer candidate
            current_candidate_integer += 1
        
        # This part of the code should theoretically not be reached given the problem constraints
        # (there's always exactly one unique binary string for valid inputs)
        return "-1"